/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package notImplemented;

/**
 *
 * @author Krist
 */
public class HanteraProjekt extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HanteraProjekt.class.getName());
    

    /**
     * Creates new form HanteraProjekt
     */
    public HanteraProjekt() {
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLblRubrik = new javax.swing.JLabel();
        JPanelProjekt = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableListaProjekt = new javax.swing.JTable();
        JLblProjektID = new javax.swing.JLabel();
        JLblProjektNamn = new javax.swing.JLabel();
        JLblProjektStatus = new javax.swing.JLabel();
        JTxtFieldProjektID = new javax.swing.JTextField();
        JTxtFieldProjektNamn = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        JBtnLaggTillProjekt = new javax.swing.JButton();
        JBtnTaBortProjekt = new javax.swing.JButton();
        JBtnÄndraProjekt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JPanelUppgifterValtProjekt = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTableUppgifter = new javax.swing.JTable();
        JLblBeskrivning = new javax.swing.JLabel();
        JLblStartDatum = new javax.swing.JLabel();
        JLblSlutDatum = new javax.swing.JLabel();
        JLblKostnader = new javax.swing.JLabel();
        JLblPrioritet = new javax.swing.JLabel();
        JLblProjektChef = new javax.swing.JLabel();
        JTxtFieldBeskrivning = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        JTxtFieldSlutDatum = new javax.swing.JTextField();
        JTxtFieldKostnader = new javax.swing.JTextField();
        JTxtFieldPrioritet = new javax.swing.JTextField();
        JTxtFieldProjektChef = new javax.swing.JTextField();
        JLblLand = new javax.swing.JLabel();
        JTxtFieldLand = new javax.swing.JTextField();
        JLblUnderRubrikProjektUppgifter = new javax.swing.JLabel();
        JBtnLaggTillUppgifter = new javax.swing.JButton();
        JBtnAndraUppgifter = new javax.swing.JButton();
        JBtnTaBortUppgifter = new javax.swing.JButton();
        JLblProjektansvarig = new javax.swing.JLabel();
        JTxtFieldProjektansvarig = new javax.swing.JTextField();
        lblTillbakaTillMeny = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLblRubrik.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JLblRubrik.setText("Hantera Projekt");

        JPanelProjekt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Projekt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        JTableListaProjekt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTableListaProjekt);

        JLblProjektID.setText("ProjektID");

        JLblProjektNamn.setText("Projektnamn");

        JLblProjektStatus.setText("ProjektStatus");

        JTxtFieldProjektID.setText("[ProjektID]");

        JTxtFieldProjektNamn.setText("[Projektnamn]");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Planerad", "Aktiv", "Pausad", "Avslutat", "Avbrutet" }));

        JBtnLaggTillProjekt.setText("Lägg till");
        JBtnLaggTillProjekt.addActionListener(this::JBtnLaggTillProjektActionPerformed);

        JBtnTaBortProjekt.setText("Ta Bort");

        JBtnÄndraProjekt.setText("Ändra");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Projektinformation:");

        javax.swing.GroupLayout JPanelProjektLayout = new javax.swing.GroupLayout(JPanelProjekt);
        JPanelProjekt.setLayout(JPanelProjektLayout);
        JPanelProjektLayout.setHorizontalGroup(
            JPanelProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelProjektLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JLblProjektStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JLblProjektNamn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JLblProjektID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(JBtnTaBortProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtnLaggTillProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanelProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelProjektLayout.createSequentialGroup()
                        .addGroup(JPanelProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTxtFieldProjektID)
                            .addComponent(JTxtFieldProjektNamn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(JPanelProjektLayout.createSequentialGroup()
                        .addComponent(JBtnÄndraProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        JPanelProjektLayout.setVerticalGroup(
            JPanelProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelProjektLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(JPanelProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(JPanelProjektLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPanelProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblProjektID)
                            .addComponent(JTxtFieldProjektID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JPanelProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblProjektNamn)
                            .addComponent(JTxtFieldProjektNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JPanelProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblProjektStatus)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(JBtnLaggTillProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JPanelProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBtnTaBortProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtnÄndraProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        JPanelUppgifterValtProjekt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Uppgifter för valt projekt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        JTableUppgifter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(JTableUppgifter);

        JLblBeskrivning.setText("Beskrivning");

        JLblStartDatum.setText("Startdatum");

        JLblSlutDatum.setText("Slutdatum");

        JLblKostnader.setText("Kostnader");

        JLblPrioritet.setText("Prioritet");

        JLblProjektChef.setText("Projektchef");

        JTxtFieldBeskrivning.setText("[Beskrivning]");

        jTextField2.setText("[Startdatum]");

        JTxtFieldSlutDatum.setText("[Slutdatum]");

        JTxtFieldKostnader.setText("[Kostnader]");

        JTxtFieldPrioritet.setText("[Prioritet]");

        JTxtFieldProjektChef.setText("[ProjektChef]");

        JLblLand.setText("Land");

        JTxtFieldLand.setText("[Land]");

        JLblUnderRubrikProjektUppgifter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLblUnderRubrikProjektUppgifter.setText("ProjektUppgifter");

        JBtnLaggTillUppgifter.setText("Lägg till");

        JBtnAndraUppgifter.setText("Ändra");

        JBtnTaBortUppgifter.setText("Ta bort");

        JLblProjektansvarig.setText("Projektansvarig");

        JTxtFieldProjektansvarig.setText("[Projektansvarig]");

        javax.swing.GroupLayout JPanelUppgifterValtProjektLayout = new javax.swing.GroupLayout(JPanelUppgifterValtProjekt);
        JPanelUppgifterValtProjekt.setLayout(JPanelUppgifterValtProjektLayout);
        JPanelUppgifterValtProjektLayout.setHorizontalGroup(
            JPanelUppgifterValtProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelUppgifterValtProjektLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JPanelUppgifterValtProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLblUnderRubrikProjektUppgifter)
                    .addGroup(JPanelUppgifterValtProjektLayout.createSequentialGroup()
                        .addGroup(JPanelUppgifterValtProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JLblProjektansvarig, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(JBtnLaggTillUppgifter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLblBeskrivning, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLblStartDatum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLblSlutDatum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLblKostnader, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLblPrioritet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLblProjektChef, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLblLand, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(JPanelUppgifterValtProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JBtnAndraUppgifter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTxtFieldBeskrivning)
                            .addComponent(jTextField2)
                            .addComponent(JTxtFieldSlutDatum)
                            .addComponent(JTxtFieldKostnader)
                            .addComponent(JTxtFieldPrioritet)
                            .addComponent(JTxtFieldProjektChef)
                            .addComponent(JTxtFieldLand)
                            .addComponent(JTxtFieldProjektansvarig))
                        .addGap(18, 18, 18)
                        .addComponent(JBtnTaBortUppgifter, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelUppgifterValtProjektLayout.setVerticalGroup(
            JPanelUppgifterValtProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelUppgifterValtProjektLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPanelUppgifterValtProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPanelUppgifterValtProjektLayout.createSequentialGroup()
                        .addComponent(JLblUnderRubrikProjektUppgifter)
                        .addGap(8, 8, 8)
                        .addGroup(JPanelUppgifterValtProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblBeskrivning)
                            .addComponent(JTxtFieldBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JPanelUppgifterValtProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblStartDatum)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JPanelUppgifterValtProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblSlutDatum)
                            .addComponent(JTxtFieldSlutDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JPanelUppgifterValtProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblKostnader)
                            .addComponent(JTxtFieldKostnader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JPanelUppgifterValtProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblPrioritet)
                            .addComponent(JTxtFieldPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JPanelUppgifterValtProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblProjektChef)
                            .addComponent(JTxtFieldProjektChef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JPanelUppgifterValtProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblProjektansvarig)
                            .addComponent(JTxtFieldProjektansvarig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JPanelUppgifterValtProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblLand)
                            .addComponent(JTxtFieldLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JPanelUppgifterValtProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBtnLaggTillUppgifter, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtnAndraUppgifter, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtnTaBortUppgifter, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTillbakaTillMeny.setText("Tillbaka till Meny");
        lblTillbakaTillMeny.addActionListener(this::lblTillbakaTillMenyActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPanelUppgifterValtProjekt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JPanelProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTillbakaTillMeny)
                                .addGap(160, 160, 160)
                                .addComponent(JLblRubrik)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblRubrik)
                    .addComponent(lblTillbakaTillMeny))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JPanelProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelUppgifterValtProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnLaggTillProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnLaggTillProjektActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtnLaggTillProjektActionPerformed

    private void lblTillbakaTillMenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblTillbakaTillMenyActionPerformed
        //new MenyHandlaggareProjektchef().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblTillbakaTillMenyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HanteraProjekt().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnAndraUppgifter;
    private javax.swing.JButton JBtnLaggTillProjekt;
    private javax.swing.JButton JBtnLaggTillUppgifter;
    private javax.swing.JButton JBtnTaBortProjekt;
    private javax.swing.JButton JBtnTaBortUppgifter;
    private javax.swing.JButton JBtnÄndraProjekt;
    private javax.swing.JLabel JLblBeskrivning;
    private javax.swing.JLabel JLblKostnader;
    private javax.swing.JLabel JLblLand;
    private javax.swing.JLabel JLblPrioritet;
    private javax.swing.JLabel JLblProjektChef;
    private javax.swing.JLabel JLblProjektID;
    private javax.swing.JLabel JLblProjektNamn;
    private javax.swing.JLabel JLblProjektStatus;
    private javax.swing.JLabel JLblProjektansvarig;
    private javax.swing.JLabel JLblRubrik;
    private javax.swing.JLabel JLblSlutDatum;
    private javax.swing.JLabel JLblStartDatum;
    private javax.swing.JLabel JLblUnderRubrikProjektUppgifter;
    private javax.swing.JPanel JPanelProjekt;
    private javax.swing.JPanel JPanelUppgifterValtProjekt;
    private javax.swing.JTable JTableListaProjekt;
    private javax.swing.JTable JTableUppgifter;
    private javax.swing.JTextField JTxtFieldBeskrivning;
    private javax.swing.JTextField JTxtFieldKostnader;
    private javax.swing.JTextField JTxtFieldLand;
    private javax.swing.JTextField JTxtFieldPrioritet;
    private javax.swing.JTextField JTxtFieldProjektChef;
    private javax.swing.JTextField JTxtFieldProjektID;
    private javax.swing.JTextField JTxtFieldProjektNamn;
    private javax.swing.JTextField JTxtFieldProjektansvarig;
    private javax.swing.JTextField JTxtFieldSlutDatum;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton lblTillbakaTillMeny;
    // End of variables declaration//GEN-END:variables
}
