/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

import oru.inf.InfDB;

/**
 *
 * @author Krist
 */
public class AdministratörMeny extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdministratörMeny.class.getName());
    private Anvandare anvandare;
    private InfDB idb;
    private int aid;
    private String namn;
    private String efternamn;
    /**
     * Creates new form Administratör
     */
    public AdministratörMeny(Anvandare anvandare) {
        initComponents();
        this.idb = anvandare.getIdb();
        this.aid = anvandare.getAid();
        this.anvandare = anvandare;
        this.namn = anvandare.getDbNamn();
        this.efternamn = anvandare.getDbEfternamn();
        this.anvandare = anvandare;
        
        JLblEpost.setText("namn: " + namn +" " + efternamn );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RubrikAdmin = new javax.swing.JLabel();
        BtnHanteraAnst = new javax.swing.JButton();
        BtnHanteraProjekt = new javax.swing.JButton();
        BtnHanteraAvd = new javax.swing.JButton();
        BtnHanteraPartner = new javax.swing.JButton();
        BtnHanteraLand = new javax.swing.JButton();
        BtnHanteraHmål = new javax.swing.JButton();
        JLblEpost = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        RubrikAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RubrikAdmin.setText("ADMIN Meny");

        BtnHanteraAnst.setText("Hantera anställd");
        BtnHanteraAnst.addActionListener(this::BtnHanteraAnstActionPerformed);

        BtnHanteraProjekt.setText("Projekt");
        BtnHanteraProjekt.addActionListener(this::BtnHanteraProjektActionPerformed);

        BtnHanteraAvd.setText("Hantera avdelning");
        BtnHanteraAvd.addActionListener(this::BtnHanteraAvdActionPerformed);

        BtnHanteraPartner.setText("Hantera Partner");
        BtnHanteraPartner.addActionListener(this::BtnHanteraPartnerActionPerformed);

        BtnHanteraLand.setText("Hantera Land");
        BtnHanteraLand.addActionListener(this::BtnHanteraLandActionPerformed);

        BtnHanteraHmål.setText("Hantera Hållbarhetsmål");
        BtnHanteraHmål.addActionListener(this::BtnHanteraHmålActionPerformed);

        JLblEpost.setText("för och efternamn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(RubrikAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(JLblEpost)
                .addGap(28, 28, 28))
            .addComponent(BtnHanteraAnst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnHanteraLand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnHanteraPartner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnHanteraAvd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnHanteraProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnHanteraHmål, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RubrikAdmin)
                    .addComponent(JLblEpost))
                .addGap(40, 40, 40)
                .addComponent(BtnHanteraAnst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnHanteraLand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnHanteraPartner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnHanteraAvd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnHanteraProjekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnHanteraHmål)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnHanteraHmålActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHanteraHmålActionPerformed
        new HanteraHållbarhetsmål(anvandare).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnHanteraHmålActionPerformed

    private void BtnHanteraAnstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHanteraAnstActionPerformed
        new HanteraAnstalld(anvandare).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnHanteraAnstActionPerformed

    private void BtnHanteraProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHanteraProjektActionPerformed
        new ProjektSokAdmin(anvandare).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnHanteraProjektActionPerformed

    private void BtnHanteraLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHanteraLandActionPerformed
        new HanteraLand(anvandare).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnHanteraLandActionPerformed

    private void BtnHanteraPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHanteraPartnerActionPerformed
        new HanteraPartner(anvandare).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnHanteraPartnerActionPerformed

    private void BtnHanteraAvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHanteraAvdActionPerformed
        new HanteraAvdelning(anvandare).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnHanteraAvdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new AdministratörMeny().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHanteraAnst;
    private javax.swing.JButton BtnHanteraAvd;
    private javax.swing.JButton BtnHanteraHmål;
    private javax.swing.JButton BtnHanteraLand;
    private javax.swing.JButton BtnHanteraPartner;
    private javax.swing.JButton BtnHanteraProjekt;
    private javax.swing.JLabel JLblEpost;
    private javax.swing.JLabel RubrikAdmin;
    // End of variables declaration//GEN-END:variables
}
