/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

/**
 *
 * @author alexander.willen, Kristoffer Kolkowski
 */
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class Hallbarhetsmal extends javax.swing.JFrame {
    private Anvandare anvandare;
    private InfDB idb;
    private DefaultTableModel bordsModell;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Hallbarhetsmal.class.getName());

    /**
     * Creates new form Hallbarhetsmal
     */
    public Hallbarhetsmal(Anvandare anvandare) {
        this.idb = anvandare.getIdb();
        this.anvandare = anvandare;
        initComponents();

        // Kopplar JTable till modell och sätter samma rubriker som i admin-fönstret
        bordsModell = (DefaultTableModel) JTableVisaMal.getModel();
        bordsModell.setColumnIdentifiers(new Object[]{"hid", "Namn", "Målnummer", "Beskrivning", "Prioritet"});

        // metod för att hämta målen från databasen
        visaAllaHallbarhetsmal();
    }

    /**
     * Metoden för att hämta hållbarhetsmål från databasen
     */
    private void visaAllaHallbarhetsmal() {

        // Tömmer eventuella testrader
        bordsModell.setRowCount(0);

        // SQLfråga för att hämta kolumnerna från tabellen hallbarhetsmal
        String SQLFraga = "SELECT hid, namn, malnummer, beskrivning, prioritet FROM hallbarhetsmal";

        try {
            ArrayList<HashMap<String, String>> rader = idb.fetchRows(SQLFraga);

            if (rader != null) {
                // Loopar igenom varje rad i databasen och lägger till i vårat JTable
                for (HashMap<String, String> rad : rader) {
                    bordsModell.addRow(new Object[]{
                        rad.get("hid"),
                        rad.get("namn"),
                        rad.get("malnummer"),
                        rad.get("beskrivning"),
                        rad.get("prioritet")
                    });
                }
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(this, "Kunde inte hämta hållbarhetsmål: " + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTillbakaTillMeny = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTableVisaMal = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Hållbarhetsmål");

        lblTillbakaTillMeny.setText("Tillbaka till Meny");
        lblTillbakaTillMeny.addActionListener(this::lblTillbakaTillMenyActionPerformed);

        JTableVisaMal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(JTableVisaMal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTillbakaTillMeny)
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTillbakaTillMeny))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnTillbakaTillMenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnTillbakaTillMenyActionPerformed
        Navigering.tillbakaTillMeny(anvandare);
        this.dispose();
    }//GEN-LAST:event_JBtnTillbakaTillMenyActionPerformed

    private void lblTillbakaTillMenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblTillbakaTillMenyActionPerformed
        Navigering.tillbakaTillMeny(anvandare);
        this.dispose();
    }//GEN-LAST:event_lblTillbakaTillMenyActionPerformed

    /**
     * Tillfällig main metod för att provköra fönstret.
     */
//    public static void main(String args[]) {
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//
//        /* Skapar en testanslutning och visar fönstret */
//        java.awt.EventQueue.invokeLater(() -> {
//            try {
//                InfDB testDb = new InfDB("sdgsweden", "3306", "root", "masterkey");
//                new Hallbarhetsmal(testDb).setVisible(true);
//            } catch (InfException e) {
//                System.out.println("Kunde inte starta testdatabasen: " + e.getMessage());
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableVisaMal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton lblTillbakaTillMeny;
    // End of variables declaration//GEN-END:variables
}
