/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

import oru.inf.InfDB;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfException;
import projListeners.AnstalldListener;

/**
 *
 * @author Krist
 */
public class HanteraAnstalld extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HanteraAnstalld.class.getName());
    private Anvandare anvandare;
    private InfDB idb;
    private AnstalldListener anstalldListener;

    public HanteraAnstalld(Anvandare anvandare) {
        initComponents();

        this.anvandare = anvandare;
        this.idb = anvandare.getIdb();
        fyllAvdelningComboBox();
        fyllRollComboBox();

        if (!anvandare.getRoll().equals("admin")) {
            //Användaren är ej admin och ska ej få tillgång till knapparna ta bort, uppdatera, lägg till och rensa
            JBtnLaggTillAnstalld.setVisible(false);
            JBtnUppdateraAnstalld.setVisible(false);
            JBtnTaBortAnstalld.setVisible(false);
            JBtnRensaUppgifteranstalld.setVisible(false);
        }

        JTxtFieldAnstalldID.setEditable(false);

        hamtaAllaAnstallda();

        jTable1.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                if (!evt.getValueIsAdjusting()) {
                    int valdRad = jTable1.getSelectedRow();
                    fyllFaltFranMarkeradRad(valdRad);
                }
            }
        });
    }

    private void fyllAvdelningComboBox() {
        try {
            cbAvdelning.removeAllItems();

            ArrayList<HashMap<String, String>> avdelningsLista = anvandare.getIdb().fetchRows(
                    "SELECT avdid, namn FROM avdelning ORDER BY namn"
            );

            for (HashMap<String, String> avdelning : avdelningsLista) {
                String avdid = avdelning.get("avdid");
                String namn = avdelning.get("namn");

                cbAvdelning.addItem(avdid + " - " + namn);
            }

        } catch (InfException ex) {
            JOptionPane.showMessageDialog(this, "Kunde inte ladda länder.");
        }
    }
    
    private void fyllRollComboBox() {
    cbRoll.removeAllItems();

    cbRoll.addItem("admin");
    cbRoll.addItem("handlaggare");
    cbRoll.addItem("handlaggare_projektchef");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLblRubrik = new javax.swing.JLabel();
        JScrollPaneListaAnställda = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JTxtFieldSökruta = new javax.swing.JTextField();
        JLblSokAnställd = new javax.swing.JLabel();
        JBtnUppdateraAnstalld = new javax.swing.JButton();
        JBtnRensaUppgifteranstalld = new javax.swing.JButton();
        JBtnTaBortAnstalld = new javax.swing.JButton();
        JBtnLaggTillAnstalld = new javax.swing.JButton();
        JLblAnstalldID = new javax.swing.JLabel();
        JTxtFieldAnstalldID = new javax.swing.JTextField();
        JLblAnstalldUppgifter = new javax.swing.JLabel();
        JLblFNamn = new javax.swing.JLabel();
        JTxtFieldFNamn = new javax.swing.JTextField();
        JLblRoll = new javax.swing.JLabel();
        JLblENamn = new javax.swing.JLabel();
        JTxtFieldENamn = new javax.swing.JTextField();
        JLblTeleNr = new javax.swing.JLabel();
        JLblPostAdress = new javax.swing.JLabel();
        JLblEpost = new javax.swing.JLabel();
        JTxtFieldTeleNr = new javax.swing.JTextField();
        JTxtFieldPostadress = new javax.swing.JTextField();
        JTxtFieldEpost = new javax.swing.JTextField();
        JLblLösen = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        JLblAvdelning = new javax.swing.JLabel();
        JLblAnstDatum = new javax.swing.JLabel();
        JTxtFieldAnstDatum = new javax.swing.JTextField();
        btnSök = new javax.swing.JButton();
        btnGenereraLösenord = new javax.swing.JButton();
        btnTillbakatillmeny = new javax.swing.JButton();
        cbAvdelning = new javax.swing.JComboBox<>();
        cbRoll = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLblRubrik.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JLblRubrik.setText("Hantera Anställda");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JScrollPaneListaAnställda.setViewportView(jTable1);

        JTxtFieldSökruta.addActionListener(this::JTxtFieldSökrutaActionPerformed);

        JLblSokAnställd.setText("Sök Anställd");

        JBtnUppdateraAnstalld.setText("Uppdatera");
        JBtnUppdateraAnstalld.addActionListener(this::JBtnUppdateraAnstalldActionPerformed);

        JBtnRensaUppgifteranstalld.setText("Rensa");
        JBtnRensaUppgifteranstalld.addActionListener(this::JBtnRensaUppgifteranstalldActionPerformed);

        JBtnTaBortAnstalld.setText("Ta bort");
        JBtnTaBortAnstalld.addActionListener(this::JBtnTaBortAnstalldActionPerformed);

        JBtnLaggTillAnstalld.setText("Lägg till");
        JBtnLaggTillAnstalld.addActionListener(this::JBtnLaggTillAnstalldActionPerformed);

        JLblAnstalldID.setText("AnställdID");

        JTxtFieldAnstalldID.setText("[AID]");

        JLblAnstalldUppgifter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLblAnstalldUppgifter.setText("Uppgifter Anställd");

        JLblFNamn.setText("Förnamn");

        JLblRoll.setText("Roll");

        JLblENamn.setText("Efternamn");

        JLblTeleNr.setText("Telefonnummer");

        JLblPostAdress.setText("Postadress");

        JLblEpost.setText("Epost");

        JTxtFieldTeleNr.addActionListener(this::JTxtFieldTeleNrActionPerformed);

        JTxtFieldPostadress.addActionListener(this::JTxtFieldPostadressActionPerformed);

        JTxtFieldEpost.addActionListener(this::JTxtFieldEpostActionPerformed);

        JLblLösen.setText("Lösen");

        jTextField5.addActionListener(this::jTextField5ActionPerformed);

        JLblAvdelning.setText("Avdelning");

        JLblAnstDatum.setText("Anställningsdatum");

        JTxtFieldAnstDatum.setText("ÅÅÅÅ-MM-DD");

        btnSök.setText("Sök");
        btnSök.addActionListener(this::btnSökActionPerformed);

        btnGenereraLösenord.setText("Generera lösenord");
        btnGenereraLösenord.addActionListener(this::btnGenereraLösenordActionPerformed);

        btnTillbakatillmeny.setText("Tillbaka till meny");
        btnTillbakatillmeny.addActionListener(this::btnTillbakatillmenyActionPerformed);

        cbAvdelning.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbRoll.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTillbakatillmeny)
                        .addGap(149, 149, 149)
                        .addComponent(JLblRubrik))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLblSokAnställd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JTxtFieldSökruta, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSök))
                    .addComponent(JScrollPaneListaAnställda, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(JLblPostAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(JTxtFieldPostadress))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(JLblEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(JTxtFieldEpost))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(JLblAnstDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(JTxtFieldAnstDatum))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(JLblLösen, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField5))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JBtnTaBortAnstalld, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(JBtnLaggTillAnstalld, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JBtnUppdateraAnstalld, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JBtnRensaUppgifteranstalld, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JLblAnstalldUppgifter)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(JLblAnstalldID, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JLblAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(JLblRoll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JLblENamn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                                    .addGap(14, 14, 14))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JLblFNamn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JTxtFieldFNamn)
                                .addComponent(cbAvdelning, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(JTxtFieldAnstalldID, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cbRoll, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(JLblTeleNr, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JTxtFieldENamn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(JTxtFieldTeleNr)))))
                    .addComponent(btnGenereraLösenord, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JLblAnstDatum, JLblENamn, JLblEpost, JLblLösen, JLblPostAdress, JLblTeleNr});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLblRubrik)
                    .addComponent(btnTillbakatillmeny))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTxtFieldSökruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLblSokAnställd)
                            .addComponent(btnSök))
                        .addGap(18, 18, 18)
                        .addComponent(JScrollPaneListaAnställda, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(JLblAnstalldUppgifter)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblAnstalldID)
                            .addComponent(JTxtFieldAnstalldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblAvdelning)
                            .addComponent(cbAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblRoll)
                            .addComponent(cbRoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblFNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTxtFieldFNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblENamn)
                            .addComponent(JTxtFieldENamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblTeleNr)
                            .addComponent(JTxtFieldTeleNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblPostAdress)
                            .addComponent(JTxtFieldPostadress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblEpost)
                            .addComponent(JTxtFieldEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblAnstDatum)
                            .addComponent(JTxtFieldAnstDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblLösen)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGenereraLösenord)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBtnUppdateraAnstalld, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JBtnTaBortAnstalld, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JBtnRensaUppgifteranstalld, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(JBtnLaggTillAnstalld, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addAnstalldListener(AnstalldListener anstalldListener) {
        this.anstalldListener = anstalldListener;
    }

    private void hamtaAllaAnstallda() {
        try {
            String sqlFraga
                    = "SELECT aid, fornamn, efternamn, telefon, adress, epost, anstallningsdatum, avdelning, losenord "
                    + "FROM anstalld";

            ArrayList<HashMap<String, String>> lista = idb.fetchRows(sqlFraga);

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("AID");
            model.addColumn("Förnamn");
            model.addColumn("Efternamn");
            model.addColumn("Telefon");
            model.addColumn("Adress");
            model.addColumn("Epost");
            model.addColumn("Anställningsdatum");
            model.addColumn("Avdelning");
            model.addColumn("Lösenord");

            if (lista != null) {
                for (HashMap<String, String> rad : lista) {
                    model.addRow(new Object[]{
                        rad.get("aid"),
                        rad.get("fornamn"),
                        rad.get("efternamn"),
                        rad.get("telefon"),
                        rad.get("adress"),
                        rad.get("epost"),
                        rad.get("anstallningsdatum"),
                        rad.get("avdelning"),
                        rad.get("losenord")
                    });
                }
            }

            jTable1.setModel(model);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Kunde inte hämta anställda.");
        }
    }

    private void fyllFaltFranMarkeradRad(int valdRad) {
        if (valdRad == -1) {
            return;
        }
        JTxtFieldAnstalldID.setText(jTable1.getValueAt(valdRad, 0).toString());
        JTxtFieldFNamn.setText(jTable1.getValueAt(valdRad, 1).toString());
        JTxtFieldENamn.setText(jTable1.getValueAt(valdRad, 2).toString());
        JTxtFieldTeleNr.setText(jTable1.getValueAt(valdRad, 3).toString());
        JTxtFieldPostadress.setText(jTable1.getValueAt(valdRad, 4).toString());
        JTxtFieldEpost.setText(jTable1.getValueAt(valdRad, 5).toString());
        JTxtFieldAnstDatum.setText(jTable1.getValueAt(valdRad, 6).toString());
        String avdelningsId = jTable1.getValueAt(valdRad, 7).toString();

        for (int i = 0; i < cbAvdelning.getItemCount(); i++) {
            String item = cbAvdelning.getItemAt(i);

            if (item.startsWith(avdelningsId + " - ")) {
                cbAvdelning.setSelectedIndex(i);
                break;
            }
        }

        jTextField5.setText(jTable1.getValueAt(valdRad, 8).toString());

        String roll = visaRollForAnstalld();
        cbRoll.setSelectedItem(roll);

        if (anstalldListener != null) {
            String fulltNamn = jTable1.getValueAt(valdRad, 1) + " " + jTable1.getValueAt(valdRad, 2);
            //Anropar valAnstalld på anstalldListener objektet och skickar in  id, namn och roll då en rad valts
            anstalldListener.valAnstalld(jTable1.getValueAt(valdRad, 0).toString(), fulltNamn, roll);
        }
    }

    public void valjRad(String anstalldId) {
        int valdRad = SwingUtils.valjRadIJTableMedId(jTable1, anstalldId, 0);
        fyllFaltFranMarkeradRad(valdRad);
    }

//Returnerar rollen
    private String visaRollForAnstalld() {
        try {
            String aid = JTxtFieldAnstalldID.getText();

            String adminCheck = idb.fetchSingle("SELECT COUNT(*) FROM admin WHERE aid = " + aid);
            String handlaggareCheck = idb.fetchSingle("SELECT COUNT(*) FROM handlaggare WHERE aid = " + aid);
            String projektchefCheck = idb.fetchSingle("SELECT COUNT(*) FROM projekt WHERE projektchef = " + aid);

            boolean arAdmin = !adminCheck.equals("0");
            boolean arHandlaggare = !handlaggareCheck.equals("0");
            boolean arProjektchef = !projektchefCheck.equals("0");

            String roll;

            if (arAdmin) {
                roll = "admin";
            } else if (arHandlaggare && arProjektchef) {
                roll = "handlaggare_projektchef";
            } else if (arHandlaggare) {
                roll = "handlaggare";
            } else {
                roll = "";
            }

            cbRoll.setSelectedItem(roll);
            return roll;

        } catch (Exception ex) {
            cbRoll.setSelectedItem(-1);
            return "";
        }
    }

    private void rensaFalt() {
        JTxtFieldAnstalldID.setText("");
        JTxtFieldFNamn.setText("");
        JTxtFieldENamn.setText("");
        JTxtFieldTeleNr.setText("");
        JTxtFieldPostadress.setText("");
        JTxtFieldEpost.setText("");
        JTxtFieldAnstDatum.setText("");
        cbAvdelning.setSelectedItem("");
        cbRoll.setSelectedIndex(-1);
        jTextField5.setText("");
    }

    private void sokAnstalld() {
        try {
            String sokning = JTxtFieldSökruta.getText();

            String sqlFraga
                    = "SELECT aid, fornamn, efternamn, telefon, adress, epost, anstallningsdatum, avdelning, losenord "
                    + "FROM anstalld "
                    + "WHERE fornamn LIKE '%" + sokning + "%' "
                    + "OR efternamn LIKE '%" + sokning + "%' "
                    + "OR epost LIKE '%" + sokning + "%' "
                    + "OR telefon LIKE '%" + sokning + "%'";

            ArrayList<HashMap<String, String>> lista = idb.fetchRows(sqlFraga);

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("AID");
            model.addColumn("Förnamn");
            model.addColumn("Efternamn");
            model.addColumn("Telefon");
            model.addColumn("Adress");
            model.addColumn("Epost");
            model.addColumn("Anställningsdatum");
            model.addColumn("Avdelning");
            model.addColumn("Lösenord");

            if (lista != null) {
                for (HashMap<String, String> rad : lista) {
                    model.addRow(new Object[]{
                        rad.get("aid"),
                        rad.get("fornamn"),
                        rad.get("efternamn"),
                        rad.get("telefon"),
                        rad.get("adress"),
                        rad.get("epost"),
                        rad.get("anstallningsdatum"),
                        rad.get("avdelning"),
                        rad.get("losenord")
                    });
                }
            }

            jTable1.setModel(model);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Kunde inte söka anställd.");
        }
    }


    private void JTxtFieldEpostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtFieldEpostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtFieldEpostActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void JTxtFieldTeleNrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtFieldTeleNrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtFieldTeleNrActionPerformed

    private void JTxtFieldPostadressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtFieldPostadressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtFieldPostadressActionPerformed

    private void JTxtFieldSökrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtFieldSökrutaActionPerformed
        sokAnstalld();
    }//GEN-LAST:event_JTxtFieldSökrutaActionPerformed

    private void btnSökActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSökActionPerformed
        sokAnstalld();
    }//GEN-LAST:event_btnSökActionPerformed

    private void JBtnRensaUppgifteranstalldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnRensaUppgifteranstalldActionPerformed
        rensaFalt();
    }//GEN-LAST:event_JBtnRensaUppgifteranstalldActionPerformed

    private void JBtnLaggTillAnstalldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnLaggTillAnstalldActionPerformed
        try {
            String aid = idb.getAutoIncrement("anstalld", "aid");

            String avdID = cbAvdelning.getSelectedItem().toString().split(" - ")[0];
            String roll = cbRoll.getSelectedItem().toString();
            String fornamn = JTxtFieldFNamn.getText();
            String efternamn = JTxtFieldENamn.getText();
            String telefon = JTxtFieldTeleNr.getText();
            String adress = JTxtFieldPostadress.getText();
            String epost = JTxtFieldEpost.getText();
            String anstallningsdatum = JTxtFieldAnstDatum.getText();
            String losenord = jTextField5.getText();

            String sqlAnstalld
                    = "INSERT INTO anstalld "
                    + "(aid, fornamn, efternamn, adress, epost, telefon, anstallningsdatum, losenord, avdelning) "
                    + "VALUES ('" + aid + "', '" + fornamn + "', '" + efternamn + "', '"
                    + adress + "', '" + epost + "', '" + telefon + "', '"
                    + anstallningsdatum + "', '" + losenord + "', '" + avdID + "')";

            idb.insert(sqlAnstalld);

            if (roll.equalsIgnoreCase("admin")) {
                idb.insert("INSERT INTO admin (aid, behorighetsniva) VALUES ('" + aid + "', '1')");
            } else if (roll.equalsIgnoreCase("handlaggare")) {
                idb.insert("INSERT INTO handlaggare (aid) VALUES ('" + aid + "')");
            } else if (roll.equalsIgnoreCase("handlaggare_projektchef")) {
                idb.insert("INSERT INTO handlaggare (aid) VALUES ('" + aid + "')");

                String pid = JOptionPane.showInputDialog(this, "Ange projekt-ID där personen ska vara projektchef:");

                if (pid != null && !pid.trim().isEmpty()) {
                    idb.update("UPDATE projekt SET projektchef = '" + aid + "' WHERE pid = '" + pid + "'");
                }
            }

            JTxtFieldAnstalldID.setText(aid);

            javax.swing.JOptionPane.showMessageDialog(this, "Anställd har lagts till!");

            hamtaAllaAnstallda();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Kunde inte lägga till anställd: " + e.getMessage());
        }

    }//GEN-LAST:event_JBtnLaggTillAnstalldActionPerformed

    private void JBtnUppdateraAnstalldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnUppdateraAnstalldActionPerformed
        try {
            String aid = JTxtFieldAnstalldID.getText();
            String avdID = cbAvdelning.getSelectedItem().toString().split(" - ")[0];
            String roll = cbRoll.getSelectedItem().toString();
            String fornamn = JTxtFieldFNamn.getText();
            String efternamn = JTxtFieldENamn.getText();
            String telefon = JTxtFieldTeleNr.getText();
            String adress = JTxtFieldPostadress.getText();
            String epost = JTxtFieldEpost.getText();
            String anstallningsdatum = JTxtFieldAnstDatum.getText();
            String losenord = jTextField5.getText();

            if (aid.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Välj en anställd först.");
                return;
            }

            String sql
                    = "UPDATE anstalld SET "
                    + "fornamn = '" + fornamn + "', "
                    + "efternamn = '" + efternamn + "', "
                    + "telefon = '" + telefon + "', "
                    + "adress = '" + adress + "', "
                    + "epost = '" + epost + "', "
                    + "anstallningsdatum = '" + anstallningsdatum + "', "
                    + "losenord = '" + losenord + "', "
                    + "avdelning = '" + avdID + "' "
                    + "WHERE aid = '" + aid + "'";

            idb.update(sql);

            idb.delete("DELETE FROM admin WHERE aid = '" + aid + "'");
            idb.delete("DELETE FROM handlaggare WHERE aid = '" + aid + "'");

            if (roll.equalsIgnoreCase("admin")) {
                idb.insert("INSERT INTO admin (aid, behorighetsniva) VALUES ('" + aid + "', '1')");
            } else if (roll.equalsIgnoreCase("handlaggare")) {
                idb.insert("INSERT INTO handlaggare (aid) VALUES ('" + aid + "')");
            } else if (roll.equalsIgnoreCase("handlaggare_projektchef")) {
                idb.insert("INSERT INTO handlaggare (aid) VALUES ('" + aid + "')");
            }

            JOptionPane.showMessageDialog(this, "Anställd har uppdaterats.");

            hamtaAllaAnstallda();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Kunde inte uppdatera anställd: " + e.getMessage());
        }
    }//GEN-LAST:event_JBtnUppdateraAnstalldActionPerformed


    private void JBtnTaBortAnstalldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnTaBortAnstalldActionPerformed
        try {
            String aid = JTxtFieldAnstalldID.getText().trim();

            if (aid.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Välj en anställd först.");
                return;
            }

            if (aid.equals(String.valueOf(anvandare.getAid()))) {
                JOptionPane.showMessageDialog(this, "Du kan inte ta bort dig själv.");
                return;
            }

            String arProjektchef = idb.fetchSingle(
                    "SELECT COUNT(*) FROM projekt WHERE projektchef = '" + aid + "'"
            );

            String arProjektmedlem = idb.fetchSingle(
                    "SELECT COUNT(*) FROM ans_proj WHERE aid = '" + aid + "'"
            );

            String arMentor = idb.fetchSingle(
                    "SELECT COUNT(*) FROM handlaggare WHERE mentor = '" + aid + "'"
            );

            String arAvdelningschef = idb.fetchSingle(
                    "SELECT COUNT(*) FROM avdelning WHERE chef = '" + aid + "'"
            );

            if (!arProjektchef.equals("0") || !arProjektmedlem.equals("0") || !arMentor.equals("0") || !arAvdelningschef.equals("0")) {

                JOptionPane.showMessageDialog(this,
                        "Den anställda kan inte tas bort eftersom personen är kopplad till projekt, mentor eller avdelning.");
                return;
            }

            int svar = JOptionPane.showConfirmDialog(
                    this,
                    "Är du säker på att du vill ta bort anställd med ID " + aid + "?",
                    "Bekräfta borttagning",
                    JOptionPane.YES_NO_OPTION
            );

            if (svar != JOptionPane.YES_OPTION) {
                return;
            }

            idb.delete("DELETE FROM admin WHERE aid = '" + aid + "'");
            idb.delete("DELETE FROM handlaggare WHERE aid = '" + aid + "'");
            idb.delete("DELETE FROM anstalld WHERE aid = '" + aid + "'");

            JOptionPane.showMessageDialog(this, "Anställd har tagits bort.");

            rensaFalt();
            hamtaAllaAnstallda();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Kunde inte ta bort anställd: " + e.getMessage());
        }
    }//GEN-LAST:event_JBtnTaBortAnstalldActionPerformed

    private void btnGenereraLösenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenereraLösenordActionPerformed
        String tecken = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890!@#$%^&*()_+?><";
        String genereradLosenord = "";
        for (int i = 0; i < 3; i++) {
            double siffra = Math.random() * 77; // 77 är hur många tecken man har i String tecken
            int heltalSiffra = (int) siffra; // förvandra till int
            genereradLosenord += tecken.charAt(heltalSiffra);// lägga till till String genereradLosenord
        }
        jTextField5.setText("password" + genereradLosenord);// alla lösenord som blir genererade börjar med password som i db
    }//GEN-LAST:event_btnGenereraLösenordActionPerformed

    private void btnTillbakatillmenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakatillmenyActionPerformed
        Navigering.tillbakaTillMeny(anvandare);
        this.dispose();
    }//GEN-LAST:event_btnTillbakatillmenyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    
    ///java.awt.EventQueue.invokeLater(() -> new HanteraAnstalld().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnLaggTillAnstalld;
    private javax.swing.JButton JBtnRensaUppgifteranstalld;
    private javax.swing.JButton JBtnTaBortAnstalld;
    private javax.swing.JButton JBtnUppdateraAnstalld;
    private javax.swing.JLabel JLblAnstDatum;
    private javax.swing.JLabel JLblAnstalldID;
    private javax.swing.JLabel JLblAnstalldUppgifter;
    private javax.swing.JLabel JLblAvdelning;
    private javax.swing.JLabel JLblENamn;
    private javax.swing.JLabel JLblEpost;
    private javax.swing.JLabel JLblFNamn;
    private javax.swing.JLabel JLblLösen;
    private javax.swing.JLabel JLblPostAdress;
    private javax.swing.JLabel JLblRoll;
    private javax.swing.JLabel JLblRubrik;
    private javax.swing.JLabel JLblSokAnställd;
    private javax.swing.JLabel JLblTeleNr;
    private javax.swing.JScrollPane JScrollPaneListaAnställda;
    private javax.swing.JTextField JTxtFieldAnstDatum;
    private javax.swing.JTextField JTxtFieldAnstalldID;
    private javax.swing.JTextField JTxtFieldENamn;
    private javax.swing.JTextField JTxtFieldEpost;
    private javax.swing.JTextField JTxtFieldFNamn;
    private javax.swing.JTextField JTxtFieldPostadress;
    private javax.swing.JTextField JTxtFieldSökruta;
    private javax.swing.JTextField JTxtFieldTeleNr;
    private javax.swing.JButton btnGenereraLösenord;
    private javax.swing.JButton btnSök;
    private javax.swing.JButton btnTillbakatillmeny;
    private javax.swing.JComboBox<String> cbAvdelning;
    private javax.swing.JComboBox<String> cbRoll;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
