/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

/**
 *
 * @author Kristoffer Kolkowski
 */
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class HanteraHållbarhetsmål extends javax.swing.JFrame {
    
    private InfDB idb; // Variabeln heter nu db istället för idb
    private DefaultTableModel bordsModell;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HanteraHållbarhetsmål.class.getName());

    /**
     * Creates new form HanteraHållbarhetsmål
     */
    public HanteraHållbarhetsmål(InfDB idb) {
        this.idb = idb;
        initComponents();
        
        // Kopplar din JTable till en hanterbar modell och sätter kolumnnamn
        bordsModell = (DefaultTableModel) JTableHallberhetsmal.getModel();
        bordsModell.setColumnIdentifiers(new Object[]{"ID", "Namn", "Målnummer", "Beskrivning", "Prioritet"});
        
        // Hämtar data automatiskt vid uppstart
        laddaHållbarhetsmål();
    }

    private void laddaHållbarhetsmål() {
        bordsModell.setRowCount(0); // Tömmer testrader
        
        // SQL-fråga (anpassa kolumnnamnen om de heter något annat i din MySQL-databas)
        String fråga = "SELECT mal_id, namn, malnummer, beskrivning, prioritet FROM hallbarhetsmal";
        
        try {
            ArrayList<HashMap<String, String>> rader = idb.fetchRows(fråga);
            
            if (rader != null) {
                for (HashMap<String, String> rad : rader) {
                    bordsModell.addRow(new Object[]{
                        rad.get("mal_id"),
                        rad.get("namn"),
                        rad.get("malnummer"),
                        rad.get("beskrivning"),
                        rad.get("prioritet")
                    });
                }
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(this, "Kunde inte ladda data: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLblRubrik = new javax.swing.JLabel();
        JPanelHållbarhetsmål = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableHallberhetsmal = new javax.swing.JTable();
        JLblLID = new javax.swing.JLabel();
        JLblNamn = new javax.swing.JLabel();
        JLblMalNr = new javax.swing.JLabel();
        JLblBeskrivning = new javax.swing.JLabel();
        JLblPrioritet = new javax.swing.JLabel();
        JTxtFieldHID = new javax.swing.JTextField();
        JTxtFieldNamn = new javax.swing.JTextField();
        JTxtFieldMalNr = new javax.swing.JTextField();
        JTxtFieldBeskrivning = new javax.swing.JTextField();
        JTxtFieldPrioritet = new javax.swing.JTextField();
        JBtnLaggTillHallbarhetsmal = new javax.swing.JButton();
        JBtnAndraHallbarhetsmal = new javax.swing.JButton();
        JBtnTaBortHallbarhetsmal = new javax.swing.JButton();
        JPanelProjektMotMal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLblRubrik.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JLblRubrik.setText("Hantera Hållbarhetsmål");

        JPanelHållbarhetsmål.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hållbarhetsmål", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        JTableHallberhetsmal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTableHallberhetsmal);

        JLblLID.setText("HållberhetsmålID");

        JLblNamn.setText("Namn");

        JLblMalNr.setText("Målnummer");

        JLblBeskrivning.setText("Beskrivning");

        JLblPrioritet.setText("Prioritet");

        JTxtFieldHID.setText("[HID]");

        JTxtFieldNamn.setText("[Namn]");

        JTxtFieldMalNr.setText("[Malnummer]");

        JTxtFieldBeskrivning.setText("[Beskrivning]");

        JTxtFieldPrioritet.setText("[Prioritet]");

        JBtnLaggTillHallbarhetsmal.setText("Lägg till");
        JBtnLaggTillHallbarhetsmal.addActionListener(this::JBtnLaggTillHallbarhetsmalActionPerformed);

        JBtnAndraHallbarhetsmal.setText("Ändra");

        JBtnTaBortHallbarhetsmal.setText("Ta bort");

        javax.swing.GroupLayout JPanelHållbarhetsmålLayout = new javax.swing.GroupLayout(JPanelHållbarhetsmål);
        JPanelHållbarhetsmål.setLayout(JPanelHållbarhetsmålLayout);
        JPanelHållbarhetsmålLayout.setHorizontalGroup(
            JPanelHållbarhetsmålLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelHållbarhetsmålLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JPanelHållbarhetsmålLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JLblLID, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(JLblNamn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLblMalNr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLblBeskrivning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLblPrioritet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBtnLaggTillHallbarhetsmal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(JPanelHållbarhetsmålLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JTxtFieldHID)
                    .addComponent(JTxtFieldNamn)
                    .addComponent(JTxtFieldMalNr, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(JTxtFieldBeskrivning)
                    .addComponent(JTxtFieldPrioritet)
                    .addComponent(JBtnAndraHallbarhetsmal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(JBtnTaBortHallbarhetsmal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        JPanelHållbarhetsmålLayout.setVerticalGroup(
            JPanelHållbarhetsmålLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelHållbarhetsmålLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPanelHållbarhetsmålLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPanelHållbarhetsmålLayout.createSequentialGroup()
                        .addGroup(JPanelHållbarhetsmålLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblLID)
                            .addComponent(JTxtFieldHID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JPanelHållbarhetsmålLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblNamn)
                            .addComponent(JTxtFieldNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JPanelHållbarhetsmålLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblMalNr)
                            .addComponent(JTxtFieldMalNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JPanelHållbarhetsmålLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblBeskrivning)
                            .addComponent(JTxtFieldBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JPanelHållbarhetsmålLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblPrioritet)
                            .addComponent(JTxtFieldPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JPanelHållbarhetsmålLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JBtnLaggTillHallbarhetsmal, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(JBtnAndraHallbarhetsmal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBtnTaBortHallbarhetsmal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );

        JPanelProjektMotMal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Projekt kopplade till valt hållbarhetsmål", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        javax.swing.GroupLayout JPanelProjektMotMalLayout = new javax.swing.GroupLayout(JPanelProjektMotMal);
        JPanelProjektMotMal.setLayout(JPanelProjektMotMalLayout);
        JPanelProjektMotMalLayout.setHorizontalGroup(
            JPanelProjektMotMalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JPanelProjektMotMalLayout.setVerticalGroup(
            JPanelProjektMotMalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(269, 269, 269)
                                .addComponent(JLblRubrik))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(JPanelHållbarhetsmål, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(JPanelProjektMotMal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLblRubrik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelHållbarhetsmål, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JPanelProjektMotMal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnLaggTillHallbarhetsmalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnLaggTillHallbarhetsmalActionPerformed

    // 1. Hämta texten som användaren skrivit in i textfälten
        String id = JTxtFieldHID.getText().trim();
        String namn = JTxtFieldNamn.getText().trim();
        String malnr = JTxtFieldMalNr.getText().trim();
        String beskrivning = JTxtFieldBeskrivning.getText().trim();
        String prioritet = JTxtFieldPrioritet.getText().trim();

        // 2. Validering – Kontrollera att användaren inte har glömt att fylla i något fält
        if (id.isEmpty() || namn.isEmpty() || malnr.isEmpty() || beskrivning.isEmpty() || prioritet.isEmpty() ||
            id.equals("[HID]") || namn.equals("[Namn]") || malnr.equals("[Malnummer]")) {
            
            JOptionPane.showMessageDialog(this, "Vänligen fyll i alla fält innan du lägger till");
            return; // Avbryt metoden om något saknas
        }
        try {
            // Sqlfråga
            String sqlFråga = "INSERT INTO hallbarhetsmal (mal_id, namn, malnummer, beskrivning, prioritet) " +
                  "VALUES ('" + id + "', '" + namn + "', '" + malnr + "', '" + beskrivning + "', '" + prioritet + "')";

            // 4. Skicka frågan till databasen
            idb.insert(sqlFråga);

            // 5. Meddela användaren att det lyckades
            JOptionPane.showMessageDialog(this, "Hållbarhetsmålet har lagts till framgångsrikt!");

            // 6. Uppdatera tabellen på skärmen direkt så att det nya målet syns
            laddaHållbarhetsmål();

            // 7. Töm textfälten så att de är redo för nästa inmatning
            JTxtFieldHID.setText("");
            JTxtFieldNamn.setText("");
            JTxtFieldMalNr.setText("");
            JTxtFieldBeskrivning.setText("");
            JTxtFieldPrioritet.setText("");

        } catch (InfException e) {
            JOptionPane.showMessageDialog(this, "Kunde inte lägga till målet. Kontrollera att ID inte redan finns.\nFelmeddelande: " + e.getMessage());
        }
    }//GEN-LAST:event_JBtnLaggTillHallbarhetsmalActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnAndraHallbarhetsmal;
    private javax.swing.JButton JBtnLaggTillHallbarhetsmal;
    private javax.swing.JButton JBtnTaBortHallbarhetsmal;
    private javax.swing.JLabel JLblBeskrivning;
    private javax.swing.JLabel JLblLID;
    private javax.swing.JLabel JLblMalNr;
    private javax.swing.JLabel JLblNamn;
    private javax.swing.JLabel JLblPrioritet;
    private javax.swing.JLabel JLblRubrik;
    private javax.swing.JPanel JPanelHållbarhetsmål;
    private javax.swing.JPanel JPanelProjektMotMal;
    private javax.swing.JTable JTableHallberhetsmal;
    private javax.swing.JTextField JTxtFieldBeskrivning;
    private javax.swing.JTextField JTxtFieldHID;
    private javax.swing.JTextField JTxtFieldMalNr;
    private javax.swing.JTextField JTxtFieldNamn;
    private javax.swing.JTextField JTxtFieldPrioritet;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    //Tillfällig main metod för att kunna provköra klassen
    public static void main(String args[]) {
        try {
            // OBS! Ändra sökvägen nedanför till din egen .podb-fils faktiska placering
            InfDB testDb = new InfDB("C:\\db\\NGO_2024.podb"); 
            
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new HanteraHållbarhetsmål(testDb).setVisible(true);
                }
            });
        } catch (InfException e) {
            System.out.println("Kunde inte starta test-databasen: " + e.getMessage());
        }
    }
}
