/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author WDM
 */
public class inloggningsfonster extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(inloggningsfonster.class.getName());
    private InfDB idb;
    /**
     * Creates new form inloggningsfonster
     */
    public inloggningsfonster(InfDB idb) {
        this.idb = idb;
        initComponents();
        lblFelmeddelande.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMain = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblLösenord = new javax.swing.JLabel();
        tfEPost = new javax.swing.JTextField();
        tfLösenord = new javax.swing.JTextField();
        lblFelmeddelande = new javax.swing.JLabel();
        btnLoggain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMain.setText("NGO grupp2");

        lblEpost.setText("E-post");

        lblLösenord.setText("Lösenord");

        lblFelmeddelande.setForeground(new java.awt.Color(255, 0, 0));
        lblFelmeddelande.setText("Felaktig epost eller lösenord");

        btnLoggain.setText("Logga in");
        btnLoggain.addActionListener(this::btnLoggainActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblFelmeddelande)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnLoggain))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(lblLösenord))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblEpost)
                                        .addComponent(lblMain)))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfEPost, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                    .addComponent(tfLösenord, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))))
                        .addGap(92, 92, 92))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblMain)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost)
                    .addComponent(tfEPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLösenord)
                    .addComponent(tfLösenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblFelmeddelande)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnLoggain)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoggainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggainActionPerformed

        String ePost = tfEPost.getText();
        String losen = tfLösenord.getText();

        try{
            String sqlFråga = "SELECT losenord FROM anstalld where epost = '" + ePost+"'";
            //System.out.println(sqlFråga);
            String dblosen = idb.fetchSingle(sqlFråga);
            if (losen.equals(dblosen)){
                String anvandaresNamn = "SELECT fornamn FROM anstalld where epost = '" + ePost+"'";
                String dbNamn = idb.fetchSingle(anvandaresNamn);
                
                String anvandaresEfternamn = "SELECT efternamn FROM anstalld where epost = '" + ePost+"'";
                String dbEfternamn = idb.fetchSingle(anvandaresEfternamn);
                
                String anvandaresAnstallningsdatum = "SELECT anstallningsdatum FROM anstalld where epost = '" + ePost+"'";
                String dbAnstallningsdatum = anvandaresAnstallningsdatum;
                
                String anvandaresID = "SELECT aid FROM anstalld where epost = '" + ePost+"'";
                String dbAnvandaresID = anvandaresID;
                
                String anvandaresAdress = "SELECT adress FROM anstalld where epost = '" + ePost+"'";
                String dbAnvandaresAdress = anvandaresAdress;
                
                String anvandaresTelefon = "SELECT telefon FROM anstalld where epost = '" + ePost+"'";
                String dbAnvandaresTelefon = anvandaresTelefon;
                
                String anvandareslosenord = "SELECT losenord FROM anstalld where epost = '" + ePost+"'";
                String dbAnvandareslosenord = anvandareslosenord;
                
                
                
                new UppgifterHandlaggare().setVisible(true);
                this.setVisible(false);
            }
            else{
                lblFelmeddelande.setVisible(true);
            }
        }
        catch(Exception ex){
        }

    }//GEN-LAST:event_btnLoggainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new inloggningsfonster().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoggain;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFelmeddelande;
    private javax.swing.JLabel lblLösenord;
    private javax.swing.JLabel lblMain;
    private javax.swing.JTextField tfEPost;
    private javax.swing.JTextField tfLösenord;
    // End of variables declaration//GEN-END:variables
}
