/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

import oru.inf.InfException;
import oru.inf.InfDB;

/**
 *
 * @author WDM
 */
public class MenyHandlaggareProjektchef extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenyHandlaggareProjektchef.class.getName());
    
    private Anvandare anvandare;
    private InfDB idb;
        
    
    
    //Första Constructor
    public MenyHandlaggareProjektchef(Anvandare anvandare) {
        initComponents();
        this.anvandare = anvandare;
         this.idb = anvandare.getIdb();
        lblFörnamn.setText(anvandare.getDbNamn());
        lblEfternamn.setText(anvandare.getDbEfternamn());
        
                          
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnMinaUppgifter = new javax.swing.JButton();
        btnMinaProjekt = new javax.swing.JButton();
        btnHållbarhetsmålen = new javax.swing.JButton();
        btnSökPersonal = new javax.swing.JButton();
        btnSökProjekt = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnÄndraProjektUppgifter = new javax.swing.JButton();
        btnHanterHandläggare = new javax.swing.JButton();
        btnManagePartners = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnVisaProjektKostnader = new javax.swing.JButton();
        btnVisaProjektland = new javax.swing.JButton();
        lblFörnamn = new javax.swing.JLabel();
        lblEfternamn = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Projektchef & Handläggare");

        btnMinaUppgifter.setText("Mina uppgifter");
        btnMinaUppgifter.addActionListener(this::btnMinaUppgifterActionPerformed);

        btnMinaProjekt.setText("Mina projekt");
        btnMinaProjekt.addActionListener(this::btnMinaProjektActionPerformed);

        btnHållbarhetsmålen.setText("Hållbarhetsmålen");
        btnHållbarhetsmålen.addActionListener(this::btnHållbarhetsmålenActionPerformed);

        btnSökPersonal.setText("Personal List");
        btnSökPersonal.addActionListener(this::btnSökPersonalActionPerformed);

        btnSökProjekt.setText("Projekt på min avdelning");
        btnSökProjekt.addActionListener(this::btnSökProjektActionPerformed);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Hantera och Uppdatera"));

        btnÄndraProjektUppgifter.setText("Ändra projektuppgifter");
        btnÄndraProjektUppgifter.addActionListener(this::btnÄndraProjektUppgifterActionPerformed);

        btnHanterHandläggare.setText("Hanter handläggare");
        btnHanterHandläggare.addActionListener(this::btnHanterHandläggareActionPerformed);

        btnManagePartners.setText("Hantera partners");
        btnManagePartners.addActionListener(this::btnManagePartnersActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnÄndraProjektUppgifter, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(btnHanterHandläggare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManagePartners, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnÄndraProjektUppgifter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManagePartners)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHanterHandläggare)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Visa information"));

        btnVisaProjektKostnader.setText("Visa projektkostnader");
        btnVisaProjektKostnader.addActionListener(this::btnVisaProjektKostnaderActionPerformed);

        btnVisaProjektland.setText("Visa projektland (LÅG)");
        btnVisaProjektland.addActionListener(this::btnVisaProjektlandActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVisaProjektKostnader, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(btnVisaProjektland, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVisaProjektKostnader)
                .addGap(18, 18, 18)
                .addComponent(btnVisaProjektland)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblFörnamn.setText("förnamn");

        lblEfternamn.setText("efternamn");

        jButton1.setText("partners");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMinaUppgifter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHållbarhetsmålen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSökPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addComponent(btnMinaProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(79, 79, 79)
                .addComponent(lblFörnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addComponent(btnSökProjekt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblFörnamn)
                    .addComponent(lblEfternamn))
                .addGap(26, 26, 26)
                .addComponent(btnMinaUppgifter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMinaProjekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSökProjekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnHållbarhetsmålen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSökPersonal)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(224, 224, 224))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaProjektActionPerformed
        new ProjektHandlaggare(anvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMinaProjektActionPerformed

    private void btnHållbarhetsmålenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHållbarhetsmålenActionPerformed
        new Hallbarhetsmal(anvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHållbarhetsmålenActionPerformed

    private void btnSökPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSökPersonalActionPerformed
        new PersonalLista(anvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSökPersonalActionPerformed

    private void btnSökProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSökProjektActionPerformed

        new ProjektSokHandlaggareAdmin(anvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSökProjektActionPerformed

    private void btnÄndraProjektUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÄndraProjektUppgifterActionPerformed
        new ÄndraProject(anvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnÄndraProjektUppgifterActionPerformed

    private void btnHanterHandläggareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHanterHandläggareActionPerformed
        new HanteraHandläggare(anvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHanterHandläggareActionPerformed

    private void btnVisaProjektKostnaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaProjektKostnaderActionPerformed
        new ProjectCost(anvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVisaProjektKostnaderActionPerformed

    private void btnMinaUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaUppgifterActionPerformed
        new UppgifterHandlaggare(anvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMinaUppgifterActionPerformed

    private void btnVisaProjektlandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaProjektlandActionPerformed
        new ViewProjectCountry(anvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVisaProjektlandActionPerformed

    private void btnManagePartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePartnersActionPerformed
        new ManagePartners(anvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnManagePartnersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new MenyHandlaggareProjektchef().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHanterHandläggare;
    private javax.swing.JButton btnHållbarhetsmålen;
    private javax.swing.JButton btnManagePartners;
    private javax.swing.JButton btnMinaProjekt;
    private javax.swing.JButton btnMinaUppgifter;
    private javax.swing.JButton btnSökPersonal;
    private javax.swing.JButton btnSökProjekt;
    private javax.swing.JButton btnVisaProjektKostnader;
    private javax.swing.JButton btnVisaProjektland;
    private javax.swing.JButton btnÄndraProjektUppgifter;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblEfternamn;
    private javax.swing.JLabel lblFörnamn;
    // End of variables declaration//GEN-END:variables
}
