/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

import oru.inf.InfException;
import oru.inf.InfDB;

/**
 *
 * @author WDM
 */
public class MenyHandlaggareProjektchef extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenyHandlaggareProjektchef.class.getName());
    private Anvandare anvandare;
    private InfDB idb;
    private int aid;

    /**
     * Creates new form MenyHandlaggareProjektchef
     */
    public MenyHandlaggareProjektchef(Anvandare anvandare) {
        initComponents();
        this.idb = anvandare.getIdb();
        this.aid = anvandare.getAid();
        this.anvandare = anvandare;
       try{
        lblFörnamn.setText(idb.fetchSingle("SELECT fornamn FROM anstalld where aid = '"+ aid+"'"));
       }catch(InfException ex){
           
       }
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnMinaUppgifter = new javax.swing.JButton();
        btnMinaProjekt = new javax.swing.JButton();
        btnHållbarhetsmålen = new javax.swing.JButton();
        btnSökPersonal = new javax.swing.JButton();
        btnSökProjekt = new javax.swing.JButton();
        lblFörnamn = new javax.swing.JLabel();
        lblEfternamn = new javax.swing.JLabel();
        btnVisaProjektKostnader = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Projektchef & Handläggare");

        btnMinaUppgifter.setText("Mina uppgifter");
        btnMinaUppgifter.addActionListener(this::btnMinaUppgifterActionPerformed);

        btnMinaProjekt.setText("Mina projekt");
        btnMinaProjekt.addActionListener(this::btnMinaProjektActionPerformed);

        btnHållbarhetsmålen.setText("Hållbarhetsmålen");
        btnHållbarhetsmålen.addActionListener(this::btnHållbarhetsmålenActionPerformed);

        btnSökPersonal.setText("Sök personal");
        btnSökPersonal.addActionListener(this::btnSökPersonalActionPerformed);

        btnSökProjekt.setText("Sök projekt");
        btnSökProjekt.addActionListener(this::btnSökProjektActionPerformed);

        lblFörnamn.setText("förnamn");

        lblEfternamn.setText("efternamn");

        btnVisaProjektKostnader.setText("Visa Projekts Kostnader");
        btnVisaProjektKostnader.addActionListener(this::btnVisaProjektKostnaderActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMinaProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMinaUppgifter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHållbarhetsmålen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSökPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSökProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(79, 79, 79)
                .addComponent(lblFörnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addComponent(btnVisaProjektKostnader, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblFörnamn)
                    .addComponent(lblEfternamn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnMinaUppgifter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMinaProjekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHållbarhetsmålen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSökPersonal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSökProjekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVisaProjektKostnader)
                .addGap(95, 95, 95))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaProjektActionPerformed
        new ProjektSok(anvandare).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMinaProjektActionPerformed

    private void btnHållbarhetsmålenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHållbarhetsmålenActionPerformed
        new Hallbarhetsmal(anvandare).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHållbarhetsmålenActionPerformed

    private void btnSökPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSökPersonalActionPerformed
        new PersonalLista(anvandare).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSökPersonalActionPerformed

    private void btnSökProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSökProjektActionPerformed

        new ProjektSok(anvandare).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSökProjektActionPerformed

    private void btnVisaProjektKostnaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaProjektKostnaderActionPerformed
        new ProjectCost(anvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVisaProjektKostnaderActionPerformed

    private void btnMinaUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaUppgifterActionPerformed
        new UppgifterHandlaggare(anvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMinaUppgifterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new MenyHandlaggareProjektchef().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHållbarhetsmålen;
    private javax.swing.JButton btnMinaProjekt;
    private javax.swing.JButton btnMinaUppgifter;
    private javax.swing.JButton btnSökPersonal;
    private javax.swing.JButton btnSökProjekt;
    private javax.swing.JButton btnVisaProjektKostnader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEfternamn;
    private javax.swing.JLabel lblFörnamn;
    // End of variables declaration//GEN-END:variables
}
