/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

import oru.inf.InfDB;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.BorderLayout;

/**
 *
 * @author alexander.willen
 */
public class PersonalLista extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PersonalLista.class.getName());
    private Anvandare anvandare;
    private InfDB idb;
    private int aid;

    /**
     * Creates new form Personer
     */
    public PersonalLista(Anvandare anvandare) {

        initComponents();
        this.anvandare = anvandare;
        this.idb = anvandare.getIdb();
        this.aid = anvandare.getAid();
        jLabel3.setVisible(false);

        visaAllPersonalIAvdelning();
    }

    private void visaAllPersonalIAvdelning() {
        try {
            jPanel6.removeAll();
            jPanel6.add(jPanel10);

            String sqlFraga
                    = "SELECT CONCAT(fornamn, ' ', efternamn), epost, telefon "
                    + "FROM anstalld "
                    + "WHERE avdelning = (SELECT avdelning FROM anstalld WHERE aid = " + aid + ")";

            ArrayList<java.util.HashMap<String, String>> personalLista = idb.fetchRows(sqlFraga);

            if (personalLista == null || personalLista.isEmpty()) {
                jLabel3.setText("Ingen personal hittades");
                jLabel3.setVisible(true);
                return;
            }

            for (java.util.HashMap<String, String> rad : personalLista) {

                String namn = rad.get("CONCAT(fornamn, ' ', efternamn)");
                String epost = rad.get("epost");
                String telefon = rad.get("telefon");

                JPanel radPanel = new JPanel();
                radPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 0, 4, 0));
                radPanel.setMaximumSize(new java.awt.Dimension(570, 32));
                radPanel.setPreferredSize(new java.awt.Dimension(570, 32));
                radPanel.setLayout(new BorderLayout(10, 0));

                JLabel lblNamn = new JLabel(namn);
                lblNamn.setPreferredSize(new java.awt.Dimension(180, 16));

                JLabel lblEpost = new JLabel(epost);

                JLabel lblTelefon = new JLabel(telefon);
                lblTelefon.setPreferredSize(new java.awt.Dimension(120, 16));

                radPanel.add(lblNamn, BorderLayout.WEST);
                radPanel.add(lblEpost, BorderLayout.CENTER);
                radPanel.add(lblTelefon, BorderLayout.EAST);

                jPanel6.add(radPanel);
            }

            jPanel6.revalidate();
            jPanel6.repaint();

        } catch (Exception ex) {
            jLabel3.setText("Kunde inte hämta personal");
            jLabel3.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTillbakaTillMeny = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSök = new javax.swing.JButton();
        SökningsFält = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTillbakaTillMeny.setText("Tillbaka till Meny");
        btnTillbakaTillMeny.addActionListener(this::btnTillbakaTillMenyActionPerformed);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 0, 4, 0));
        jPanel10.setMaximumSize(new java.awt.Dimension(570, 32));
        jPanel10.setPreferredSize(new java.awt.Dimension(570, 32));
        jPanel10.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel12.setText("Namn");
        jLabel12.setMaximumSize(new java.awt.Dimension(180, 16));
        jLabel12.setPreferredSize(new java.awt.Dimension(180, 16));
        jPanel10.add(jLabel12, java.awt.BorderLayout.WEST);

        jLabel14.setText("Epost");
        jLabel14.setPreferredSize(new java.awt.Dimension(30, 16));
        jPanel10.add(jLabel14, java.awt.BorderLayout.CENTER);

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 3));
        jPanel10.add(jSeparator1, java.awt.BorderLayout.PAGE_END);

        jLabel18.setText("Telefon");
        jLabel18.setMaximumSize(new java.awt.Dimension(50, 16));
        jLabel18.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel10.add(jLabel18, java.awt.BorderLayout.EAST);

        jPanel6.add(jPanel10);

        jPanel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 0, 4, 0));
        jPanel11.setMaximumSize(new java.awt.Dimension(570, 32));
        jPanel11.setPreferredSize(new java.awt.Dimension(570, 32));
        jPanel11.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel13.setText("[namn]");
        jLabel13.setMaximumSize(new java.awt.Dimension(180, 16));
        jLabel13.setPreferredSize(new java.awt.Dimension(180, 16));
        jPanel11.add(jLabel13, java.awt.BorderLayout.WEST);

        jLabel15.setText("[epost]");
        jPanel11.add(jLabel15, java.awt.BorderLayout.CENTER);

        jLabel19.setText("[telefon]");
        jLabel19.setMaximumSize(new java.awt.Dimension(50, 16));
        jLabel19.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel11.add(jLabel19, java.awt.BorderLayout.EAST);

        jPanel6.add(jPanel11);

        jPanel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 0, 4, 0));
        jPanel13.setMaximumSize(new java.awt.Dimension(570, 32));
        jPanel13.setPreferredSize(new java.awt.Dimension(570, 32));
        jPanel13.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel20.setText("[namn]");
        jLabel20.setMaximumSize(new java.awt.Dimension(180, 16));
        jLabel20.setPreferredSize(new java.awt.Dimension(180, 16));
        jPanel13.add(jLabel20, java.awt.BorderLayout.WEST);

        jLabel21.setText("[epost]");
        jPanel13.add(jLabel21, java.awt.BorderLayout.CENTER);

        jLabel22.setText("[telefon]");
        jLabel22.setMaximumSize(new java.awt.Dimension(50, 16));
        jLabel22.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel13.add(jLabel22, java.awt.BorderLayout.EAST);

        jPanel6.add(jPanel13);

        jScrollPane1.setViewportView(jPanel6);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Sök efter personal i din avdelning");

        btnSök.setText("Sök 🔍");
        btnSök.addActionListener(this::btnSökActionPerformed);

        SökningsFält.addActionListener(this::SökningsFältActionPerformed);

        jLabel2.setText("Sök efter namn och epost");

        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("[felmeddelande]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SökningsFält, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSök, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btnTillbakaTillMeny)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTillbakaTillMeny)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SökningsFält, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSök)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSökActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSökActionPerformed
        try {
            String sokning = SökningsFält.getText();
            ValideringInput.ArGiltigSokning resultatSokning
                    = ValideringInput.valideraSokning(sokning);

            if (resultatSokning == ValideringInput.ArGiltigSokning.TOM) {
                JOptionPane.showMessageDialog(
                        this,
                        "Du måste skriva något att söka efter.");
                return;
            }

            if (resultatSokning == ValideringInput.ArGiltigSokning.FOR_LANG) {
                JOptionPane.showMessageDialog(
                        this,
                        "Sökningen är för lång.");
                return;
            }

            if (resultatSokning == ValideringInput.ArGiltigSokning.OGILTIGT_TECKEN) {
                JOptionPane.showMessageDialog(
                        this,
                        "Sökningen innehåller ogiltiga tecken.");
                return;
            }

            String sqlFraga
                    = "SELECT CONCAT(fornamn, ' ', efternamn) AS namn, epost, telefon "
                    + "FROM anstalld "
                    + "WHERE avdelning = (SELECT avdelning FROM anstalld WHERE aid = " + aid + ") "
                    + "AND (fornamn LIKE '%" + sokning + "%' "
                    + "OR efternamn LIKE '%" + sokning + "%' "
                    + "OR epost LIKE '%" + sokning + "%')";

            ArrayList<java.util.HashMap<String, String>> resultat = idb.fetchRows(sqlFraga);

            if (resultat == null || resultat.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Ingen anställd hittades i din avdelning.",
                        "Sökresultat",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE
                );
                return;
            }

            StringBuilder meddelande = new StringBuilder();

            for (java.util.HashMap<String, String> rad : resultat) {
                meddelande.append("Namn: ").append(rad.get("namn")).append("\n");
                meddelande.append("Epost: ").append(rad.get("epost")).append("\n");
                meddelande.append("Telefon: ").append(rad.get("telefon")).append("\n");
                meddelande.append("----------------------\n");
            }

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    meddelande.toString(),
                    "Personal i din avdelning",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Fel vid sökning.",
                    "Fel",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnSökActionPerformed


    private void lblTillbakaTillMenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblTillbakaTillMenyActionPerformed
        //new MenyHandlaggareProjektchef().setVisible(true);
        // this.setVisible(false);
    }//GEN-LAST:event_lblTillbakaTillMenyActionPerformed

    private void SökningsFältActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SökningsFältActionPerformed
        btnSökActionPerformed(evt);
    }//GEN-LAST:event_SökningsFältActionPerformed

    private void btnTillbakaTillMenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaTillMenyActionPerformed
        Navigering.tillbakaTillMeny(anvandare);
        this.dispose();
    }//GEN-LAST:event_btnTillbakaTillMenyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new PersonalLista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SökningsFält;
    private javax.swing.JButton btnSök;
    private javax.swing.JButton btnTillbakaTillMeny;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
