/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.HashSet;
import javaapplication3.ProjektHandlaggare.Instanstyp;
import static javaapplication3.ProjektHandlaggare.Instanstyp.*;
import javax.swing.*;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import oru.inf.InfDB;
import oru.inf.InfException;
import projListeners.LandListener;
import projListeners.AnstalldListener;
import projListeners.MalListener;

/**
 *
 * @author alexander.willen
 */
public class ProjektProjektchef extends javax.swing.JFrame {

    private final JFrame dennaFrame = this;

    //Bakgrundsfärgen som används av vårt valda "tema" i NetBeans
    private static final Color bakgrundsfarg = new Color(212, 217, 223);

    //Session
    private Anvandare anv; //användaren (Session)
    private int pid; //det valda projektet vars uppgifter visas  

    //Redigeringsläge
    private boolean redigerar;

    //Borttagningslägen
    private boolean borttagningslageMal;
    private boolean borttagningslageLand;
    private boolean borttagningslageDeltagare;
    private boolean borttagningslagePartners;

    //behöver bara spara ID! Det är ju genom dessa vi för SQL-uppdateringen/insert. Sen kallar vi bara ladda-info igen
    //Nuvarande datan som visas i projektet
    private HashMap<String, String> projektinfoEnskilda; //Attributer. Identifierare + värde
    private HashSet<String> projektMal; //Nycklar
    private HashSet<String> projektAdmins; //--::--
    private HashSet<String> projektHandlaggare;
    private HashSet<String> projektPartners;

    //Lagrade ändringar som ännu inte blivit sparade till databasen
    private HashMap<String, String> projektinfoAndringar;  //Attributer. Identifierar + värde
    private HashSet<String> projektMalNya; //Nycklar
    private HashSet<String> projektMalBorttagna; //--::--
    private HashSet<String> projektAdminsNya;
    private HashSet<String> projektAdminsBorttagna;
    private HashSet<String> projektHandlaggareNya;
    private HashSet<String> projektHandlaggareBorttagna;
    private HashSet<String> projektPartnersNya;
    private HashSet<String> projektPartnersBorttagna;

    public ProjektProjektchef(Anvandare anv, int pid) {
        //Den som öppnat detta fönster är projektchef för det, vid nuläget innebär det att kontroll behöver

        this.anv = anv;
        this.pid = pid;
        redigerar = false;
        borttagningslageMal = false;
        borttagningslageLand = false;
        borttagningslageDeltagare = false;
        borttagningslagePartners = false;

        //Nuvarande data
        projektinfoEnskilda = new HashMap<>();
        projektMal = new HashSet<>();
        projektAdmins = new HashSet<>();
        projektHandlaggare = new HashSet<>();
        projektPartners = new HashSet<>();

        //Lagrade ändringar
        projektinfoAndringar = new HashMap<>();
        projektMalNya = new HashSet<>();
        projektMalBorttagna = new HashSet<>();
        projektAdminsNya = new HashSet<>();
        projektAdminsBorttagna = new HashSet<>();
        projektHandlaggareNya = new HashSet<>();
        projektHandlaggareBorttagna = new HashSet<>();
        projektPartnersNya = new HashSet<>();
        projektPartnersBorttagna = new HashSet<>();

        //anstalldListener = skapaAnstalldListener();
        //landListener = skapaLandListener();
        initComponents();
        laddaInfo();
        startlageGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnlTop = new javax.swing.JScrollPane();
        pnlTop = new javax.swing.JPanel();
        lblPid = new javax.swing.JLabel();
        lblStartar = new javax.swing.JLabel();
        lblAvslutad = new javax.swing.JLabel();
        pnlVanster = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        btnMalDropdown = new javax.swing.JButton();
        spnlMalDropdown = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        pnlMal = new javax.swing.JPanel();
        pnlTaBortMal = new javax.swing.JPanel();
        btnTaBortMal = new javax.swing.JButton();
        lblFelmeddelandeMal = new javax.swing.JLabel();
        btnAddMal = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        btnBeskrivningDropdown = new javax.swing.JButton();
        spnlBeskrivningDropdown = new javax.swing.JScrollPane();
        pnlBeskrivning = new javax.swing.JPanel();
        txarBeskrivning = new javax.swing.JTextArea();
        pnlLand = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnLand = new javax.swing.JButton();
        btnBytLand = new javax.swing.JButton();
        pnlTaBortLand = new javax.swing.JPanel();
        btnTaBortLand = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtfStatus = new javax.swing.JTextField();
        cbStatus = new javax.swing.JComboBox<>();
        jPanel14 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtfPrioritet = new javax.swing.JTextField();
        cbPrioritet = new javax.swing.JComboBox<>();
        pnlFelmeddelandeKostnad = new javax.swing.JPanel();
        lblFelmeddelandeKostnad = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtfKostnad = new javax.swing.JTextField();
        pnlHoger = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btnDeltagareDropdown = new javax.swing.JButton();
        spnlDeltagareDropdown = new javax.swing.JScrollPane();
        pnlDeltagare = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        pnlAdmin = new javax.swing.JPanel();
        btnAddAdmin = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        pnlHandlaggare = new javax.swing.JPanel();
        btnAddHandlaggare = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        pnlProjektchef = new javax.swing.JPanel();
        btnProjektchef = new javax.swing.JButton();
        btnBytProjektchef = new javax.swing.JButton();
        btnTaBortDeltagare = new javax.swing.JButton();
        lblFelmeddelandeProjektchef = new javax.swing.JLabel();
        lblFelmeddelandeHandlaggare = new javax.swing.JLabel();
        lblFelmeddelandeAdmin = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        btnPartnersDropdown = new javax.swing.JButton();
        spnlPartnersDropdown = new javax.swing.JScrollPane();
        pnlPartners = new javax.swing.JPanel();
        pnlTaBortPartners = new javax.swing.JPanel();
        btnTaBortPartners = new javax.swing.JButton();
        lblFelmeddelandePartners = new javax.swing.JLabel();
        btnAddPartner = new javax.swing.JButton();
        pnlStartDatum = new javax.swing.JPanel();
        txtfStartDatum = new javax.swing.JTextField();
        dateStartDatum = new com.toedter.calendar.JDateChooser();
        pnlSlutDatum = new javax.swing.JPanel();
        txtfSlutDatum = new javax.swing.JTextField();
        dateSlutDatum = new com.toedter.calendar.JDateChooser();
        pnlProjektnamn = new javax.swing.JPanel();
        txtfProjektnamn = new javax.swing.JTextField();
        btnAndra = new javax.swing.JButton();
        btnSpara = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        spnlTop.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        spnlTop.setPreferredSize(new java.awt.Dimension(730, 577));

        pnlTop.setMaximumSize(new java.awt.Dimension(700, 2000));

        lblPid.setText("Projektid: [pid]");
        lblPid.setMaximumSize(new java.awt.Dimension(150, 16));

        lblStartar.setText("Startad");

        lblAvslutad.setText("Avslutad");

        pnlVanster.setMaximumSize(new java.awt.Dimension(385, 30000));
        pnlVanster.setMinimumSize(new java.awt.Dimension(200, 260));
        pnlVanster.setLayout(new javax.swing.BoxLayout(pnlVanster, javax.swing.BoxLayout.Y_AXIS));

        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel9.setMaximumSize(new java.awt.Dimension(500, 35));
        jPanel9.setPreferredSize(new java.awt.Dimension(250, 35));

        btnMalDropdown.setText("▶ Hållbarhetsmål");
        btnMalDropdown.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMalDropdown.setMaximumSize(new java.awt.Dimension(160, 160));
        btnMalDropdown.setMinimumSize(new java.awt.Dimension(86, 23));
        btnMalDropdown.setPreferredSize(new java.awt.Dimension(86, 23));
        btnMalDropdown.addActionListener(this::btnMalDropdownActionPerformed);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(btnMalDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 187, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMalDropdown, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        pnlVanster.add(jPanel9);

        spnlMalDropdown.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        spnlMalDropdown.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        spnlMalDropdown.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        spnlMalDropdown.setMaximumSize(new java.awt.Dimension(400, 400));
        spnlMalDropdown.setMinimumSize(new java.awt.Dimension(310, 100));
        spnlMalDropdown.setPreferredSize(new java.awt.Dimension(310, 160));

        jPanel1.setPreferredSize(new java.awt.Dimension(200, 800));
        jPanel1.setLayout(new java.awt.BorderLayout());

        pnlMal.setMaximumSize(new java.awt.Dimension(500, 400));
        pnlMal.setMinimumSize(new java.awt.Dimension(200, 90));
        pnlMal.setOpaque(false);
        pnlMal.setPreferredSize(new java.awt.Dimension(300, 800));
        pnlMal.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        pnlTaBortMal.setMaximumSize(new java.awt.Dimension(500, 30));
        pnlTaBortMal.setMinimumSize(new java.awt.Dimension(290, 35));
        pnlTaBortMal.setPreferredSize(new java.awt.Dimension(330, 35));

        btnTaBortMal.setText("[ Ta bort ]");
        btnTaBortMal.setMinimumSize(new java.awt.Dimension(81, 22));
        btnTaBortMal.setPreferredSize(new java.awt.Dimension(81, 22));
        btnTaBortMal.addActionListener(this::btnTaBortMalActionPerformed);

        lblFelmeddelandeMal.setForeground(new java.awt.Color(255, 51, 0));
        lblFelmeddelandeMal.setText("[felmeddelande]");

        javax.swing.GroupLayout pnlTaBortMalLayout = new javax.swing.GroupLayout(pnlTaBortMal);
        pnlTaBortMal.setLayout(pnlTaBortMalLayout);
        pnlTaBortMalLayout.setHorizontalGroup(
            pnlTaBortMalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTaBortMalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFelmeddelandeMal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(btnTaBortMal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        pnlTaBortMalLayout.setVerticalGroup(
            pnlTaBortMalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaBortMalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTaBortMalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaBortMal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelmeddelandeMal))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pnlMal.add(pnlTaBortMal);

        btnAddMal.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        btnAddMal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikoner/plusikon.png"))); // NOI18N
        btnAddMal.setIconTextGap(0);
        btnAddMal.setMargin(new java.awt.Insets(2, 13, 3, 14));
        btnAddMal.setName("btnAddMal"); // NOI18N
        btnAddMal.setPreferredSize(new java.awt.Dimension(19, 19));
        btnAddMal.addActionListener(this::btnAddMalActionPerformed);
        pnlMal.add(btnAddMal);

        jPanel1.add(pnlMal, java.awt.BorderLayout.NORTH);

        spnlMalDropdown.setViewportView(jPanel1);

        pnlVanster.add(spnlMalDropdown);

        jPanel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel13.setMaximumSize(new java.awt.Dimension(500, 38));
        jPanel13.setMinimumSize(new java.awt.Dimension(139, 38));
        jPanel13.setName(""); // NOI18N
        jPanel13.setPreferredSize(new java.awt.Dimension(250, 38));

        btnBeskrivningDropdown.setText("▶ Beskrivning");
        btnBeskrivningDropdown.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBeskrivningDropdown.setMargin(new java.awt.Insets(0, 0, 0, 14));
        btnBeskrivningDropdown.setMaximumSize(new java.awt.Dimension(160, 160));
        btnBeskrivningDropdown.setMinimumSize(new java.awt.Dimension(123, 30));
        btnBeskrivningDropdown.setPreferredSize(new java.awt.Dimension(125, 30));
        btnBeskrivningDropdown.setVerifyInputWhenFocusTarget(false);
        btnBeskrivningDropdown.addActionListener(this::btnBeskrivningDropdownActionPerformed);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(btnBeskrivningDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 199, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(btnBeskrivningDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlVanster.add(jPanel13);

        spnlBeskrivningDropdown.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        spnlBeskrivningDropdown.setToolTipText("");
        spnlBeskrivningDropdown.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        spnlBeskrivningDropdown.setMaximumSize(new java.awt.Dimension(32767, 60));
        spnlBeskrivningDropdown.setMinimumSize(new java.awt.Dimension(225, 60));
        spnlBeskrivningDropdown.setPreferredSize(new java.awt.Dimension(230, 60));

        pnlBeskrivning.setMinimumSize(new java.awt.Dimension(220, 100));
        pnlBeskrivning.setName(""); // NOI18N
        pnlBeskrivning.setLayout(new java.awt.BorderLayout());

        txarBeskrivning.setColumns(5);
        txarBeskrivning.setLineWrap(true);
        txarBeskrivning.setRows(5);
        txarBeskrivning.setWrapStyleWord(true);
        txarBeskrivning.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txarBeskrivning.setMaximumSize(new java.awt.Dimension(200, 84));
        txarBeskrivning.setMinimumSize(new java.awt.Dimension(200, 20));
        pnlBeskrivning.add(txarBeskrivning, java.awt.BorderLayout.PAGE_START);

        spnlBeskrivningDropdown.setViewportView(pnlBeskrivning);

        pnlVanster.add(spnlBeskrivningDropdown);

        pnlLand.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 0, 4, 0));
        pnlLand.setMaximumSize(new java.awt.Dimension(500, 32));
        pnlLand.setPreferredSize(new java.awt.Dimension(250, 36));
        pnlLand.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jLabel12.setText("Land");
        jLabel12.setMaximumSize(new java.awt.Dimension(71, 16));
        jLabel12.setMinimumSize(new java.awt.Dimension(71, 16));
        jLabel12.setPreferredSize(new java.awt.Dimension(71, 16));
        pnlLand.add(jLabel12);

        btnLand.setText("[Land]");
        btnLand.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLand.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnLand.setMaximumSize(new java.awt.Dimension(180, 30));
        btnLand.setMinimumSize(new java.awt.Dimension(43, 30));
        btnLand.setPreferredSize(new java.awt.Dimension(50, 30));
        btnLand.addActionListener(this::btnLandActionPerformed);
        pnlLand.add(btnLand);

        btnBytLand.setText("Byt");
        btnBytLand.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnBytLand.setMaximumSize(new java.awt.Dimension(45, 22));
        btnBytLand.setPreferredSize(new java.awt.Dimension(45, 22));
        btnBytLand.addActionListener(this::btnBytLandActionPerformed);
        pnlLand.add(btnBytLand);

        pnlTaBortLand.setPreferredSize(new java.awt.Dimension(130, 22));
        pnlTaBortLand.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        btnTaBortLand.setText("[ Ta bort ]");
        btnTaBortLand.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnTaBortLand.setMaximumSize(new java.awt.Dimension(150, 22));
        btnTaBortLand.setMinimumSize(new java.awt.Dimension(60, 18));
        btnTaBortLand.setPreferredSize(new java.awt.Dimension(80, 22));
        btnTaBortLand.addActionListener(this::btnTaBortLandActionPerformed);
        pnlTaBortLand.add(btnTaBortLand);

        pnlLand.add(pnlTaBortLand);

        pnlVanster.add(pnlLand);

        jPanel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 0, 4, 0));
        jPanel12.setMaximumSize(new java.awt.Dimension(500, 32));
        jPanel12.setPreferredSize(new java.awt.Dimension(200, 36));

        jLabel13.setText("Status");

        txtfStatus.setEditable(false);
        txtfStatus.setBackground(new java.awt.Color(212, 217, 223));
        txtfStatus.setText("[Status]");
        txtfStatus.setFocusable(false);
        txtfStatus.setMaximumSize(new java.awt.Dimension(160, 30));
        txtfStatus.setMinimumSize(new java.awt.Dimension(45, 30));
        txtfStatus.setPreferredSize(new java.awt.Dimension(60, 30));

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Planerat", "Pågående", "Avslutat", "Ingen" }));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel13)
                .addGap(40, 40, 40)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtfStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlVanster.add(jPanel12);

        jPanel14.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 0, 4, 0));
        jPanel14.setMaximumSize(new java.awt.Dimension(500, 32));
        jPanel14.setPreferredSize(new java.awt.Dimension(200, 36));

        jLabel15.setText("Prioritet");

        txtfPrioritet.setEditable(false);
        txtfPrioritet.setBackground(new java.awt.Color(212, 217, 223));
        txtfPrioritet.setText("[Prioritet]");
        txtfPrioritet.setFocusable(false);
        txtfPrioritet.setMaximumSize(new java.awt.Dimension(185, 30));
        txtfPrioritet.setMinimumSize(new java.awt.Dimension(45, 30));
        txtfPrioritet.setPreferredSize(new java.awt.Dimension(70, 30));

        cbPrioritet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Låg", "Medel", "Hög", "Ingen" }));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(28, 28, 28)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtfPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cbPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(txtfPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlVanster.add(jPanel14);

        pnlFelmeddelandeKostnad.setPreferredSize(new java.awt.Dimension(324, 24));

        lblFelmeddelandeKostnad.setForeground(new java.awt.Color(255, 51, 0));
        lblFelmeddelandeKostnad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFelmeddelandeKostnad.setText("[felmeddelande]");

        javax.swing.GroupLayout pnlFelmeddelandeKostnadLayout = new javax.swing.GroupLayout(pnlFelmeddelandeKostnad);
        pnlFelmeddelandeKostnad.setLayout(pnlFelmeddelandeKostnadLayout);
        pnlFelmeddelandeKostnadLayout.setHorizontalGroup(
            pnlFelmeddelandeKostnadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFelmeddelandeKostnadLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblFelmeddelandeKostnad)
                .addContainerGap(237, Short.MAX_VALUE))
        );
        pnlFelmeddelandeKostnadLayout.setVerticalGroup(
            pnlFelmeddelandeKostnadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFelmeddelandeKostnadLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(lblFelmeddelandeKostnad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlVanster.add(pnlFelmeddelandeKostnad);

        jPanel15.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 0, 4, 0));
        jPanel15.setMaximumSize(new java.awt.Dimension(500, 32));
        jPanel15.setPreferredSize(new java.awt.Dimension(200, 36));

        jLabel17.setText("Kostnad");

        txtfKostnad.setEditable(false);
        txtfKostnad.setBackground(new java.awt.Color(212, 217, 223));
        txtfKostnad.setText("[Kostnad]");
        txtfKostnad.setFocusable(false);
        txtfKostnad.setMaximumSize(new java.awt.Dimension(200, 30));
        txtfKostnad.setMinimumSize(new java.awt.Dimension(64, 30));
        txtfKostnad.setPreferredSize(new java.awt.Dimension(70, 30));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addGap(26, 26, 26)
                .addComponent(txtfKostnad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtfKostnad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlVanster.add(jPanel15);

        pnlHoger.setLayout(new javax.swing.BoxLayout(pnlHoger, javax.swing.BoxLayout.Y_AXIS));

        jPanel8.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel8.setPreferredSize(new java.awt.Dimension(456, 35));

        btnDeltagareDropdown.setText("▶ Deltagare");
        btnDeltagareDropdown.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDeltagareDropdown.setMaximumSize(new java.awt.Dimension(200, 160));
        btnDeltagareDropdown.setMinimumSize(new java.awt.Dimension(93, 30));
        btnDeltagareDropdown.setPreferredSize(new java.awt.Dimension(93, 35));
        btnDeltagareDropdown.addActionListener(this::btnDeltagareDropdownActionPerformed);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(btnDeltagareDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 270, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDeltagareDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlHoger.add(jPanel8);

        spnlDeltagareDropdown.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        spnlDeltagareDropdown.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        spnlDeltagareDropdown.setMaximumSize(new java.awt.Dimension(32767, 300));
        spnlDeltagareDropdown.setPreferredSize(new java.awt.Dimension(395, 300));

        pnlDeltagare.setMaximumSize(new java.awt.Dimension(350, 30000));
        pnlDeltagare.setMinimumSize(new java.awt.Dimension(350, 200));
        pnlDeltagare.setPreferredSize(new java.awt.Dimension(350, 200));

        jLabel7.setText("Projektchef");

        jLabel8.setText("Administratörer");

        pnlAdmin.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        btnAddAdmin.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        btnAddAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikoner/plusikon.png"))); // NOI18N
        btnAddAdmin.setIconTextGap(0);
        btnAddAdmin.setMargin(new java.awt.Insets(2, 13, 3, 14));
        btnAddAdmin.setPreferredSize(new java.awt.Dimension(19, 19));
        btnAddAdmin.addActionListener(this::btnAddAdminActionPerformed);
        pnlAdmin.add(btnAddAdmin);

        pnlHandlaggare.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        btnAddHandlaggare.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        btnAddHandlaggare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikoner/plusikon.png"))); // NOI18N
        btnAddHandlaggare.setIconTextGap(0);
        btnAddHandlaggare.setMargin(new java.awt.Insets(2, 13, 3, 14));
        btnAddHandlaggare.setPreferredSize(new java.awt.Dimension(19, 19));
        btnAddHandlaggare.addActionListener(this::btnAddHandlaggareActionPerformed);
        pnlHandlaggare.add(btnAddHandlaggare);

        jLabel9.setText("Handläggare");

        pnlProjektchef.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        btnProjektchef.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 16, 6, 16));
        btnProjektchef.setMaximumSize(new java.awt.Dimension(180, 23));
        btnProjektchef.setMinimumSize(new java.awt.Dimension(40, 23));
        btnProjektchef.addActionListener(this::btnProjektchefActionPerformed);
        pnlProjektchef.add(btnProjektchef);

        btnBytProjektchef.setText("Byt");
        btnBytProjektchef.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnBytProjektchef.setMaximumSize(new java.awt.Dimension(45, 22));
        btnBytProjektchef.setPreferredSize(new java.awt.Dimension(45, 22));
        btnBytProjektchef.addActionListener(this::btnBytProjektchefActionPerformed);
        pnlProjektchef.add(btnBytProjektchef);

        btnTaBortDeltagare.setText("[ Ta bort ]");
        btnTaBortDeltagare.addActionListener(this::btnTaBortDeltagareActionPerformed);

        lblFelmeddelandeProjektchef.setForeground(new java.awt.Color(255, 51, 0));
        lblFelmeddelandeProjektchef.setText("[felmeddelande]");

        lblFelmeddelandeHandlaggare.setForeground(new java.awt.Color(255, 51, 0));
        lblFelmeddelandeHandlaggare.setText("[felmeddelande]");

        lblFelmeddelandeAdmin.setForeground(new java.awt.Color(255, 51, 0));
        lblFelmeddelandeAdmin.setText("[felmeddelande]");

        javax.swing.GroupLayout pnlDeltagareLayout = new javax.swing.GroupLayout(pnlDeltagare);
        pnlDeltagare.setLayout(pnlDeltagareLayout);
        pnlDeltagareLayout.setHorizontalGroup(
            pnlDeltagareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeltagareLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDeltagareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDeltagareLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lblFelmeddelandeProjektchef)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTaBortDeltagare))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDeltagareLayout.createSequentialGroup()
                        .addGroup(pnlDeltagareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDeltagareLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblFelmeddelandeHandlaggare))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDeltagareLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFelmeddelandeAdmin)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlDeltagareLayout.createSequentialGroup()
                .addGroup(pnlDeltagareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlHandlaggare, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlProjektchef, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        pnlDeltagareLayout.setVerticalGroup(
            pnlDeltagareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeltagareLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDeltagareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(btnTaBortDeltagare)
                    .addComponent(lblFelmeddelandeProjektchef))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlProjektchef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDeltagareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblFelmeddelandeAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDeltagareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblFelmeddelandeHandlaggare))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlHandlaggare, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        spnlDeltagareDropdown.setViewportView(pnlDeltagare);

        pnlHoger.add(spnlDeltagareDropdown);

        jPanel11.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel11.setPreferredSize(new java.awt.Dimension(456, 40));

        btnPartnersDropdown.setText("▶ Partners");
        btnPartnersDropdown.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPartnersDropdown.setMaximumSize(new java.awt.Dimension(160, 160));
        btnPartnersDropdown.setVerifyInputWhenFocusTarget(false);
        btnPartnersDropdown.addActionListener(this::btnPartnersDropdownActionPerformed);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(btnPartnersDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 290, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(btnPartnersDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlHoger.add(jPanel11);

        spnlPartnersDropdown.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        spnlPartnersDropdown.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        spnlPartnersDropdown.setMinimumSize(new java.awt.Dimension(16, 100));
        spnlPartnersDropdown.setPreferredSize(new java.awt.Dimension(375, 100));

        pnlPartners.setMaximumSize(null);
        pnlPartners.setMinimumSize(new java.awt.Dimension(350, 60));
        pnlPartners.setPreferredSize(new java.awt.Dimension(350, 60));
        pnlPartners.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        pnlTaBortPartners.setMaximumSize(new java.awt.Dimension(360, 24));
        pnlTaBortPartners.setMinimumSize(new java.awt.Dimension(360, 0));
        pnlTaBortPartners.setPreferredSize(new java.awt.Dimension(360, 24));

        btnTaBortPartners.setText("[ Ta bort ]");
        btnTaBortPartners.addActionListener(this::btnTaBortPartnersActionPerformed);

        lblFelmeddelandePartners.setForeground(new java.awt.Color(255, 51, 0));
        lblFelmeddelandePartners.setText("[felmeddelande]");

        javax.swing.GroupLayout pnlTaBortPartnersLayout = new javax.swing.GroupLayout(pnlTaBortPartners);
        pnlTaBortPartners.setLayout(pnlTaBortPartnersLayout);
        pnlTaBortPartnersLayout.setHorizontalGroup(
            pnlTaBortPartnersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTaBortPartnersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFelmeddelandePartners)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addComponent(btnTaBortPartners)
                .addContainerGap())
        );
        pnlTaBortPartnersLayout.setVerticalGroup(
            pnlTaBortPartnersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTaBortPartnersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnTaBortPartners)
                .addComponent(lblFelmeddelandePartners))
        );

        pnlPartners.add(pnlTaBortPartners);

        btnAddPartner.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        btnAddPartner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikoner/plusikon.png"))); // NOI18N
        btnAddPartner.setIconTextGap(0);
        btnAddPartner.setMargin(new java.awt.Insets(2, 13, 3, 14));
        btnAddPartner.setPreferredSize(new java.awt.Dimension(19, 19));
        btnAddPartner.addActionListener(this::btnAddPartnerActionPerformed);
        pnlPartners.add(btnAddPartner);

        spnlPartnersDropdown.setViewportView(pnlPartners);

        pnlHoger.add(spnlPartnersDropdown);

        pnlStartDatum.setMinimumSize(new java.awt.Dimension(20, 30));
        pnlStartDatum.setPreferredSize(new java.awt.Dimension(20, 30));
        pnlStartDatum.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtfStartDatum.setEditable(false);
        txtfStartDatum.setBackground(new java.awt.Color(212, 217, 223));
        txtfStartDatum.setText("ÅÅÅÅ-MM-DD");
        txtfStartDatum.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 3, 0, 0));
        txtfStartDatum.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtfStartDatum.setPreferredSize(new java.awt.Dimension(86, 16));
        txtfStartDatum.addActionListener(this::txtfStartDatumActionPerformed);
        pnlStartDatum.add(txtfStartDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        dateStartDatum.setDateFormatString("y MMM d");
        pnlStartDatum.add(dateStartDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        pnlSlutDatum.setMinimumSize(new java.awt.Dimension(20, 30));
        pnlSlutDatum.setPreferredSize(new java.awt.Dimension(20, 30));
        pnlSlutDatum.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtfSlutDatum.setEditable(false);
        txtfSlutDatum.setBackground(new java.awt.Color(212, 217, 223));
        txtfSlutDatum.setText("ÅÅÅÅ-MM-DD");
        txtfSlutDatum.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 3, 0, 0));
        txtfSlutDatum.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtfSlutDatum.setPreferredSize(new java.awt.Dimension(86, 16));
        txtfSlutDatum.addActionListener(this::txtfSlutDatumActionPerformed);
        pnlSlutDatum.add(txtfSlutDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        dateSlutDatum.setDateFormatString("y MMM d");
        pnlSlutDatum.add(dateSlutDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        txtfProjektnamn.setEditable(false);
        txtfProjektnamn.setBackground(new java.awt.Color(212, 217, 223));
        txtfProjektnamn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtfProjektnamn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfProjektnamn.setText("[Projektnamn]");
        txtfProjektnamn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtfProjektnamn.setFocusable(false);
        txtfProjektnamn.setMaximumSize(new java.awt.Dimension(500, 25));
        txtfProjektnamn.setMinimumSize(new java.awt.Dimension(80, 25));
        txtfProjektnamn.setOpaque(true);
        txtfProjektnamn.setPreferredSize(new java.awt.Dimension(150, 25));
        txtfProjektnamn.addActionListener(this::txtfProjektnamnActionPerformed);
        pnlProjektnamn.add(txtfProjektnamn);

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addComponent(pnlVanster, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlHoger, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblPid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addComponent(lblAvslutad)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                        .addComponent(lblStartar)
                        .addGap(20, 20, 20)))
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlSlutDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlStartDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(280, 280, 280))
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(pnlProjektnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlProjektnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(pnlStartDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlSlutDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblStartar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAvslutad)
                        .addGap(23, 23, 23)))
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlVanster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlHoger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(254, Short.MAX_VALUE))
        );

        spnlTop.setViewportView(pnlTop);

        btnAndra.setText("Ändra");
        btnAndra.addActionListener(this::btnAndraActionPerformed);

        btnSpara.setText("Spara");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAndra, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnSpara, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(spnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAndra)
                    .addComponent(btnSpara))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startlageGUI() {
        //Gömmer pop-up paneler
        spnlMalDropdown.setVisible(false);
        spnlBeskrivningDropdown.setVisible(false);
        spnlDeltagareDropdown.setVisible(false);
        spnlPartnersDropdown.setVisible(false);

        //----NYTT FÖR PROJEKTCHEF------------------       
        //---Redigerings-läget---
        //...Datum rutor
        dateStartDatum.setVisible(false);
        dateSlutDatum.setVisible(false);
        //...Adderingsknappar
        btnAddMal.setVisible(false);
        btnAddAdmin.setVisible(false);
        btnAddHandlaggare.setVisible(false);
        btnAddPartner.setVisible(false);
        //...Felmeddelande
        lblFelmeddelandeMal.setVisible(false);
        pnlFelmeddelandeKostnad.setVisible(false);
        lblFelmeddelandeProjektchef.setVisible(false);
        lblFelmeddelandeAdmin.setVisible(false);
        lblFelmeddelandeHandlaggare.setVisible(false);
        lblFelmeddelandePartners.setVisible(false);
        //...Comboboxes
        cbStatus.setVisible(false);
        cbPrioritet.setVisible(false);
        //Edit-UI
        uppdateraEditUI();

        revalidate();
        repaint();
        //------------------------------------------
    }

    private void laddaInfo() {
        //databas
        InfDB idb = anv.getIdb();

        try {
            //---Hämtar projektinfo--- (Att ha datahämtning här är dålig cohesion och coupling. Förbättra vid refaktorisering, är låg-prio)
            HashMap<String, String> projektinfoEnskilda = idb.fetchRow(
                    "SELECT projektnamn, startdatum, slutdatum, Projekt.beskrivning, "
                    + "status, prioritet, kostnad, Land.namn as landnamn, lid as landId, "
                    + "CONCAT(fornamn, ' ', efternamn) as chefnamn, projektchef as projektchefId "
                    + "FROM Projekt "
                    + "JOIN Land ON land = lid "
                    + "JOIN Anstalld ON projektchef = aid "
                    + "WHERE pid = " + pid);

            ArrayList<HashMap<String, String>> projektinfoMal = idb.fetchRows(
                    "SELECT malnummer, namn, h.hid as id "
                    + "FROM Hallbarhetsmal h "
                    + "JOIN Proj_Hallbarhet ph on h.hid = ph.hid "
                    + "WHERE ph.pid = " + pid);

            ArrayList<HashMap<String, String>> projektinfoAdmins = idb.fetchRows(
                    "SELECT CONCAT(fornamn, ' ', efternamn) as namn, a.aid as id "
                    + "FROM Anstalld a "
                    + "JOIN Admin ad on a.aid = ad.aid "
                    + "JOIN Ans_Proj ap on a.aid = ap.aid "
                    + "WHERE ap.pid = " + pid);

            ArrayList<HashMap<String, String>> projektinfoHandlaggare = idb.fetchRows(
                    "SELECT CONCAT(fornamn, ' ', efternamn) as namn, a.aid as id "
                    + "FROM Anstalld a "
                    + "JOIN Handlaggare h on a.aid = h.aid "
                    + "JOIN Ans_Proj ap on a.aid = ap.aid "
                    + "WHERE ap.pid = " + pid);

            ArrayList<HashMap<String, String>> projektinfoPartners = idb.fetchRows(
                    "SELECT namn, p.pid as id "
                    + "FROM Partner p "
                    + "JOIN Projekt_Partner pp on p.pid = pp.partner_pid "
                    + "WHERE pp.pid = " + pid);

            //-----NYTT FÖR PROJEKTCHEF-----
            String projektnamn = projektinfoEnskilda.get("projektnamn");
            String beskrivning = projektinfoEnskilda.get("beskrivning");
            String kostnad = projektinfoEnskilda.get("kostnad");
            String chefnamn = projektinfoEnskilda.get("chefnamn");
            String landnamn = projektinfoEnskilda.get("namn"); //alias (as landnamn) fungerade ej
            String startdatum = projektinfoEnskilda.get("startdatum");
            String slutdatum = projektinfoEnskilda.get("slutdatum");
            String status = projektinfoEnskilda.get("status");
            String prioritet = projektinfoEnskilda.get("prioritet");

            //---Lagrar hämtad projektInfo i fält---
            this.projektinfoEnskilda.putAll(projektinfoEnskilda);
            for (HashMap<String, String> mal : projektinfoMal) {
                this.projektMal.add(mal.get("id"));
            }
            for (HashMap<String, String> admin : projektinfoAdmins) {
                this.projektAdmins.add(admin.get("id"));
            }
            for (HashMap<String, String> handlaggare : projektinfoHandlaggare) {
                this.projektHandlaggare.add(handlaggare.get("id"));
            }
            for (HashMap<String, String> partner : projektinfoPartners) {
                this.projektPartners.add(partner.get("id"));
            }

            //---Visar hämtad projektInfo---
            //...ändrar text
            lblPid.setText("Projektid: " + pid);
            txtfProjektnamn.setText(projektnamn);
            txarBeskrivning.setText(beskrivning);
            txtfKostnad.setText(kostnad);
            btnProjektchef.setText(chefnamn);
            btnLand.setText(landnamn);
            //...Datum
            uppdateraStartdatumUI(startdatum);
            uppdateraSlutdatumUI(slutdatum);
            //...Status och prioritet
            uppdateraStatusUI(status);
            uppdateraPrioritetUI(prioritet);
            //...Edit-UI
            uppdateraEditUILand();
            uppdateraEditUIProjektchef();

            //---Tar bort redan tillagda "instansknappar"---
            taBortAllaInstansknappar();

            //---Skapar "instansknappar"---
            //...Hållbarhetsmålen
            skapaInstansknappar(projektinfoMal, ProjektHandlaggare.Instanstyp.HALLBARHETSMAL);
            //...Admin
            skapaInstansknappar(projektinfoAdmins, ProjektHandlaggare.Instanstyp.ADMIN);
            //...Handläggare
            skapaInstansknappar(projektinfoHandlaggare, ProjektHandlaggare.Instanstyp.HANDLAGGARE);
            //...Partners
            skapaInstansknappar(projektinfoPartners, ProjektHandlaggare.Instanstyp.PARTNER);

            System.out.println("Info har laddats för visning.");

        } catch (InfException e) {
            System.out.println("Info kunde ej laddas. " + e.getMessage());
        }
        pnlTop.revalidate();
        pnlTop.repaint();
        //------------------------------------
    }

    private void vaxlaBorttagningslageMal() {
        //Ändrar fältets tillstånd och uppdaterar knappens visning utifrån nya tillståndet 
        borttagningslageMal = !borttagningslageMal;
        uppdateraBorttagningslageUI(borttagningslageMal, btnTaBortMal);
    }

    private void vaxlaBorttagningslageLand() {
        borttagningslageLand = !borttagningslageLand;
        uppdateraBorttagningslageUI(borttagningslageLand, btnTaBortLand);
    }

    private void vaxlaBorttagningslageDeltagare() {
        borttagningslageDeltagare = !borttagningslageDeltagare;
        uppdateraBorttagningslageUI(borttagningslageDeltagare, btnTaBortDeltagare);
    }

    private void vaxlaBorttagningslagePartners() {
        borttagningslagePartners = !borttagningslagePartners;
        uppdateraBorttagningslageUI(borttagningslagePartners, btnTaBortPartners);
    }

    private void aterstallBorttagningslagen() {
        borttagningslageMal = false;
        borttagningslageLand = false;
        borttagningslageDeltagare = false;
        borttagningslagePartners = false;
        uppdateraAllaBorttagningslagenUI();

    }

    private void uppdateraBorttagningslageUI(Boolean bortagningslage, JButton taBortKnapp) {
        //Sätter texten som antingen [ Avbryt borttagning ] eller [ Ta bort ]
        String knappText = bortagningslage ? "[ Avbryt borttagning ]" : "[ Ta bort ]";
        //Sätter färgen som antingen röd eller vit utifrån bortagningsläget
        Color knappFarg = bortagningslage ? new Color(160, 50, 50) : bakgrundsfarg;
        taBortKnapp.setText(knappText);
        taBortKnapp.setBackground(knappFarg);

        //Uppdaterar layout och färger
        taBortKnapp.getParent().revalidate();
        taBortKnapp.getParent().repaint();
    }

    private void uppdateraAllaBorttagningslagenUI() {
        uppdateraBorttagningslageUI(borttagningslageMal, btnTaBortMal);
        uppdateraBorttagningslageUI(borttagningslageLand, btnTaBortLand);
        uppdateraBorttagningslageUI(borttagningslageDeltagare, btnTaBortDeltagare);
        uppdateraBorttagningslageUI(borttagningslagePartners, btnTaBortPartners);
    }

    private void uppdateraEditUI() {
        pnlTaBortMal.setVisible(redigerar);
        btnTaBortDeltagare.setVisible(redigerar);
        pnlTaBortPartners.setVisible(redigerar);
        uppdateraEditUILand(); //Ta bort + byt
        uppdateraEditUIProjektchef(); //byt
    }

    /**
     * Edit-UI refererar till UI som används för att ändra på en viss sak inom
     * ett projekt. Exempelvis "byt"- och "ta-bort"-knapparna bredvid land.
     */
    private void uppdateraEditUILand() {
        String landText = btnLand.getText();
        if ("".equals(landText) || landText == null || "[ + ]".equals(landText)) {
            //Växla mellan [ + ] och en tom ruta ifall det inte finns något land.
            //Om redigergingsläget är på --> visa "[ + ]"
            //Om redigergingsläget är av --> visa inget (null)
            String knappText = redigerar ? "[ + ]" : null;
            btnLand.setText(knappText);

            //Edit-UI för land ska alltid vara gömd om det inte finns något land
            btnBytLand.setVisible(false);
            btnTaBortLand.setVisible(false);
        } else {
            //Växla bara knapparnas synlighet om det finns ett land
            //om redigeringsläget är på--> synligt
            //om redigergingsläget är av --> gömt
            btnBytLand.setVisible(redigerar);
            btnTaBortLand.setVisible(redigerar);
        }
    }

    private void uppdateraEditUIProjektchef() {
        String projektchefText = btnProjektchef.getText();
        if ("".equals(projektchefText) || projektchefText == null || "[ + ]".equals(projektchefText)) {
            String knappText = redigerar ? "[ + ]" : null;
            btnProjektchef.setText(knappText);
            btnBytProjektchef.setVisible(false);
        } else {
            btnBytProjektchef.setVisible(redigerar);
        }
    }

    private void uppdateraStatusUI(String status) {
        if (SwingUtils.finnsIComboBox(cbStatus, status)) {
            //Validering av input i databasen sker, därför kan denna kontroll ses som onödig, men 
            //att göra det för output är ofta bra ändå ifall fel data råkat kommit i databasen av diverse anledning.
            cbStatus.setSelectedItem(status); //Om statusen finns --> visa denna i vår ComboBox 
        } else {
            cbStatus.setSelectedItem("Ingen"); //Om statusen inte fanns (eller om item var null), visa "Ingen"
        }
        txtfStatus.setText(status);
    }

    private void uppdateraPrioritetUI(String prioritet) {
        if (SwingUtils.finnsIComboBox(cbPrioritet, prioritet)) {
            cbPrioritet.setSelectedItem(prioritet);
        } else {
            cbPrioritet.setSelectedItem("Ingen");
        }
        txtfPrioritet.setText(prioritet);
    }

    private void uppdateraStartdatumUI(String datum) {
        String startdatum = (datum == null) ? "DATUM TOMT" : datum;
        txtfStartDatum.setText(startdatum);
        java.util.Date startdatumDate = (datum == null) ? null : java.sql.Date.valueOf(datum); //Upcasting från java.sql.Date till java.util.Date;
        dateStartDatum.setDate(startdatumDate);
    }

    private void uppdateraSlutdatumUI(String datum) {
        String slutdatum = (datum == null) ? "DATUM TOMT" : datum;
        txtfSlutDatum.setText(slutdatum);
        java.util.Date slutdatumDate = (datum == null) ? null : java.sql.Date.valueOf(datum);
        dateSlutDatum.setDate(slutdatumDate);
    }

    private void sparaAndringarTillDatabas() {
        //Hashmappen andradProjektinfos key är identifieraren på informationen vi sparar (som i InfDB's HashMaps)
        HashMap<String, String> andradProjektinfo = new HashMap<>();
        //Sätter in all information från våra olika textrutor i andradProjektinfo
        andradProjektinfo.put("projektnamn", txtfProjektnamn.getText());
        andradProjektinfo.put("startdatum", new java.sql.Date(dateStartDatum.getDate().getTime()).toString()); //konverterar java.util.Date till String i format YYYY-MM-DD
        andradProjektinfo.put("slutdatum", new java.sql.Date(dateSlutDatum.getDate().getTime()).toString());
        andradProjektinfo.put("beskrivning", txarBeskrivning.getText());
        andradProjektinfo.put("status", (String) cbStatus.getSelectedItem()); //Downcast pga att getSelectedItem är generisk --> kan vara vad som helst för subtyp, vi behöver bara specifiera den.
        andradProjektinfo.put("prioritet", (String) cbPrioritet.getSelectedItem());
        andradProjektinfo.put("kostnad", txtfKostnad.getText());
        //...namn = landnamn (alias funka inte)
        andradProjektinfo.put("namn", btnLand.getText()); //måste göra väljaruta för land och anstalld!
        //projektnamn, startdatum, slutdatum, Projekt.beskrivning, "+
        //"status, Projekt.prioritet, kostnad, Land.namn as landnamn, "+
        //"CONCAT(fornamn, ' ', efternamn) as chefnamn, projektchef

        //För instansknapparna behöver vi också spara ID på något snyggt sätt
        //Spara "Ingen" i comboboxes som null
    }

    /**
     * @return returnerar det nya redigergingsläget
     *
     */
    private void vaxlaDropdownLage(JScrollPane dropdownRuta, JButton dropdownKnapp) {
        Boolean rutaNySynlighet = !dropdownRuta.isVisible();

        String pil = rutaNySynlighet ? "▼" : "▶"; //Blir rutan synlig --> pil = ▼. Blir rutan osynlig --> pil = ▶
        dropdownKnapp.setText(pil + dropdownKnapp.getText().substring(1)); //sätter texten som pil + nuvarande texten minus pilen som redan fanns
        dropdownRuta.setVisible(rutaNySynlighet);
        //Uppdaterar layout
        dropdownRuta.getParent().revalidate();
    }

    private boolean vaxlaRedigeringslage() {
        //Växla mellan redigeringslägen 
        redigerar = !redigerar;

        if (redigerar) {
            btnAndra.setText("Ångra");
            txtfKostnad.setBackground(Color.WHITE);
        } else {
            btnAndra.setText("Ändra");
            txtfKostnad.setBackground(bakgrundsfarg);
            aterstallBorttagningslagen();
            tomAndringar();

            //LÅG-PRIO FUNKTIONALITETSUTÖKNING:
            //Fönster-pup-up som säger "Är du säker att du vill ångra och ej spara förändringar?" om förändringar skett.
            //"Ja" och "Nej" knappar
            //Checkbox: "visa inte detta meddelande igen"
        }

        //---Sätter synlighet för redigerings-GUI---
        //...Datumrutor-byten
        dateStartDatum.setVisible(redigerar);
        dateSlutDatum.setVisible(redigerar);
        txtfStartDatum.setVisible(!redigerar);
        txtfSlutDatum.setVisible(!redigerar);
        //...Comborutor-byten
        cbStatus.setVisible(redigerar);
        cbPrioritet.setVisible(redigerar);
        txtfStatus.setVisible(!redigerar);
        txtfPrioritet.setVisible(!redigerar);
        //...Adderingsknappar
        btnAddMal.setVisible(redigerar);
        btnAddAdmin.setVisible(redigerar);
        btnAddHandlaggare.setVisible(redigerar);
        btnAddPartner.setVisible(redigerar);
        //...Edit-UI (knappar som ändrar på något, tex landet i projektet)
        uppdateraEditUI();
        //...Ta-Bort knappar
        //---Andra växlande värden---
        txtfKostnad.setEditable(redigerar);

        //Uppdatera layout
        pnlTop.revalidate();
        pnlTop.repaint();

        //returnerar det nya redigeringsläget
        return redigerar;
    }

    /**
     * "Instansknappar" är knappar användaren trycker på för att ta sig vidare
     * till ett nytt fönster som visar information om saken knappen
     * representerade. Knappar kan vara hållbarhetsmål, deltagare och partners.
     * Denna metod skapar en viss typ av instansknapp, som definieras via
     * parametern instanstyp. En knapp är en "instans" av typ
     * HashMap<String, String>. Genom argumentet för instans kommer information
     * (namn, id) om instansen in. Alla instansers HashMap behöver ha keys "id"
     * och "namn" med mappade värden. Just hållbarhetsmål är ett specialfall. Om
     * dess HashMap även innehåller key "målnummer" så tas även detta med i
     * knappens text. Vid tryckning av en knapp tas vi till information om dess
     * instans i ett nytt fönster. Tex i ett fönster om hållbarhetsmål med id
     * "5".
     */
    private void skapaInstansknapp(Map<String, String> instans, Instanstyp instanstyp) {
        //Gör om nyckelidentifieraren i HashMappen till "id" eftersom alias ("as...") inte fungerade i SQL-frågan...
        for (String key : instans.keySet()) {
            if (key.matches("^[aph]id$")) {
                String varde = instans.remove(key);
                instans.put("id", varde);
                break;
            }
        }

        //---Endast dessa attributer sparas per instans---
        //...namm används som text på knappen
        String namn = instans.get("namn");
        //...id skickas vidare vid knapptryckning till nya fönstret
        String id = instans.get("id");

        JButton btnInstans = new JButton(namn);
        btnInstans.setMinimumSize(new Dimension(70, 23));
        btnInstans.setMaximumSize(new Dimension(200, 23));

        switch (instanstyp) {
            case HALLBARHETSMAL -> {
                //Lägger till malnummer i knappens text om det finns
                if (instans.containsKey("malnummer")) {
                    btnInstans.setText(btnInstans.getText() + " [" + instans.get("malnummer") + "]");
                }
                //Lägger till metod vid knapp-tryck (genom klassen ActionListener)
                btnInstans.addActionListener(new ActionListener() { //<--implementerar ActionListener interface i ny instans av anonymklass
                    @Override //override av abstrakt metod
                    public void actionPerformed(ActionEvent e) {
                        //Ett pop-up fönster öppnas, fönstret som visar en lista av Hållbarhetsmål.                        
                        if (borttagningslageMal == true) {
                            registreraBorttagningInstans(projektMalBorttagna, id, btnInstans);
                        } else {//Om bortagningsläget ej är på:
                            //Öppnar ett fönster som visar en lista på land med ett visst land i fokus
                            HanteraHållbarhetsmål hallbarhetsmal = new HanteraHållbarhetsmål(anv);
                            hallbarhetsmal.setVisible(true);
                            hallbarhetsmal.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                            hallbarhetsmal.valjRad(id);
                        }
                    }
                });
                //Lägger knappen direkt efter + knappen
                pnlMal.add(btnInstans);
            }
            case ADMIN -> {
                btnInstans.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        if (borttagningslageDeltagare) {
                            registreraBorttagningInstans(projektAdminsBorttagna, id, btnInstans);
                        } else {
                            HanteraAnstalld anstalldFonster = new HanteraAnstalld(anv);
                            anstalldFonster.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                            anstalldFonster.setVisible(true);
                            //IMPLEMENTERA valjRad() metoden i denna klass!
                        }
                    }
                });
                if (instanstyp == instanstyp.ADMIN) {
                    pnlAdmin.add(btnInstans);
                }
            }
            case HANDLAGGARE -> {
                btnInstans.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        if (borttagningslageDeltagare) {
                            registreraBorttagningInstans(projektAdminsBorttagna, id, btnInstans);
                        } else {
                            HanteraAnstalld anstalldFonster = new HanteraAnstalld(anv);
                            anstalldFonster.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                            anstalldFonster.setVisible(true);
                            //IMPLEMENTERA valjRad() metoden i denna klass!
                        }
                    }
                });
                pnlHandlaggare.add(btnInstans);
            }
            case PARTNER -> {
                btnInstans.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        if (borttagningslagePartners) {
                            registreraBorttagningInstans(projektPartnersBorttagna, id, btnInstans);
                        } else {
                            HanteraPartner partnerFonster = new HanteraPartner(anv);
                            partnerFonster.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                            partnerFonster.setVisible(true);
                            //IMPLEMENTERA valjRad() I HanteraPartner FÖNSTRET
                        }
                    }
                });
                pnlPartners.add(btnInstans);
            }
            default ->
                throw new IllegalStateException();
        }
    }

    private void skapaInstansknappar(ArrayList<HashMap<String, String>> instanser, Instanstyp instanstyp) {
        for (HashMap<String, String> instans : instanser) {
            skapaInstansknapp(instans, instanstyp);
        }
    }

    private void taBortInstansknapparI(JPanel pnl) {
        int startAntal = pnl.getComponentCount();
        for (int i = 0; i < startAntal; i++) {
            Component c = pnl.getComponent(i);
            if (c instanceof JButton knapp) {
                if (knapp.getName() != null && !knapp.getName().startsWith("btnAdd")) {
                    //tar bara bort om knappens namn inte börjar med btnAdd
                    pnl.remove(knapp);
                }
            }
        }
    }

    private void taBortAllaInstansknappar() {
        taBortInstansknapparI(pnlMal);
        taBortInstansknapparI(pnlAdmin);
        taBortInstansknapparI(pnlHandlaggare);
        taBortInstansknapparI(pnlPartners);
    }

    private void tomAndringar() {
        projektinfoAndringar.clear();
        projektMalNya.clear();
        projektMalBorttagna.clear();
        projektAdminsNya.clear();
        projektAdminsBorttagna.clear();
        projektHandlaggareNya.clear();
        projektHandlaggareBorttagna.clear();
        projektPartnersNya.clear();
        projektPartnersBorttagna.clear();
    }

    /**
     * Skicka in identifierare för vilken nyckel som ska registreras som att den
     * tas bort. Tex "landId". Skicka INTE in värder för själva nyckeln, tex id
     * = 4. den knapp som skickas in är knappen vars text som töms och färg som
     * görs röd för att indikera borttagning.
     *
     * "Enstaka" i metodnamnet betyder att denna metod gäller för knappar som är
     * enstaka, eller fasta i fönstret. De tas ej bort eller läggs till.
     */
    private void registreraBorttagningEnstaka(String nyckelIdentifierare, JButton knappAttTomma) {

        //Lägg till mapping för [nyckelIdentifierare] med värdet null. Detta indikerar bortagning av land i projektet.
        projektinfoAndringar.put(nyckelIdentifierare, null);
        knappAttTomma.setText("");
    }

    /**
     * Denna tar inte in en nyckelIdentifierare som
     * registreraBorttagningEnstaka() gör. Den tar in en id-värde på en viss
     * instans som ska tas bort från detta projekt. Typen av instansen kan tex
     * vara ett hållbarhetsmål eller en partner. Denna id sparas för
     * borttagning.
     */
    private void registreraBorttagningInstans(HashSet<String> borttagnaInstanser, String id, JButton knappAttTaBort) {
        System.out.println("Bortagning registrerad");
        //spara id för instansen i fråga i en samling för eventuell borttagning
        borttagnaInstanser.add(id);
        //tar bort knappen i fråga (från dess parent-container)
        knappAttTaBort.getParent().remove(knappAttTaBort);
        pnlTop.revalidate();
        pnlTop.repaint();
    }

    private void oppnaPopupValjMal() {
        //Isntansierar popup och skickar vidare min malListener
        HanteraHållbarhetsmål malFonster = new HanteraHållbarhetsmål(anv);
        malFonster.addMalListener(new MalListener() { //<-- är en funktionell interface (1 metod), kan därför också göra till lambda
            //Implementerar en metod till min malListener som jag skickar in i malFonster genom addMalListener()
            @Override
            public void valMal(String malId, String malNamn, String malnummer) {
                //Då ett val gjorts i en pop-up (metoden kallas i pop-up fönstret):
                //...lagra ändringen (men uppdaterar inte i databasen!)
                projektMalNya.add(malId);
                //...visa ändringen
                skapaInstansknapp(
                        Map.of(
                                "id", malId,
                                "namn", malNamn,
                                "malnummer", malnummer
                        ),
                        Instanstyp.HALLBARHETSMAL);
                //...stänger pop-up fönstret
                malFonster.dispose();
                //...aktivera vår originalruta igen
                dennaFrame.setEnabled(true);
                dennaFrame.toFront();
                //växlar av alla borttagningslägen
                aterstallBorttagningslagen();
            }
        });
        //Gör att om målfönstret stängs ned så tas det bort, men andra fönster finns kvar,
        //vilket passar bra till funktionen av ett popup-fönster.
        malFonster.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        //Detta fönster görs non-interactable. Användaren
        //kan endast interagera med det nya fönstret
        this.setEnabled(false);
        //Visar pop-up fönstret
        malFonster.setVisible(true);
    }

    private void oppnaPopupValjLand() {
        //Isntansierar popup och skickar vidare min landListener
        HanteraLand landFonster = new HanteraLand(anv);
        landFonster.addLandListener(new LandListener() {
            //Implementerar en metod till min landListener som jag skickar in i landFonster genom addLandListener()
            @Override
            public void valLand(String landId, String landNamn) {
                //Då ett val gjorts i en pop-up (metoden kallas i pop-up fönstret):
                //...lagra ändringen (men uppdaterar inte i databasen!)
                projektinfoAndringar.put("lid", landId); //"lid" är land-id
                //...visa ändringen
                btnLand.setText(landNamn);
                //...stänger pop-up fönstret
                landFonster.dispose();
                //...aktivera vår originalruta igen
                dennaFrame.setEnabled(true);
                dennaFrame.toFront();
                //Visar Edit-UI igen ifall varit gömt
                uppdateraEditUILand();
                //Växlar av alla borttagningslägen
                aterstallBorttagningslagen();
            }
        });
        //Gör att om landfönstret stängs ned så tas det bort, men andra fönster finns kvar,
        //vilket passar bra till funktionen av ett popup-fönster.
        landFonster.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        //Detta fönster görs non-interactable. Användaren
        //kan endast interagera med det nya fönstret
        this.setEnabled(false);
        //Visar pop-up fönstret
        landFonster.setVisible(true);
    }

    private void oppnaPopupValjProjektchef() {
        //Isntansierar popup och skickar vidare min anstalldListener
        HanteraAnstalld anstalldFonster = new HanteraAnstalld(anv);
        anstalldFonster.addAnstalldListener(new AnstalldListener() {
            //Implementerar en metod till min landListener som jag skickar in i anstalldFonster med addAnstalldListener()
            @Override
            public void valAnstalld(String projektchefId, String fulltNamn) {
                //Då ett val gjorts i en pop-up (metoden kallas i pop-up fönstret):
                //...lagra ändringen (men uppdaterar inte i databasen!)
                projektinfoAndringar.put("projektchef", projektchefId); //projektchef är aid för projektchef
                //...visa ändringen
                btnProjektchef.setText(fulltNamn);
                //...stänger pop-up fönstret
                anstalldFonster.dispose();
                //...aktivera vår originalruta igen
                dennaFrame.setEnabled(true);
                dennaFrame.toFront();
                //Visar Edit-UI igen ifall varit gömt
                uppdateraEditUIProjektchef();
                //Växlar av alla borttagningslägen
                aterstallBorttagningslagen();
            }
        });
        //Gör att om anstalldFonster stängs ned så tas det bort, men andra fönster finns kvar,
        //vilket passar bra till funktionen av ett popup-fönster.
        anstalldFonster.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        //Detta fönster görs non-interactable. Användaren
        //kan endast interagera med det nya fönstret
        this.setEnabled(false);
        //Visar pop-up fönstret
        anstalldFonster.setVisible(true);
    }

    private void oppnaPopupValjAdmin() {
        //Isntansierar popup och skickar vidare min anstalldListener
        HanteraAnstalld anstalldFonster = new HanteraAnstalld(anv);
        anstalldFonster.addAnstalldListener(new AnstalldListener() {
            //Implementerar en metod till min anstalldListener som jag skickar in i anstalldFonster med metoden addAnstalldListener
            @Override
            public void valAnstalld(String adminId, String fulltNamn) {
                //Då ett val gjorts i en pop-up (metoden kallas i pop-up fönstret):
                //...lagra ändringen (men uppdaterar inte i databasen!)
                projektAdminsNya.add(adminId);
                //...visa ändringen
                skapaInstansknapp(
                        Map.of(
                                "id", adminId,
                                "namn", fulltNamn
                        ),
                        Instanstyp.ADMIN);
                //...stänger pop-up fönstret
                anstalldFonster.dispose();
                //...aktivera vår originalruta igen
                dennaFrame.setEnabled(true);
                dennaFrame.toFront();
                //Växlar av alla borttagningslägen
                aterstallBorttagningslagen();
            }
        });
        //Gör att om anstalldFonster stängs ned så tas det bort, men andra fönster finns kvar,
        //vilket passar bra till funktionen av ett popup-fönster.
        anstalldFonster.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        //Detta fönster görs non-interactable. Användaren
        //kan endast interagera med det nya fönstret
        this.setEnabled(false);
        //Visar pop-up fönstret
        anstalldFonster.setVisible(true);
    }

    private void oppnaPopupValjHandlaggare() {
        //Isntansierar popup och skickar vidare min anstalldListener
        HanteraAnstalld anstalldFonster = new HanteraAnstalld(anv);
        anstalldFonster.addAnstalldListener(new AnstalldListener() {
            //Implementerar en metod till min anstalldListener som jag skickar in i anstalldFonster med metoden addAnstalldListener
            @Override
            public void valAnstalld(String handlaggareId, String fulltNamn) {
                //Då ett val gjorts i en pop-up (metoden kallas i pop-up fönstret):
                //...lagra ändringen (men uppdaterar inte i databasen!)
                projektAdminsNya.add(handlaggareId);
                //...visa ändringen
                skapaInstansknapp(
                        Map.of(
                                "id", handlaggareId,
                                "namn", fulltNamn
                        ),
                        Instanstyp.HANDLAGGARE);
                //...stänger pop-up fönstret
                anstalldFonster.dispose();
                //...aktivera vår originalruta igen
                dennaFrame.setEnabled(true);
                dennaFrame.toFront();
                //Växlar av alla borttagningslägen
                aterstallBorttagningslagen();
            }
        });
        //Gör att om anstalldFonster stängs ned så tas det bort, men andra fönster finns kvar,
        //vilket passar bra till funktionen av ett popup-fönster.
        anstalldFonster.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        //Detta fönster görs non-interactable. Användaren
        //kan endast interagera med det nya fönstret
        this.setEnabled(false);
        //Visar pop-up fönstret
        anstalldFonster.setVisible(true);
    }

    private void oppnaPopupValjPartner() {
        //Gör som metoderna ovan
        //Använd HanteraPartner, kollla rollen i början
    }

    private boolean arTom(String id) {
        //True om [det] för projektet saknas ([det] är tex land)
        boolean saknas = projektinfoEnskilda.get(id) == null;
        //True om en lagrad ändring finns
        boolean andrat = projektinfoAndringar.containsKey(id);
        //True om en lagrad ändring finns och lagrade ändringen är null.
        boolean borttaget = andrat && projektinfoAndringar.get(id) == null;
        //True om [det] som visas garanterat är tomt oavsett om användaren är i redigeringsläget eller ej
        boolean arTom = (saknas && !andrat) || borttaget;
        return arTom;
    }

    private void btnDeltagareDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeltagareDropdownActionPerformed
        vaxlaDropdownLage(spnlDeltagareDropdown, btnDeltagareDropdown);
    }//GEN-LAST:event_btnDeltagareDropdownActionPerformed

    private void btnMalDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMalDropdownActionPerformed
        vaxlaDropdownLage(spnlMalDropdown, btnMalDropdown);
    }//GEN-LAST:event_btnMalDropdownActionPerformed

    private void btnPartnersDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartnersDropdownActionPerformed
        vaxlaDropdownLage(spnlPartnersDropdown, btnPartnersDropdown);

    }//GEN-LAST:event_btnPartnersDropdownActionPerformed

    private void btnBeskrivningDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeskrivningDropdownActionPerformed
        vaxlaDropdownLage(spnlBeskrivningDropdown, btnBeskrivningDropdown);
    }//GEN-LAST:event_btnBeskrivningDropdownActionPerformed

    private void btnAddHandlaggareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHandlaggareActionPerformed
        oppnaPopupValjHandlaggare();
    }//GEN-LAST:event_btnAddHandlaggareActionPerformed

    private void btnAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAdminActionPerformed
        oppnaPopupValjAdmin();
    }//GEN-LAST:event_btnAddAdminActionPerformed

    private void btnAddMalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMalActionPerformed
        oppnaPopupValjMal();
    }//GEN-LAST:event_btnAddMalActionPerformed

    private void btnAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraActionPerformed
        //---Om användaren trycker på samma knapp i redigeringsläget (ångra knappen)---
        if (vaxlaRedigeringslage() == false) {
            //laddar om infon, eventuella ändringar som gjordes i redigeringsläget försvinner
            tomAndringar();
            laddaInfo();
        }
    }//GEN-LAST:event_btnAndraActionPerformed

    private void txtfStartDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfStartDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfStartDatumActionPerformed

    private void txtfSlutDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfSlutDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfSlutDatumActionPerformed

    private void txtfProjektnamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfProjektnamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfProjektnamnActionPerformed

    private void btnLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLandActionPerformed

        if (redigerar && arTom("lid")) {//Alias "as landId" fungerade inte, behöver använda lid 
            //Öppna popup för att välja ett fisst land om användaren redigerar och det ej visas något land
            System.out.println("Öppnar popup ruta för land att välja");
            oppnaPopupValjLand();
        } else if (borttagningslageLand) {
            registreraBorttagningEnstaka("lid", btnLand);
            uppdateraEditUILand();
        } else {//Om bortagningsläget ej är på:
            //Öppnar ett fönster som visar en lista på land med ett visst land i fokus
            HanteraLand landFonster = new HanteraLand(anv);
            landFonster.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            landFonster.setVisible(true);
            //IMPLEMENTERA valjRow I HANTERALAND FÖNSTRET OCH KALLA HÄR
        }
    }//GEN-LAST:event_btnLandActionPerformed

    private void btnBytLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBytLandActionPerformed
        oppnaPopupValjLand();
    }//GEN-LAST:event_btnBytLandActionPerformed

    private void btnBytProjektchefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBytProjektchefActionPerformed
        oppnaPopupValjProjektchef();
    }//GEN-LAST:event_btnBytProjektchefActionPerformed

    private void btnTaBortPartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortPartnersActionPerformed
        vaxlaBorttagningslagePartners();
    }//GEN-LAST:event_btnTaBortPartnersActionPerformed

    private void btnTaBortDeltagareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortDeltagareActionPerformed
        if (redigerar) {
            vaxlaBorttagningslageDeltagare();
        }
    }//GEN-LAST:event_btnTaBortDeltagareActionPerformed

    private void btnTaBortMalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortMalActionPerformed
        if (redigerar) {
            vaxlaBorttagningslageMal();
        }
    }//GEN-LAST:event_btnTaBortMalActionPerformed

    private void btnTaBortLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortLandActionPerformed
        if (redigerar) {
            vaxlaBorttagningslageLand();
        }
    }//GEN-LAST:event_btnTaBortLandActionPerformed

    private void btnProjektchefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjektchefActionPerformed
        if (redigerar && arTom("projektchef")) { //"projektchef" är aid för projektchef
            oppnaPopupValjProjektchef();
        } else if (borttagningslageDeltagare) {
            registreraBorttagningEnstaka("projektchef", btnProjektchef);
            //Uppdaterar för att se till att EditUI göms och att knappen visar [ + ] 
            uppdateraEditUIProjektchef();
        } else {//Om bortagningsläget ej är på:
            //Öppnar ett fönster som visar en lista på anstallda med denna projektchef i fokus
            HanteraAnstalld anstalldFonster = new HanteraAnstalld(anv);
            anstalldFonster.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            anstalldFonster.setVisible(true);
            //IMPLEMENTERA valjRow I HANTERALAND FÖNSTRET OCH KALLA HÄR
        }
    }//GEN-LAST:event_btnProjektchefActionPerformed

    private void btnAddPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPartnerActionPerformed
        oppnaPopupValjPartner();
    }//GEN-LAST:event_btnAddPartnerActionPerformed

    public static void main(String args[]) { //TA BORT MAIN METODEN TILLSLUT. NI SKA ENDAST ANVÄNDA MAIN METODEN I Startklassen
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {

        }
        //</editor-fold>

        try {
            InfDB idb = new InfDB("sdgsweden", "3306", "root", "masterkey");
            new ProjektProjektchef(new Anvandare(idb, null, null, null, 3, null, null, null, "admin"), 3).setVisible(true);
            System.out.println("Databaskoppling skapad");
        } catch (InfException e) {
            System.out.println(e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAdmin;
    private javax.swing.JButton btnAddHandlaggare;
    private javax.swing.JButton btnAddMal;
    private javax.swing.JButton btnAddPartner;
    private javax.swing.JButton btnAndra;
    private javax.swing.JButton btnBeskrivningDropdown;
    private javax.swing.JButton btnBytLand;
    private javax.swing.JButton btnBytProjektchef;
    private javax.swing.JButton btnDeltagareDropdown;
    private javax.swing.JButton btnLand;
    private javax.swing.JButton btnMalDropdown;
    private javax.swing.JButton btnPartnersDropdown;
    private javax.swing.JButton btnProjektchef;
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTaBortDeltagare;
    private javax.swing.JButton btnTaBortLand;
    private javax.swing.JButton btnTaBortMal;
    private javax.swing.JButton btnTaBortPartners;
    private javax.swing.JComboBox<String> cbPrioritet;
    private javax.swing.JComboBox<String> cbStatus;
    private com.toedter.calendar.JDateChooser dateSlutDatum;
    private com.toedter.calendar.JDateChooser dateStartDatum;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAvslutad;
    private javax.swing.JLabel lblFelmeddelandeAdmin;
    private javax.swing.JLabel lblFelmeddelandeHandlaggare;
    private javax.swing.JLabel lblFelmeddelandeKostnad;
    private javax.swing.JLabel lblFelmeddelandeMal;
    private javax.swing.JLabel lblFelmeddelandePartners;
    private javax.swing.JLabel lblFelmeddelandeProjektchef;
    private javax.swing.JLabel lblPid;
    private javax.swing.JLabel lblStartar;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlBeskrivning;
    private javax.swing.JPanel pnlDeltagare;
    private javax.swing.JPanel pnlFelmeddelandeKostnad;
    private javax.swing.JPanel pnlHandlaggare;
    private javax.swing.JPanel pnlHoger;
    private javax.swing.JPanel pnlLand;
    private javax.swing.JPanel pnlMal;
    private javax.swing.JPanel pnlPartners;
    private javax.swing.JPanel pnlProjektchef;
    private javax.swing.JPanel pnlProjektnamn;
    private javax.swing.JPanel pnlSlutDatum;
    private javax.swing.JPanel pnlStartDatum;
    private javax.swing.JPanel pnlTaBortLand;
    private javax.swing.JPanel pnlTaBortMal;
    private javax.swing.JPanel pnlTaBortPartners;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JPanel pnlVanster;
    private javax.swing.JScrollPane spnlBeskrivningDropdown;
    private javax.swing.JScrollPane spnlDeltagareDropdown;
    private javax.swing.JScrollPane spnlMalDropdown;
    private javax.swing.JScrollPane spnlPartnersDropdown;
    private javax.swing.JScrollPane spnlTop;
    private javax.swing.JTextArea txarBeskrivning;
    private javax.swing.JTextField txtfKostnad;
    private javax.swing.JTextField txtfPrioritet;
    private javax.swing.JTextField txtfProjektnamn;
    private javax.swing.JTextField txtfSlutDatum;
    private javax.swing.JTextField txtfStartDatum;
    private javax.swing.JTextField txtfStatus;
    // End of variables declaration//GEN-END:variables
}
