/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.ArrayList;
import java.util.HashMap;
import static javaapplication3.ProjektHandlaggare.Instanstyp.*;
import javax.swing.*;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author alexander.willen
 */
public class ProjektProjektchef extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProjektProjektchef.class.getName());

    //Bakgrundsfärgen som används av vårt valda "tema" i NetBeans
    private static final Color bakgrundsfarg = new Color(212, 217, 223);

    //Session
    private InfDB idb; //databas
    private int aid; //användarens id
    private int pid; //det valda projektet vars uppgifter visas
  

    //Redigeringsläge
    private boolean redigerar;

    public ProjektProjektchef(InfDB idb, int aid, int pid)
    {
        this.idb = idb;
        this.aid = aid;
        this.pid = pid;
        redigerar = false;
        
        initComponents();
        laddaInfo();
        startlageGUI(); //lägg till pluss knapparna sist
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnlTop = new javax.swing.JScrollPane();
        pnlTop = new javax.swing.JPanel();
        lblPid = new javax.swing.JLabel();
        lblStartar = new javax.swing.JLabel();
        lblAvslutad = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        pnlVanster = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        btnMal = new javax.swing.JButton();
        lblMalTips = new javax.swing.JLabel();
        spnlMal = new javax.swing.JScrollPane();
        pnlMal = new javax.swing.JPanel();
        btnAddMal = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        btnBeskrivning = new javax.swing.JButton();
        spnlBeskrivning = new javax.swing.JScrollPane();
        pnlBeskrivning = new javax.swing.JPanel();
        txarBeskrivning = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnLand = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtfStatus = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtfPrioritet = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtfKostnad = new javax.swing.JTextField();
        pnlHoger = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btnDeltagare = new javax.swing.JButton();
        lblDeltagareTips = new javax.swing.JLabel();
        spnlDeltagare = new javax.swing.JScrollPane();
        pnlDeltagare = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        pnlAdmin = new javax.swing.JPanel();
        btnAddAdmin = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        pnlHandlaggare = new javax.swing.JPanel();
        btnAddHandlaggare = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        pnlProjektchef = new javax.swing.JPanel();
        btnAddProjektchef = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        btnPartners = new javax.swing.JButton();
        lblPartnersTips = new javax.swing.JLabel();
        spnlPartners = new javax.swing.JScrollPane();
        pnlPartners = new javax.swing.JPanel();
        btnAddPartner = new javax.swing.JButton();
        pnlStartDatum = new javax.swing.JPanel();
        txtfStartDatum = new javax.swing.JTextField();
        dateStartDatum = new com.toedter.calendar.JDateChooser();
        pnlSlutDatum = new javax.swing.JPanel();
        txtfSlutDatum = new javax.swing.JTextField();
        dateSlutDatum = new com.toedter.calendar.JDateChooser();
        pnlProjektnamn = new javax.swing.JPanel();
        txtfProjektnamn = new javax.swing.JTextField();
        btnAndra = new javax.swing.JButton();
        btnSpara = new javax.swing.JButton();
        lblFelmeddelande = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        spnlTop.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        spnlTop.setPreferredSize(new java.awt.Dimension(730, 577));

        pnlTop.setMaximumSize(new java.awt.Dimension(700, 2000));

        lblPid.setText("Projektid: [pid]");
        lblPid.setMaximumSize(new java.awt.Dimension(150, 16));

        lblStartar.setText("Startad");

        lblAvslutad.setText("Avslutad");

        jButton8.setText("Tillbaka till Meny");
        jButton8.addActionListener(this::jButton8ActionPerformed);

        pnlVanster.setMaximumSize(new java.awt.Dimension(385, 30000));
        pnlVanster.setMinimumSize(new java.awt.Dimension(200, 260));
        pnlVanster.setLayout(new javax.swing.BoxLayout(pnlVanster, javax.swing.BoxLayout.Y_AXIS));

        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel9.setMaximumSize(new java.awt.Dimension(310, 35));
        jPanel9.setPreferredSize(new java.awt.Dimension(250, 35));

        btnMal.setText("▶ Hållbarhetsmål");
        btnMal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMal.setMaximumSize(new java.awt.Dimension(160, 160));
        btnMal.setMinimumSize(new java.awt.Dimension(86, 23));
        btnMal.setPreferredSize(new java.awt.Dimension(86, 23));
        btnMal.addActionListener(this::btnMalActionPerformed);

        lblMalTips.setForeground(new java.awt.Color(204, 204, 0));
        lblMalTips.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMalTips.setText("Tryck för att ta bort");
        lblMalTips.setPreferredSize(new java.awt.Dimension(320, 16));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(btnMal, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMalTips, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMal, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMalTips, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlVanster.add(jPanel9);

        spnlMal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        spnlMal.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        spnlMal.setMaximumSize(new java.awt.Dimension(310, 120));
        spnlMal.setMinimumSize(new java.awt.Dimension(310, 100));
        spnlMal.setPreferredSize(new java.awt.Dimension(310, 100));

        pnlMal.setMaximumSize(null);
        pnlMal.setMinimumSize(new java.awt.Dimension(200, 90));
        pnlMal.setOpaque(false);
        pnlMal.setPreferredSize(new java.awt.Dimension(200, 90));
        pnlMal.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnAddMal.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        btnAddMal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikoner/plusikon.png"))); // NOI18N
        btnAddMal.setIconTextGap(0);
        btnAddMal.setMargin(new java.awt.Insets(2, 13, 3, 14));
        btnAddMal.setPreferredSize(new java.awt.Dimension(19, 19));
        btnAddMal.addActionListener(this::btnAddMalActionPerformed);
        pnlMal.add(btnAddMal);

        spnlMal.setViewportView(pnlMal);

        pnlVanster.add(spnlMal);

        jPanel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel13.setMaximumSize(new java.awt.Dimension(310, 38));
        jPanel13.setMinimumSize(new java.awt.Dimension(139, 38));
        jPanel13.setName(""); // NOI18N
        jPanel13.setPreferredSize(new java.awt.Dimension(250, 38));

        btnBeskrivning.setText("▶ Beskrivning");
        btnBeskrivning.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBeskrivning.setMargin(new java.awt.Insets(0, 0, 0, 14));
        btnBeskrivning.setMaximumSize(new java.awt.Dimension(160, 160));
        btnBeskrivning.setMinimumSize(new java.awt.Dimension(123, 30));
        btnBeskrivning.setPreferredSize(new java.awt.Dimension(125, 30));
        btnBeskrivning.setVerifyInputWhenFocusTarget(false);
        btnBeskrivning.addActionListener(this::btnBeskrivningActionPerformed);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(btnBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 175, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(btnBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlVanster.add(jPanel13);

        spnlBeskrivning.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        spnlBeskrivning.setToolTipText("");
        spnlBeskrivning.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        spnlBeskrivning.setMaximumSize(new java.awt.Dimension(32767, 60));
        spnlBeskrivning.setMinimumSize(new java.awt.Dimension(225, 60));
        spnlBeskrivning.setPreferredSize(new java.awt.Dimension(230, 60));

        pnlBeskrivning.setMinimumSize(new java.awt.Dimension(220, 100));
        pnlBeskrivning.setName(""); // NOI18N
        pnlBeskrivning.setLayout(new java.awt.BorderLayout());

        txarBeskrivning.setColumns(5);
        txarBeskrivning.setLineWrap(true);
        txarBeskrivning.setRows(5);
        txarBeskrivning.setText("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
        txarBeskrivning.setWrapStyleWord(true);
        txarBeskrivning.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txarBeskrivning.setMaximumSize(new java.awt.Dimension(200, 84));
        txarBeskrivning.setMinimumSize(new java.awt.Dimension(200, 20));
        pnlBeskrivning.add(txarBeskrivning, java.awt.BorderLayout.PAGE_START);

        spnlBeskrivning.setViewportView(pnlBeskrivning);

        pnlVanster.add(spnlBeskrivning);

        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 0, 4, 0));
        jPanel10.setMaximumSize(new java.awt.Dimension(310, 32));
        jPanel10.setPreferredSize(new java.awt.Dimension(200, 36));

        jLabel12.setText("Land");

        btnLand.setText(" [Land]");
        btnLand.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        btnLand.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLand.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnLand.setMaximumSize(new java.awt.Dimension(180, 30));
        btnLand.setMinimumSize(new java.awt.Dimension(43, 30));
        btnLand.setPreferredSize(new java.awt.Dimension(50, 30));
        btnLand.addActionListener(this::btnLandActionPerformed);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(43, 43, 43)
                .addComponent(btnLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap())
        );

        pnlVanster.add(jPanel10);

        jPanel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 0, 4, 0));
        jPanel12.setMaximumSize(new java.awt.Dimension(310, 32));
        jPanel12.setPreferredSize(new java.awt.Dimension(200, 36));

        jLabel13.setText("Status");

        txtfStatus.setEditable(false);
        txtfStatus.setBackground(new java.awt.Color(212, 217, 223));
        txtfStatus.setText("[Status]");
        txtfStatus.setFocusable(false);
        txtfStatus.setMaximumSize(new java.awt.Dimension(160, 30));
        txtfStatus.setMinimumSize(new java.awt.Dimension(45, 30));
        txtfStatus.setPreferredSize(new java.awt.Dimension(60, 30));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(36, 36, 36)
                .addComponent(txtfStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtfStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlVanster.add(jPanel12);

        jPanel14.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 0, 4, 0));
        jPanel14.setMaximumSize(new java.awt.Dimension(310, 32));
        jPanel14.setPreferredSize(new java.awt.Dimension(200, 36));

        jLabel15.setText("Prioritet");

        txtfPrioritet.setEditable(false);
        txtfPrioritet.setBackground(new java.awt.Color(212, 217, 223));
        txtfPrioritet.setText("[Prioritet]");
        txtfPrioritet.setFocusable(false);
        txtfPrioritet.setMaximumSize(new java.awt.Dimension(185, 30));
        txtfPrioritet.setMinimumSize(new java.awt.Dimension(45, 30));
        txtfPrioritet.setPreferredSize(new java.awt.Dimension(70, 30));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(29, 29, 29)
                .addComponent(txtfPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtfPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlVanster.add(jPanel14);

        jPanel15.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 0, 4, 0));
        jPanel15.setMaximumSize(new java.awt.Dimension(310, 32));
        jPanel15.setPreferredSize(new java.awt.Dimension(200, 36));

        jLabel17.setText("Kostnad");

        txtfKostnad.setEditable(false);
        txtfKostnad.setBackground(new java.awt.Color(212, 217, 223));
        txtfKostnad.setText("[Kostnad]");
        txtfKostnad.setFocusable(false);
        txtfKostnad.setMaximumSize(new java.awt.Dimension(200, 30));
        txtfKostnad.setMinimumSize(new java.awt.Dimension(64, 30));
        txtfKostnad.setPreferredSize(new java.awt.Dimension(70, 30));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addGap(26, 26, 26)
                .addComponent(txtfKostnad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtfKostnad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlVanster.add(jPanel15);

        pnlHoger.setLayout(new javax.swing.BoxLayout(pnlHoger, javax.swing.BoxLayout.Y_AXIS));

        jPanel8.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel8.setPreferredSize(new java.awt.Dimension(456, 35));

        btnDeltagare.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDeltagare.setLabel("▼ Deltagare");
        btnDeltagare.setMaximumSize(new java.awt.Dimension(200, 160));
        btnDeltagare.setMinimumSize(new java.awt.Dimension(93, 30));
        btnDeltagare.setPreferredSize(new java.awt.Dimension(93, 35));
        btnDeltagare.addActionListener(this::btnDeltagareActionPerformed);

        lblDeltagareTips.setForeground(new java.awt.Color(204, 204, 0));
        lblDeltagareTips.setText("Tryck för att ta bort");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(btnDeltagare, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lblDeltagareTips)
                .addGap(0, 132, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeltagare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeltagareTips)))
        );

        pnlHoger.add(jPanel8);

        spnlDeltagare.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        spnlDeltagare.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        spnlDeltagare.setMaximumSize(new java.awt.Dimension(32767, 300));
        spnlDeltagare.setPreferredSize(new java.awt.Dimension(395, 300));

        pnlDeltagare.setMaximumSize(new java.awt.Dimension(350, 30000));
        pnlDeltagare.setMinimumSize(new java.awt.Dimension(350, 200));
        pnlDeltagare.setPreferredSize(new java.awt.Dimension(350, 200));

        jLabel7.setText("Projektchef");

        jLabel8.setText("Administratörer");

        pnlAdmin.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        btnAddAdmin.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        btnAddAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikoner/plusikon.png"))); // NOI18N
        btnAddAdmin.setIconTextGap(0);
        btnAddAdmin.setMargin(new java.awt.Insets(2, 13, 3, 14));
        btnAddAdmin.setPreferredSize(new java.awt.Dimension(19, 19));
        btnAddAdmin.addActionListener(this::btnAddAdminActionPerformed);
        pnlAdmin.add(btnAddAdmin);

        pnlHandlaggare.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        btnAddHandlaggare.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        btnAddHandlaggare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikoner/plusikon.png"))); // NOI18N
        btnAddHandlaggare.setIconTextGap(0);
        btnAddHandlaggare.setMargin(new java.awt.Insets(2, 13, 3, 14));
        btnAddHandlaggare.setPreferredSize(new java.awt.Dimension(19, 19));
        btnAddHandlaggare.addActionListener(this::btnAddHandlaggareActionPerformed);
        pnlHandlaggare.add(btnAddHandlaggare);

        jLabel9.setText("Handläggare");

        pnlProjektchef.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        btnAddProjektchef.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        btnAddProjektchef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikoner/plusikon.png"))); // NOI18N
        btnAddProjektchef.setIconTextGap(0);
        btnAddProjektchef.setMargin(new java.awt.Insets(2, 13, 3, 14));
        btnAddProjektchef.setPreferredSize(new java.awt.Dimension(19, 19));
        btnAddProjektchef.addActionListener(this::btnAddProjektchefActionPerformed);
        pnlProjektchef.add(btnAddProjektchef);

        javax.swing.GroupLayout pnlDeltagareLayout = new javax.swing.GroupLayout(pnlDeltagare);
        pnlDeltagare.setLayout(pnlDeltagareLayout);
        pnlDeltagareLayout.setHorizontalGroup(
            pnlDeltagareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlDeltagareLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDeltagareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDeltagareLayout.createSequentialGroup()
                        .addGroup(pnlDeltagareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(0, 261, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(14, 14, 14))
            .addComponent(pnlHandlaggare, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
            .addComponent(pnlProjektchef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlDeltagareLayout.setVerticalGroup(
            pnlDeltagareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeltagareLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlProjektchef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlHandlaggare, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        spnlDeltagare.setViewportView(pnlDeltagare);

        pnlHoger.add(spnlDeltagare);

        jPanel11.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel11.setPreferredSize(new java.awt.Dimension(456, 40));

        btnPartners.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPartners.setLabel("▼ Partners");
        btnPartners.setMaximumSize(new java.awt.Dimension(160, 160));
        btnPartners.setVerifyInputWhenFocusTarget(false);
        btnPartners.addActionListener(this::btnPartnersActionPerformed);

        lblPartnersTips.setForeground(new java.awt.Color(204, 204, 0));
        lblPartnersTips.setText("Tryck för att ta bort");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(btnPartners, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(lblPartnersTips)
                .addGap(0, 130, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPartners, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPartnersTips)))
        );

        pnlHoger.add(jPanel11);

        spnlPartners.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        spnlPartners.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        spnlPartners.setMinimumSize(new java.awt.Dimension(16, 100));
        spnlPartners.setPreferredSize(new java.awt.Dimension(375, 100));

        pnlPartners.setMaximumSize(null);
        pnlPartners.setMinimumSize(new java.awt.Dimension(350, 60));
        pnlPartners.setPreferredSize(new java.awt.Dimension(350, 60));
        pnlPartners.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnAddPartner.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        btnAddPartner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikoner/plusikon.png"))); // NOI18N
        btnAddPartner.setIconTextGap(0);
        btnAddPartner.setMargin(new java.awt.Insets(2, 13, 3, 14));
        btnAddPartner.setPreferredSize(new java.awt.Dimension(19, 19));
        pnlPartners.add(btnAddPartner);

        spnlPartners.setViewportView(pnlPartners);

        pnlHoger.add(spnlPartners);

        pnlStartDatum.setMinimumSize(new java.awt.Dimension(20, 30));
        pnlStartDatum.setPreferredSize(new java.awt.Dimension(20, 30));
        pnlStartDatum.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtfStartDatum.setEditable(false);
        txtfStartDatum.setBackground(new java.awt.Color(212, 217, 223));
        txtfStartDatum.setText("ÅÅÅÅ-MM-DD");
        txtfStartDatum.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 3, 0, 0));
        txtfStartDatum.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtfStartDatum.setPreferredSize(new java.awt.Dimension(86, 16));
        txtfStartDatum.addActionListener(this::txtfStartDatumActionPerformed);
        pnlStartDatum.add(txtfStartDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));
        pnlStartDatum.add(dateStartDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        pnlSlutDatum.setMinimumSize(new java.awt.Dimension(20, 30));
        pnlSlutDatum.setPreferredSize(new java.awt.Dimension(20, 30));
        pnlSlutDatum.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtfSlutDatum.setEditable(false);
        txtfSlutDatum.setBackground(new java.awt.Color(212, 217, 223));
        txtfSlutDatum.setText("ÅÅÅÅ-MM-DD");
        txtfSlutDatum.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 3, 0, 0));
        txtfSlutDatum.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtfSlutDatum.setPreferredSize(new java.awt.Dimension(86, 16));
        txtfSlutDatum.addActionListener(this::txtfSlutDatumActionPerformed);
        pnlSlutDatum.add(txtfSlutDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));
        pnlSlutDatum.add(dateSlutDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        txtfProjektnamn.setEditable(false);
        txtfProjektnamn.setBackground(new java.awt.Color(212, 217, 223));
        txtfProjektnamn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtfProjektnamn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfProjektnamn.setText("[Projektnamn]");
        txtfProjektnamn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtfProjektnamn.setFocusable(false);
        txtfProjektnamn.setMaximumSize(new java.awt.Dimension(500, 25));
        txtfProjektnamn.setMinimumSize(new java.awt.Dimension(80, 25));
        txtfProjektnamn.setOpaque(true);
        txtfProjektnamn.setPreferredSize(new java.awt.Dimension(150, 25));
        txtfProjektnamn.addActionListener(this::txtfProjektnamnActionPerformed);
        pnlProjektnamn.add(txtfProjektnamn);

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addComponent(pnlVanster, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(pnlHoger, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(pnlProjektnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addComponent(lblAvslutad)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                        .addComponent(lblStartar)
                        .addGap(20, 20, 20)))
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlSlutDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlStartDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(280, 280, 280))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(lblPid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlProjektnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(pnlStartDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlSlutDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblStartar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAvslutad)
                        .addGap(23, 23, 23)))
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlVanster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlHoger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(254, Short.MAX_VALUE))
        );

        spnlTop.setViewportView(pnlTop);

        btnAndra.setText("Ändra");
        btnAndra.addActionListener(this::btnAndraActionPerformed);

        btnSpara.setText("Spara");

        lblFelmeddelande.setForeground(new java.awt.Color(255, 51, 0));
        lblFelmeddelande.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFelmeddelande.setText("[felmeddelande]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAndra, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnSpara, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(spnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblFelmeddelande, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(spnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAndra)
                    .addComponent(btnSpara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFelmeddelande)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startlageGUI() {
        //Gömmer pop-up paneler
        spnlMal.setVisible(false);
        spnlBeskrivning.setVisible(false);
        spnlDeltagare.setVisible(false);
        spnlPartners.setVisible(false);        

        //----NYTT FÖR PROJEKTCHEF----------------------------------------
        
        //---Redigerings-läget---
        //...Datum rutor
        dateStartDatum.setVisible(false);
        dateSlutDatum.setVisible(false);
        //...Adderingsknappar
        btnAddMal.setVisible(false);
        btnAddProjektchef.setVisible(false);
        btnAddAdmin.setVisible(false);
        btnAddHandlaggare.setVisible(false);
        btnAddPartner.setVisible(false);
        //...Tipsrutor
        lblMalTips.setVisible(false);
        lblDeltagareTips.setVisible(false);
        lblPartnersTips.setVisible(false);
        //...Felmeddelande
        lblFelmeddelande.setVisible(false);
    }
    
  
    private void laddaInfo(){
        
        try{
            //---Hämtar projektinfo---
            HashMap<String, String> projektinfoEnskilda = idb.fetchRow(
                    "SELECT projektnamn, startdatum, slutdatum, Projekt.beskrivning, "+
                    "status, Projekt.prioritet, kostnad, Land.namn as landnamn, "+
                    "CONCAT(fornamn, ' ', efternamn) as chefnamn, projektchef "+
                    "FROM Projekt "+
                    "JOIN Land ON land = lid "+
                    "JOIN Anstalld ON projektchef = aid "+
                    "WHERE pid = "+pid);
            
            ArrayList<HashMap<String, String>> projektinfoMal = idb.fetchRows(
                    "SELECT malnummer, namn, h.hid as id "+
                    "FROM Hallbarhetsmal h "+ 
                    "JOIN Proj_Hallbarhet ph on h.hid = ph.hid "+
                    "WHERE ph.pid = "+pid);
            
            ArrayList<HashMap<String, String>> projektinfoAdmin = idb.fetchRows(
                    "SELECT CONCAT(fornamn, ' ', efternamn) as namn, a.aid as id "+
                    "FROM Anstalld a "+ 
                    "JOIN Admin ad on a.aid = ad.aid "+
                    "JOIN Ans_Proj ap on a.aid = ap.aid "+
                    "WHERE ap.pid = "+pid);
            
            ArrayList<HashMap<String, String>> projektinfoHandlaggare = idb.fetchRows(
                    "SELECT CONCAT(fornamn, ' ', efternamn) as namn, a.aid as id "+
                    "FROM Anstalld a "+ 
                    "JOIN Handlaggare h on a.aid = h.aid "+
                    "JOIN Ans_Proj ap on a.aid = ap.aid "+
                    "WHERE ap.pid = "+pid);
            
            ArrayList<HashMap<String, String>> projektinfoPartners = idb.fetchRows(
                    "SELECT namn, p.pid as id "+
                    "FROM Partner p "+ 
                    "JOIN Projekt_Partner pp on p.pid = pp.partner_pid "+
                    "WHERE pp.pid = "+pid);
            
            
            //---Visar hämtad projektInfo---
            //...ändrar text
            lblPid.setText("Projektid: " + pid);
            txtfProjektnamn.setText(projektinfoEnskilda.get("projektnamn"));
            txarBeskrivning.setText(projektinfoEnskilda.get("beskrivning"));
            txtfStatus.setText(projektinfoEnskilda.get("status"));
            txtfPrioritet.setText(projektinfoEnskilda.get("prioritet"));
            txtfKostnad.setText(projektinfoEnskilda.get("kostnad"));
            //-----NYTT FÖR PROJEKTCHEF-----
            String startdatum = projektinfoEnskilda.get("startdatum");
            String slutdatum = projektinfoEnskilda.get("slutdatum");
            txtfStartDatum.setText(startdatum);
            txtfSlutDatum.setText(slutdatum);

            Date startdatumDate = java.sql.Date.valueOf(startdatum); //Upcasting
            Date slutdatumDate =  java.sql.Date.valueOf(slutdatum);
            dateStartDatum.setDate(startdatumDate);
            dateSlutDatum.setDate(slutdatumDate);
            //-------------------------------
            
            
            //---Skapar "instansknappar"---
            //...Hållbarhetsmålen
            skapaInstansknappar(projektinfoMal, ProjektHandlaggare.Instanstyp.HALLBARHETSMAL);
            //...Admin
            skapaInstansknappar(projektinfoAdmin, ProjektHandlaggare.Instanstyp.ADMIN);
            //...Handläggare
            skapaInstansknappar(projektinfoHandlaggare, ProjektHandlaggare.Instanstyp.HANDLAGGARE);
            //...Partners
            skapaInstansknappar(projektinfoPartners, ProjektHandlaggare.Instanstyp.PARTNERS);
            //...Projektchef
            if(projektinfoEnskilda.get("projektchef") != null){
                JButton btnProjektchef = new JButton(projektinfoEnskilda.get("chefnamn"));
                pnlProjektchef.add(btnProjektchef, 0);
                btnProjektchef.setMinimumSize(new Dimension(70, 23));
                btnProjektchef.setMaximumSize(new Dimension(200, 23));
                skapaActionBtnProjektchef(btnProjektchef);
            }
            //...Land
            if(projektinfoEnskilda.get("namn") != null){
                 btnLand.setText(projektinfoEnskilda.get("namn"));
                 skapaActionBtnLand();
            }
        }
        catch(InfException e){
            System.out.println("Info kunde ej laddas. "+e.getMessage());
        }
        
        pnlTop.revalidate();
    }
    
    private void sparaAndradInfo(){
        //pid är projektid
        //andradProjektinfo är en samling som sparar ändrad projektinfo. Nyckeln i 
        //denna HashMap sparar attribut-identifierare på samma sätt som FetchRow() i InfDB
        HashMap<String, String> andradProjektinfo = new HashMap<>();
        andradProjektinfo.put("projektnamn", txtfProjektnamn.getText());
        andradProjektinfo.put("startdatum", new java.sql.Date(dateStartDatum.getDate().getTime()).toString()); 
                //projektnamn, startdatum, slutdatum, Projekt.beskrivning, "+
                    //"status, Projekt.prioritet, kostnad, Land.namn as landnamn, "+
                    //"CONCAT(fornamn, ' ', efternamn) as chefnamn, projektchef
    }
        
    private void vaxlaPopupSynlighet(JScrollPane popUpRuta)
    {
        Boolean rutaNySynlighet = !popUpRuta.isVisible();
        popUpRuta.setVisible(rutaNySynlighet);

        //Uppdaterar layout
        popUpRuta.getParent().revalidate();
                            
    }

    private boolean vaxlaRedigeringslage() 
    {
        //Växla mellan redigeringslägen 
        redigerar = !redigerar;

        if (redigerar) {
            btnAndra.setText("Ångra");
        } else {
            btnAndra.setText("Ändra");

            //FUNKTIONALITETSUTÖKNING:
            //Fönster-pup-up som säger "Är du säker att du vill ångra och ej spara förändringar?" om förändringar skett.
            //"Ja" och "Nej" knappar
            //Checkbox: "visa inte detta meddelande igen"
        }

        //---Sätter synlighet för redigerings-GUI---
        boolean nySynlighet = redigerar;
        //...Datum rutor
        dateStartDatum.setVisible(nySynlighet);
        dateSlutDatum.setVisible(nySynlighet);
        txtfStartDatum.setVisible(!nySynlighet);
        txtfSlutDatum.setVisible(!nySynlighet);
        //...Adderingsknappar
        btnAddMal.setVisible(nySynlighet);
        btnAddProjektchef.setVisible(nySynlighet);
        btnAddAdmin.setVisible(nySynlighet);
        btnAddHandlaggare.setVisible(nySynlighet);
        btnAddPartner.setVisible(nySynlighet);

        //Uppdatera layout
        pnlTop.revalidate();
        
        //returnerar det nya redigeringsläget
        return redigerar;
    }
    
    private void skapaInstansknappar(ArrayList<HashMap<String, String>> instanser, ProjektHandlaggare.Instanstyp instanstyp) {
        for (HashMap<String, String> instans : instanser){             
            //---Endast dessa attributer sparas per instans---
            //...namm --> används som text på knappen
            String namn = instans.get("namn");
            //...id --> skickas vidare vid knapptryckning till nya fönstret
            String id = instans.get("id");

            JButton btnInstans = new JButton(namn);
            btnInstans.setMinimumSize(new Dimension(70, 23));
            btnInstans.setMaximumSize(new Dimension(200, 23));

            switch (instanstyp) {
                case HALLBARHETSMAL:
                    //Lägger till malnummer i knappens text om det finns
                    if(instans.containsKey("malnummer")){
                        btnInstans.setText(btnInstans.getText() + " [" + instans.get("malnummer") + "]");
                    }
                    
                    //Lägger till metod vid knapp-tryck (genom klassen ActionListener)
                    btnInstans.addActionListener(new ActionListener() { //implementerar abstrakt klass i ny anonymklass
                        @Override //override av abstrkt metod
                        public void actionPerformed(ActionEvent e) {
                            System.out.println("Öppnar HallbarhetsmålHandläggare");
                            //new Hallbarhetsmal(idb, aid, hid) som (idb, aid, id)
                            //behöver inte skicka med användarens roll eftersom vi vet att vi är ett handläggar-fönster
                        }
                    });
                    pnlMal.add(btnInstans, 0); //lägger knappen i början av panelen för mål
                    System.out.println("Knapp för hållbarhetsmål har laddats");
                    break;

                case ADMIN:
                    btnInstans.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            System.out.println("Öppnar personallistaHandläggare");
                            //new PersonalListaAdmin(idb, this.aid, aid) som (idb, aid, id)                              
                        }
                    });
                    pnlAdmin.add(btnInstans, 0);
                    System.out.println("Knapp för admin har laddats");
                    break;

                case HANDLAGGARE:
                    btnInstans.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            System.out.println("Öppnar personallistaHandläggare");
                            //new PersonalListaAdmin(idb, this.aid, aid) som (idb, aid, id)                              
                        }
                    });
                    pnlHandlaggare.add(btnInstans, 0);
                    System.out.println("Knapp för handläggare har laddats");
                    break;

                case PARTNERS:
                    btnInstans.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            System.out.println("Öppnar PartnersHandläggare");
                            //new PartnersHandlaggare(idb, aid, pid) (idb, aid, id)
                        }
                    });
                    pnlPartners.add(btnInstans, 0);
                    System.out.println("Knapp för partners har laddats");
                    break;

                default:
                    throw new IllegalStateException();
            }
        }
    }
    
    private void skapaActionBtnLand(){
        btnLand.addActionListener(new ActionListener(){
            @Override    //BEHÖVER DENNA METOD VARA PUBLIC? VARFÖR?
            public void actionPerformed(ActionEvent e) {
                System.out.println("Öppnar land");   
                //new LandHandlaggare(idb, lid)
            }        
        });
    }
    
    private void skapaActionBtnProjektchef(JButton knapp){
        knapp.addActionListener(new ActionListener(){
            @Override 
            public void actionPerformed(ActionEvent e) {
                System.out.println("Öppnar projektchef");   
                //new Personalista(idb, aid)
            }        
        });
    }

    private void btnDeltagareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeltagareActionPerformed
        vaxlaPopupSynlighet(spnlDeltagare);

    }//GEN-LAST:event_btnDeltagareActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnMalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMalActionPerformed
        vaxlaPopupSynlighet(spnlMal);
    }//GEN-LAST:event_btnMalActionPerformed

    private void btnPartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartnersActionPerformed
        vaxlaPopupSynlighet(spnlPartners);

    }//GEN-LAST:event_btnPartnersActionPerformed

    private void btnBeskrivningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeskrivningActionPerformed
        vaxlaPopupSynlighet(spnlBeskrivning);
    }//GEN-LAST:event_btnBeskrivningActionPerformed

    private void btnAddHandlaggareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHandlaggareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddHandlaggareActionPerformed

    private void btnAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddAdminActionPerformed

    private void btnAddMalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddMalActionPerformed

    private void btnAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraActionPerformed
        //---Om användaren trycker på samma knapp i redigeringsläget (ångra knappen)---
        if(vaxlaRedigeringslage() == false){ 
            //laddar om infon, eventuella ändringar som gjordes i redigeringsläget försvinner
            laddaInfo(); 
        }
    }//GEN-LAST:event_btnAndraActionPerformed

    private void txtfStartDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfStartDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfStartDatumActionPerformed

    private void txtfSlutDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfSlutDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfSlutDatumActionPerformed

    private void txtfProjektnamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfProjektnamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfProjektnamnActionPerformed

    private void btnAddProjektchefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProjektchefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddProjektchefActionPerformed

    private void btnLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLandActionPerformed

    public static void main(String args[]) { //TA BORT MAIN METODEN TILLSLUT. NI SKA ENDAST ANVÄNDA MAIN METODEN I Startklassen
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        try {
            InfDB idb = new InfDB("sdgsweden", "3306", "root", "masterkey");
            new ProjektProjektchef(idb, 3, 2).setVisible(true);
            System.out.println("Databaskoppling skapad");
        } catch (InfException e) {
            System.out.println(e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAdmin;
    private javax.swing.JButton btnAddHandlaggare;
    private javax.swing.JButton btnAddMal;
    private javax.swing.JButton btnAddPartner;
    private javax.swing.JButton btnAddProjektchef;
    private javax.swing.JButton btnAndra;
    private javax.swing.JButton btnBeskrivning;
    private javax.swing.JButton btnDeltagare;
    private javax.swing.JButton btnLand;
    private javax.swing.JButton btnMal;
    private javax.swing.JButton btnPartners;
    private javax.swing.JButton btnSpara;
    private com.toedter.calendar.JDateChooser dateSlutDatum;
    private com.toedter.calendar.JDateChooser dateStartDatum;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAvslutad;
    private javax.swing.JLabel lblDeltagareTips;
    private javax.swing.JLabel lblFelmeddelande;
    private javax.swing.JLabel lblMalTips;
    private javax.swing.JLabel lblPartnersTips;
    private javax.swing.JLabel lblPid;
    private javax.swing.JLabel lblStartar;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlBeskrivning;
    private javax.swing.JPanel pnlDeltagare;
    private javax.swing.JPanel pnlHandlaggare;
    private javax.swing.JPanel pnlHoger;
    private javax.swing.JPanel pnlMal;
    private javax.swing.JPanel pnlPartners;
    private javax.swing.JPanel pnlProjektchef;
    private javax.swing.JPanel pnlProjektnamn;
    private javax.swing.JPanel pnlSlutDatum;
    private javax.swing.JPanel pnlStartDatum;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JPanel pnlVanster;
    private javax.swing.JScrollPane spnlBeskrivning;
    private javax.swing.JScrollPane spnlDeltagare;
    private javax.swing.JScrollPane spnlMal;
    private javax.swing.JScrollPane spnlPartners;
    private javax.swing.JScrollPane spnlTop;
    private javax.swing.JTextArea txarBeskrivning;
    private javax.swing.JTextField txtfKostnad;
    private javax.swing.JTextField txtfPrioritet;
    private javax.swing.JTextField txtfProjektnamn;
    private javax.swing.JTextField txtfSlutDatum;
    private javax.swing.JTextField txtfStartDatum;
    private javax.swing.JTextField txtfStatus;
    // End of variables declaration//GEN-END:variables
}