/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author alexander.willen
 */
public class ProjektUppgifter extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProjektUppgifter.class.getName());

    //Bakgrundsfärgen som används av vårt valda "tema" i NetBeans
    private static final Color bakgrundsfarg = new Color(212, 217, 223);

    //Redigeringsläge
    private boolean redigerar;

    /**
     * Creates new form Projekt
     */
    public ProjektUppgifter() {
        initComponents();

        //Fält
        redigerar = false;

        //Pop-up rutor---------------------
        spnlMal.setVisible(false);
        spnlBeskrivning.setVisible(false);
        spnlDeltagare.setVisible(false);
        spnlPartners.setVisible(false);

        //Redigerings-läget----------------
        //...Datum rutor
        dateStartDatum.setVisible(false);
        dateSlutDatum.setVisible(false);
        //...Adderingsknappar
        btnAddMal.setVisible(false);
        btnAddProjektchef.setVisible(false);
        btnAddAdmin.setVisible(false);
        btnAddHandlaggare.setVisible(false);
        btnAddPartner.setVisible(false);
        //...Tipsrutor
        lblMalTips.setVisible(false);
        lblDeltagareTips.setVisible(false);
        lblPartnersTips.setVisible(false);
        //...Felmeddelande
        lblFelmeddelande.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnlTop = new javax.swing.JScrollPane();
        pnlTop = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblStartar = new javax.swing.JLabel();
        lblAvslutad = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        pnlVanster = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        btnMal = new javax.swing.JButton();
        lblMalTips = new javax.swing.JLabel();
        spnlMal = new javax.swing.JScrollPane();
        pnlMal = new javax.swing.JPanel();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        btnAddMal = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        btnBeskrivning = new javax.swing.JButton();
        spnlBeskrivning = new javax.swing.JScrollPane();
        pnlBeskrivning = new javax.swing.JPanel();
        txarBesrkivning = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        pnlHoger = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btnDeltagare = new javax.swing.JButton();
        lblDeltagareTips = new javax.swing.JLabel();
        spnlDeltagare = new javax.swing.JScrollPane();
        pnlDeltagare = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnAddAdmin = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnAddHandlaggare = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnAddProjektchef = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        btnPartners = new javax.swing.JButton();
        lblPartnersTips = new javax.swing.JLabel();
        spnlPartners = new javax.swing.JScrollPane();
        pnlPartners = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        btnAddPartner = new javax.swing.JButton();
        txtfProjektnamn = new javax.swing.JTextField();
        pnlStartDatum = new javax.swing.JPanel();
        txtfStartDatum = new javax.swing.JTextField();
        dateStartDatum = new com.toedter.calendar.JDateChooser();
        pnlSlutDatum = new javax.swing.JPanel();
        txtfSlutDatum = new javax.swing.JTextField();
        dateSlutDatum = new com.toedter.calendar.JDateChooser();
        btnAndra = new javax.swing.JButton();
        btnSpara = new javax.swing.JButton();
        lblFelmeddelande = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        spnlTop.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        spnlTop.setPreferredSize(new java.awt.Dimension(730, 577));

        pnlTop.setMaximumSize(new java.awt.Dimension(700, 2000));

        jLabel2.setText("Projektid: [pid]");

        lblStartar.setText("Startad");

        lblAvslutad.setText("Avslutad");

        jButton8.setText("Tillbaka till Meny");
        jButton8.addActionListener(this::jButton8ActionPerformed);

        pnlVanster.setMaximumSize(new java.awt.Dimension(385, 30000));
        pnlVanster.setMinimumSize(new java.awt.Dimension(200, 260));
        pnlVanster.setPreferredSize(null);
        pnlVanster.setLayout(new javax.swing.BoxLayout(pnlVanster, javax.swing.BoxLayout.Y_AXIS));

        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel9.setMaximumSize(new java.awt.Dimension(310, 35));
        jPanel9.setPreferredSize(new java.awt.Dimension(250, 35));

        btnMal.setText("▶ Hållbarhetsmål");
        btnMal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMal.setMaximumSize(new java.awt.Dimension(86, 23));
        btnMal.setMinimumSize(new java.awt.Dimension(86, 23));
        btnMal.setPreferredSize(new java.awt.Dimension(86, 23));
        btnMal.addActionListener(this::btnMalActionPerformed);

        lblMalTips.setForeground(new java.awt.Color(204, 204, 0));
        lblMalTips.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMalTips.setText("Tryck för att ta bort");
        lblMalTips.setPreferredSize(new java.awt.Dimension(320, 16));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(btnMal, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMalTips, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMal, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMalTips, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlVanster.add(jPanel9);

        spnlMal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        spnlMal.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        spnlMal.setMaximumSize(new java.awt.Dimension(310, 120));
        spnlMal.setMinimumSize(new java.awt.Dimension(310, 100));
        spnlMal.setPreferredSize(new java.awt.Dimension(310, 100));

        pnlMal.setMaximumSize(null);
        pnlMal.setMinimumSize(new java.awt.Dimension(200, 90));
        pnlMal.setOpaque(false);
        pnlMal.setPreferredSize(new java.awt.Dimension(200, 90));
        pnlMal.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButton27.setText("[Hållbarhetsmål]");
        jButton27.addActionListener(this::jButton27ActionPerformed);
        pnlMal.add(jButton27);

        jButton28.setText("[Hållbarhetsmål]");
        pnlMal.add(jButton28);

        jButton30.setText("[Hållbarhetsmål]");
        pnlMal.add(jButton30);

        jButton31.setText("[Hållbarhetsmål]");
        pnlMal.add(jButton31);

        btnAddMal.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        btnAddMal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikoner/plusikon.png"))); // NOI18N
        btnAddMal.setIconTextGap(0);
        btnAddMal.setMargin(new java.awt.Insets(2, 13, 3, 14));
        btnAddMal.setPreferredSize(new java.awt.Dimension(19, 19));
        btnAddMal.addActionListener(this::btnAddMalActionPerformed);
        pnlMal.add(btnAddMal);

        spnlMal.setViewportView(pnlMal);

        pnlVanster.add(spnlMal);

        jPanel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel13.setMaximumSize(new java.awt.Dimension(310, 38));
        jPanel13.setMinimumSize(new java.awt.Dimension(139, 38));
        jPanel13.setName(""); // NOI18N
        jPanel13.setPreferredSize(new java.awt.Dimension(250, 38));

        btnBeskrivning.setText("▶ Beskrivning");
        btnBeskrivning.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBeskrivning.setMargin(new java.awt.Insets(0, 0, 0, 14));
        btnBeskrivning.setMaximumSize(new java.awt.Dimension(123, 30));
        btnBeskrivning.setMinimumSize(new java.awt.Dimension(123, 30));
        btnBeskrivning.setPreferredSize(new java.awt.Dimension(125, 30));
        btnBeskrivning.setVerifyInputWhenFocusTarget(false);
        btnBeskrivning.addActionListener(this::btnBeskrivningActionPerformed);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(btnBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 156, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(btnBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlVanster.add(jPanel13);

        spnlBeskrivning.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        spnlBeskrivning.setToolTipText("");
        spnlBeskrivning.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        spnlBeskrivning.setMaximumSize(new java.awt.Dimension(32767, 60));
        spnlBeskrivning.setMinimumSize(new java.awt.Dimension(225, 60));
        spnlBeskrivning.setPreferredSize(new java.awt.Dimension(230, 60));

        pnlBeskrivning.setMinimumSize(new java.awt.Dimension(220, 100));
        pnlBeskrivning.setName(""); // NOI18N
        pnlBeskrivning.setPreferredSize(null);
        pnlBeskrivning.setLayout(new java.awt.BorderLayout());

        txarBesrkivning.setColumns(5);
        txarBesrkivning.setLineWrap(true);
        txarBesrkivning.setRows(5);
        txarBesrkivning.setText("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
        txarBesrkivning.setWrapStyleWord(true);
        txarBesrkivning.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txarBesrkivning.setMaximumSize(new java.awt.Dimension(200, 84));
        txarBesrkivning.setMinimumSize(new java.awt.Dimension(200, 20));
        pnlBeskrivning.add(txarBesrkivning, java.awt.BorderLayout.PAGE_START);

        spnlBeskrivning.setViewportView(pnlBeskrivning);

        pnlVanster.add(spnlBeskrivning);

        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 0, 4, 0));
        jPanel10.setMaximumSize(new java.awt.Dimension(310, 32));
        jPanel10.setPreferredSize(new java.awt.Dimension(200, 32));

        jLabel12.setText("Land");

        jButton12.setText(" [Land]");
        jButton12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jButton12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton12.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton12.setMaximumSize(new java.awt.Dimension(100, 23));
        jButton12.setPreferredSize(new java.awt.Dimension(100, 23));
        jButton12.addActionListener(this::jButton12ActionPerformed);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1))
        );

        pnlVanster.add(jPanel10);

        jPanel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 0, 4, 0));
        jPanel12.setMaximumSize(new java.awt.Dimension(310, 32));
        jPanel12.setPreferredSize(new java.awt.Dimension(200, 32));

        jLabel13.setText("Status");

        jTextField1.setBackground(new java.awt.Color(212, 217, 223));
        jTextField1.setText("[Status]");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(36, 36, 36)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlVanster.add(jPanel12);

        jPanel14.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 0, 4, 0));
        jPanel14.setMaximumSize(new java.awt.Dimension(310, 32));
        jPanel14.setPreferredSize(new java.awt.Dimension(200, 32));

        jLabel15.setText("Prioritet");

        jTextField2.setBackground(new java.awt.Color(212, 217, 223));
        jTextField2.setText("[Prioritet]");
        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(29, 29, 29)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlVanster.add(jPanel14);

        jPanel15.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 0, 4, 0));
        jPanel15.setMaximumSize(new java.awt.Dimension(310, 32));
        jPanel15.setPreferredSize(new java.awt.Dimension(200, 32));

        jLabel17.setText("Kostnad");

        jTextField3.setBackground(new java.awt.Color(212, 217, 223));
        jTextField3.setText("[Kostnad]");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addGap(26, 26, 26)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlVanster.add(jPanel15);

        pnlHoger.setPreferredSize(null);
        pnlHoger.setLayout(new javax.swing.BoxLayout(pnlHoger, javax.swing.BoxLayout.Y_AXIS));

        jPanel8.setMaximumSize(new java.awt.Dimension(32767, 27));
        jPanel8.setPreferredSize(new java.awt.Dimension(456, 27));

        btnDeltagare.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDeltagare.setLabel("▼ Deltagare");
        btnDeltagare.setMaximumSize(new java.awt.Dimension(93, 27));
        btnDeltagare.setMinimumSize(new java.awt.Dimension(93, 27));
        btnDeltagare.setPreferredSize(new java.awt.Dimension(93, 27));
        btnDeltagare.addActionListener(this::btnDeltagareActionPerformed);

        lblDeltagareTips.setForeground(new java.awt.Color(204, 204, 0));
        lblDeltagareTips.setText("Tryck för att ta bort");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(btnDeltagare, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(145, 145, 145)
                    .addComponent(lblDeltagareTips)
                    .addContainerGap(130, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(btnDeltagare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDeltagareTips)
                    .addContainerGap()))
        );

        pnlHoger.add(jPanel8);

        spnlDeltagare.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        spnlDeltagare.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        spnlDeltagare.setMaximumSize(new java.awt.Dimension(32767, 300));
        spnlDeltagare.setPreferredSize(new java.awt.Dimension(395, 300));

        pnlDeltagare.setMaximumSize(new java.awt.Dimension(350, 30000));
        pnlDeltagare.setMinimumSize(new java.awt.Dimension(350, 200));
        pnlDeltagare.setPreferredSize(new java.awt.Dimension(350, 200));

        jLabel7.setText("Projektchef");

        jButton3.setText("[namn]");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jLabel8.setText("Administratörer");

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jButton4.setText("[namn]");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel2.add(jButton4);

        jButton5.setText("[namn]");
        jPanel2.add(jButton5);

        btnAddAdmin.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        btnAddAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikoner/plusikon.png"))); // NOI18N
        btnAddAdmin.setIconTextGap(0);
        btnAddAdmin.setMargin(new java.awt.Insets(2, 13, 3, 14));
        btnAddAdmin.setPreferredSize(new java.awt.Dimension(19, 19));
        btnAddAdmin.addActionListener(this::btnAddAdminActionPerformed);
        jPanel2.add(btnAddAdmin);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jButton7.setText("[namn]");
        jPanel3.add(jButton7);

        jButton6.setText("[namn]");
        jButton6.addActionListener(this::jButton6ActionPerformed);
        jPanel3.add(jButton6);

        btnAddHandlaggare.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        btnAddHandlaggare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikoner/plusikon.png"))); // NOI18N
        btnAddHandlaggare.setIconTextGap(0);
        btnAddHandlaggare.setMargin(new java.awt.Insets(2, 13, 3, 14));
        btnAddHandlaggare.setPreferredSize(new java.awt.Dimension(19, 19));
        btnAddHandlaggare.addActionListener(this::btnAddHandlaggareActionPerformed);
        jPanel3.add(btnAddHandlaggare);

        jLabel9.setText("Handläggare");

        btnAddProjektchef.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        btnAddProjektchef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikoner/plusikon.png"))); // NOI18N
        btnAddProjektchef.setIconTextGap(0);
        btnAddProjektchef.setMargin(new java.awt.Insets(2, 13, 3, 14));
        btnAddProjektchef.setPreferredSize(new java.awt.Dimension(19, 19));
        btnAddProjektchef.addActionListener(this::btnAddProjektchefActionPerformed);

        javax.swing.GroupLayout pnlDeltagareLayout = new javax.swing.GroupLayout(pnlDeltagare);
        pnlDeltagare.setLayout(pnlDeltagareLayout);
        pnlDeltagareLayout.setHorizontalGroup(
            pnlDeltagareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDeltagareLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDeltagareLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDeltagareLayout.createSequentialGroup()
                .addGroup(pnlDeltagareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDeltagareLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlDeltagareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addGroup(pnlDeltagareLayout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(btnAddProjektchef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(14, 14, 14))
        );
        pnlDeltagareLayout.setVerticalGroup(
            pnlDeltagareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeltagareLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGroup(pnlDeltagareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDeltagareLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(7, 7, 7)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addGroup(pnlDeltagareLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnAddProjektchef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        spnlDeltagare.setViewportView(pnlDeltagare);

        pnlHoger.add(spnlDeltagare);

        jPanel11.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel11.setPreferredSize(new java.awt.Dimension(456, 40));

        btnPartners.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPartners.setLabel("▼ Partners");
        btnPartners.setVerifyInputWhenFocusTarget(false);
        btnPartners.addActionListener(this::btnPartnersActionPerformed);

        lblPartnersTips.setForeground(new java.awt.Color(204, 204, 0));
        lblPartnersTips.setText("Tryck för att ta bort");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(btnPartners, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblPartnersTips)
                .addGap(0, 130, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPartners, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPartnersTips)))
        );

        pnlHoger.add(jPanel11);

        spnlPartners.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        spnlPartners.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        spnlPartners.setMinimumSize(new java.awt.Dimension(16, 100));
        spnlPartners.setPreferredSize(new java.awt.Dimension(375, 100));

        pnlPartners.setMaximumSize(null);
        pnlPartners.setMinimumSize(new java.awt.Dimension(350, 60));
        pnlPartners.setPreferredSize(new java.awt.Dimension(350, 60));
        pnlPartners.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButton1.setText("[partner]");
        pnlPartners.add(jButton1);

        jButton9.setText("[partner]");
        pnlPartners.add(jButton9);

        btnAddPartner.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        btnAddPartner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikoner/plusikon.png"))); // NOI18N
        btnAddPartner.setIconTextGap(0);
        btnAddPartner.setMargin(new java.awt.Insets(2, 13, 3, 14));
        btnAddPartner.setPreferredSize(new java.awt.Dimension(19, 19));
        pnlPartners.add(btnAddPartner);

        spnlPartners.setViewportView(pnlPartners);

        pnlHoger.add(spnlPartners);

        txtfProjektnamn.setBackground(new java.awt.Color(212, 217, 223));
        txtfProjektnamn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtfProjektnamn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfProjektnamn.setText("[Projektnamn]");
        txtfProjektnamn.setBorder(null);
        txtfProjektnamn.setOpaque(true);
        txtfProjektnamn.addActionListener(this::txtfProjektnamnActionPerformed);

        pnlStartDatum.setMinimumSize(new java.awt.Dimension(20, 20));
        pnlStartDatum.setPreferredSize(new java.awt.Dimension(20, 22));
        pnlStartDatum.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtfStartDatum.setEditable(false);
        txtfStartDatum.setBackground(new java.awt.Color(212, 217, 223));
        txtfStartDatum.setText("ÅÅÅÅ-MM-DD");
        txtfStartDatum.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 3, 0, 0));
        txtfStartDatum.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtfStartDatum.setPreferredSize(new java.awt.Dimension(86, 16));
        txtfStartDatum.addActionListener(this::txtfStartDatumActionPerformed);
        pnlStartDatum.add(txtfStartDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));
        pnlStartDatum.add(dateStartDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 20));

        pnlSlutDatum.setMinimumSize(new java.awt.Dimension(20, 20));
        pnlSlutDatum.setPreferredSize(new java.awt.Dimension(20, 22));
        pnlSlutDatum.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtfSlutDatum.setEditable(false);
        txtfSlutDatum.setBackground(new java.awt.Color(212, 217, 223));
        txtfSlutDatum.setText("ÅÅÅÅ-MM-DD");
        txtfSlutDatum.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 3, 0, 0));
        txtfSlutDatum.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtfSlutDatum.setPreferredSize(new java.awt.Dimension(86, 16));
        txtfSlutDatum.addActionListener(this::txtfSlutDatumActionPerformed);
        pnlSlutDatum.add(txtfSlutDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));
        pnlSlutDatum.add(dateSlutDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 20));

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addComponent(pnlVanster, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(pnlHoger, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(52, 52, 52))
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTopLayout.createSequentialGroup()
                                .addGap(312, 312, 312)
                                .addComponent(lblStartar)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblAvslutad)
                                .addGap(17, 17, 17)))
                        .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlSlutDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(pnlStartDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(txtfProjektnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addComponent(txtfProjektnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStartar)
                            .addComponent(pnlStartDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlSlutDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lblAvslutad)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlVanster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlHoger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        spnlTop.setViewportView(pnlTop);

        btnAndra.setText("Ändra");
        btnAndra.addActionListener(this::btnAndraActionPerformed);

        btnSpara.setText("Spara");

        lblFelmeddelande.setForeground(new java.awt.Color(255, 51, 0));
        lblFelmeddelande.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFelmeddelande.setText("[felmeddelande]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAndra, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnSpara, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(spnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblFelmeddelande, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(spnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAndra)
                    .addComponent(btnSpara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFelmeddelande)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeltagareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeltagareActionPerformed
        vaxlaSynlighet(spnlDeltagare);
    }//GEN-LAST:event_btnDeltagareActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnMalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMalActionPerformed
        vaxlaSynlighet(spnlMal);
    }//GEN-LAST:event_btnMalActionPerformed

    private void btnPartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartnersActionPerformed
        vaxlaSynlighet(spnlPartners);

    }//GEN-LAST:event_btnPartnersActionPerformed

    private void btnBeskrivningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeskrivningActionPerformed
        vaxlaSynlighet(spnlBeskrivning);
    }//GEN-LAST:event_btnBeskrivningActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void btnAddHandlaggareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHandlaggareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddHandlaggareActionPerformed

    private void txtfProjektnamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfProjektnamnActionPerformed
        // TODO add your handling code here:
        txtfProjektnamn.setBackground(bakgrundsfarg);
    }//GEN-LAST:event_txtfProjektnamnActionPerformed

    private void btnAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddAdminActionPerformed

    private void btnAddMalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddMalActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void btnAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraActionPerformed
        vaxlaRedigeringslage();
    }//GEN-LAST:event_btnAndraActionPerformed

    private void btnAddProjektchefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProjektchefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddProjektchefActionPerformed

    private void txtfStartDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfStartDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfStartDatumActionPerformed

    private void txtfSlutDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfSlutDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfSlutDatumActionPerformed

    //LÄGG I EN UTILITY-KLASS?
    private void vaxlaSynlighet(JScrollPane popUpRuta)//gör mer "generell"? Passar namnet bättre. JComponent kan downcastas?
    {
        Boolean rutaNySynlighet = !popUpRuta.isVisible();

        popUpRuta.setVisible(rutaNySynlighet);

        //Uppdaterar layout för allt inom pupUpRutans parent-container
        popUpRuta.getParent().revalidate();
        //pnlVanster.repaint();  -LÄGG TILL VID BEHOV                             
    }

    private void vaxlaRedigeringslage() {
        //Växla mellan redigeringslägen 
        redigerar = !redigerar;

        if (redigerar) {
            //Redigeringsläge växlades på
            btnAndra.setText("Ångra");
        } else {
            //Redigeringsläge växlades av
            btnAndra.setText("Ändra");

            //FUNKTIONALITETSUTÖKNING:
            //Fönster-pup-up som säger "Är du säker att du vill ångra och ej spara förändringar?" om förändringar skett.
            //"Ja" och "Nej" knappar
            //Checkbox: "visa inte detta meddelande igen"
        }

        //---Sätter synlighet för redigerings-GUI---
        boolean nySynlighet = redigerar;
        //...Datum rutor
        dateStartDatum.setVisible(nySynlighet);
        dateSlutDatum.setVisible(nySynlighet);
        txtfStartDatum.setVisible(!nySynlighet);
        txtfSlutDatum.setVisible(!nySynlighet);
        //...Adderingsknappar
        btnAddMal.setVisible(nySynlighet);
        btnAddProjektchef.setVisible(nySynlighet);
        btnAddAdmin.setVisible(nySynlighet);
        btnAddHandlaggare.setVisible(nySynlighet);
        btnAddPartner.setVisible(nySynlighet);
        //...Tipsrutor
        lblMalTips.setVisible(nySynlighet);
        lblDeltagareTips.setVisible(nySynlighet);
        lblPartnersTips.setVisible(nySynlighet);
        //...Öppna pop-ups
        if (redigerar) {
            spnlMal.setVisible(true);
            spnlBeskrivning.setVisible(true);
            spnlDeltagare.setVisible(true);
            spnlPartners.setVisible(true);
        }

        //Uppdatera layout
        pnlTop.revalidate();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) { //TA BORT MAIN METODEN TILLSLUT. NI SKA ENDAST ANVÄNDA MAIN METODEN I Startklassen
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProjektUppgifter().setVisible(true));

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAdmin;
    private javax.swing.JButton btnAddHandlaggare;
    private javax.swing.JButton btnAddMal;
    private javax.swing.JButton btnAddPartner;
    private javax.swing.JButton btnAddProjektchef;
    private javax.swing.JButton btnAndra;
    private javax.swing.JButton btnBeskrivning;
    private javax.swing.JButton btnDeltagare;
    private javax.swing.JButton btnMal;
    private javax.swing.JButton btnPartners;
    private javax.swing.JButton btnSpara;
    private com.toedter.calendar.JDateChooser dateSlutDatum;
    private com.toedter.calendar.JDateChooser dateStartDatum;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblAvslutad;
    private javax.swing.JLabel lblDeltagareTips;
    private javax.swing.JLabel lblFelmeddelande;
    private javax.swing.JLabel lblMalTips;
    private javax.swing.JLabel lblPartnersTips;
    private javax.swing.JLabel lblStartar;
    private javax.swing.JPanel pnlBeskrivning;
    private javax.swing.JPanel pnlDeltagare;
    private javax.swing.JPanel pnlHoger;
    private javax.swing.JPanel pnlMal;
    private javax.swing.JPanel pnlPartners;
    private javax.swing.JPanel pnlSlutDatum;
    private javax.swing.JPanel pnlStartDatum;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JPanel pnlVanster;
    private javax.swing.JScrollPane spnlBeskrivning;
    private javax.swing.JScrollPane spnlDeltagare;
    private javax.swing.JScrollPane spnlMal;
    private javax.swing.JScrollPane spnlPartners;
    private javax.swing.JScrollPane spnlTop;
    private javax.swing.JTextArea txarBesrkivning;
    private javax.swing.JTextField txtfProjektnamn;
    private javax.swing.JTextField txtfSlutDatum;
    private javax.swing.JTextField txtfStartDatum;
    // End of variables declaration//GEN-END:variables
}
