/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

/**
 *
 * @author alexander.willen
 */
import oru.inf.InfDB;
import java.awt.Color;

public class UppgifterHandlaggare extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UppgifterHandlaggare.class.getName());
    private Anvandare anvandare;
    
    private InfDB idb;
    private String dbNamn;
    private String dbEfternamn;
    private String dbAnstallningsdatum;      
    private int aid;
    private String dbAnvandaresAdress;
    private String dbAnvandaresTelefon;
    private String dbAnvandareslosenord;

    /**
     * Creates new form Uppgifter_Handläggare
     */
    public UppgifterHandlaggare(Anvandare anvandare) {
        initComponents();

        this.anvandare = anvandare;

        this.idb = anvandare.getIdb();

        this.aid = anvandare.getAid();

        this.dbNamn = anvandare.getDbNamn();
        this.dbEfternamn = anvandare.getDbEfternamn();

        this.dbAnstallningsdatum = anvandare.getDbAnstallningsdatum();

        this.dbAnvandaresAdress = anvandare.getDbAnvandaresAdress();

        this.dbAnvandaresTelefon = anvandare.getDbAnvandaresTelefon();

        this.dbAnvandareslosenord = anvandare.getDbAnvandareslosenord();
        
        lblAid.setText("AnställningsID: " + aid);
        lblAnställdSedan.setText("Anställd sedan: " + dbAnstallningsdatum);
        try{
        lblAvdelningsNamnOchID.setText(idb.fetchSingle("SELECT namn,avdid FROM avdelning where chef = '"+ aid+"'"));
        txtHandläggaresEfternamn.setText(idb.fetchSingle("SELECT efternamn FROM anstalld where aid = '"+ aid+"'"));
        txtHandläggaresNamn.setText(idb.fetchSingle("SELECT fornamn FROM anstalld where aid = '"+ aid+"'"));
        txtHandläggaresTelefon.setText(idb.fetchSingle("SELECT telefon FROM anstalld where aid = '"+ aid+"'"));
        txtHandläggaresAdress.setText(idb.fetchSingle("SELECT adress FROM anstalld where aid = '"+ aid+"'"));
        txtHandläggaresEpost.setText(idb.fetchSingle("SELECT epost FROM anstalld where aid = '"+ aid+"'"));
        
        txtAnsvarsområde.setText(idb.fetchSingle("SELECT ansvarighetsomrade FROM handlaggare where aid = '"+ aid+"'"));
        txtMentor.setText(idb.fetchSingle("SELECT CONCAT(fornamn, ' ', efternamn) FROM anstalld " + "WHERE aid = (SELECT mentor FROM handlaggare " + "WHERE aid = '" + aid + "')"));
        txtMentorFör.setText(idb.fetchSingle("SELECT GROUP_CONCAT(CONCAT(fornamn, ' ', efternamn) SEPARATOR ', ') " + "FROM anstalld " + "WHERE aid IN (SELECT aid FROM handlaggare " + "WHERE mentor = '" + aid + "')"));

        
        
        
        txtHandläggaresNamn.setEditable(false);
        txtHandläggaresEfternamn.setEditable(false);
        txtHandläggaresTelefon.setEditable(false);
        txtHandläggaresAdress.setEditable(false);
        txtHandläggaresEpost.setEditable(false);
        
        txtAnsvarsområde.setEditable(false);
        txtMentor.setEditable(false);
        txtMentorFör.setEditable(false);

        txtHandläggaresNamn.setBackground(Color.LIGHT_GRAY);
        txtHandläggaresEfternamn.setBackground(Color.LIGHT_GRAY);
        txtHandläggaresTelefon.setBackground(Color.LIGHT_GRAY);
        txtHandläggaresAdress.setBackground(Color.LIGHT_GRAY);
        txtHandläggaresEpost.setBackground(Color.LIGHT_GRAY);
        
        txtAnsvarsområde.setBackground(Color.LIGHT_GRAY);
        txtMentor.setBackground(Color.LIGHT_GRAY);
        txtMentorFör.setBackground(Color.LIGHT_GRAY);
        
        }catch(Exception ex){
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnÄndra = new javax.swing.JButton();
        btnSpara = new javax.swing.JButton();
        txtHandläggaresNamn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblAid = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblAnställdSedan = new javax.swing.JLabel();
        lblAvdelningsNamnOchID = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblTillbakaTillMeny = new javax.swing.JButton();
        txtHandläggaresEfternamn = new javax.swing.JTextField();
        txtHandläggaresAdress = new javax.swing.JTextField();
        txtHandläggaresEpost = new javax.swing.JTextField();
        txtHandläggaresTelefon = new javax.swing.JTextField();
        txtAnsvarsområde = new javax.swing.JTextField();
        txtMentor = new javax.swing.JTextField();
        txtMentorFör = new javax.swing.JTextField();

        jButton2.setText("jButton2");

        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Förnamn");

        jLabel2.setText("Efternamn");

        jLabel3.setText("Telefonnummer");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Mina uppgifter");

        jLabel5.setText("Adress");

        btnÄndra.setText("Ändra");
        btnÄndra.addActionListener(this::btnÄndraActionPerformed);

        btnSpara.setText("Spara");
        btnSpara.addActionListener(this::btnSparaActionPerformed);

        txtHandläggaresNamn.addActionListener(this::txtHandläggaresNamnActionPerformed);

        jLabel6.setText("Epost");

        lblAid.setText("AnställningsID: [aid]");

        jLabel9.setText("Avdelning");

        jLabel10.setText("Mentor");

        jLabel11.setText("Mentor för");

        lblAnställdSedan.setText("Sedan [AnstDatum] ");

        lblAvdelningsNamnOchID.setText("[Namn+ID]");

        jLabel15.setText("Ansvarsområde");

        jLabel18.setText("jLabel18");

        lblTillbakaTillMeny.setText("Tillbaka till Meny");
        lblTillbakaTillMeny.addActionListener(this::lblTillbakaTillMenyActionPerformed);

        txtHandläggaresEfternamn.addActionListener(this::txtHandläggaresEfternamnActionPerformed);

        txtHandläggaresAdress.addActionListener(this::txtHandläggaresAdressActionPerformed);

        txtHandläggaresEpost.addActionListener(this::txtHandläggaresEpostActionPerformed);

        txtHandläggaresTelefon.addActionListener(this::txtHandläggaresTelefonActionPerformed);

        txtAnsvarsområde.addActionListener(this::txtAnsvarsområdeActionPerformed);

        txtMentor.addActionListener(this::txtMentorActionPerformed);

        txtMentorFör.addActionListener(this::txtMentorFörActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(428, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(107, 107, 107))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTillbakaTillMeny)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAnställdSedan, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAid, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnÄndra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSpara))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAvdelningsNamnOchID)
                            .addComponent(txtMentor, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(txtMentorFör, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(txtHandläggaresEpost, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(txtHandläggaresEfternamn, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(txtHandläggaresAdress, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(txtHandläggaresTelefon, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(txtAnsvarsområde, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHandläggaresNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAnsvarsområde, txtHandläggaresAdress, txtHandläggaresEfternamn, txtHandläggaresEpost, txtHandläggaresTelefon, txtMentor, txtMentorFör});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAnställdSedan))
                    .addComponent(lblTillbakaTillMeny))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtHandläggaresNamn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHandläggaresEfternamn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHandläggaresTelefon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtHandläggaresAdress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHandläggaresEpost))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtAnsvarsområde))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtMentor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtMentorFör))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblAvdelningsNamnOchID))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnÄndra)
                    .addComponent(btnSpara))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnÄndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÄndraActionPerformed
        // Jag tycker att bara admin kan ändra namn och efternamn på anställda.
        
        //txtHandläggaresNamn.setEditable(true);
        //txtHandläggaresEfternamn.setEditable(true);
        txtHandläggaresTelefon.setEditable(true);
        txtHandläggaresAdress.setEditable(true);
        txtHandläggaresEpost.setEditable(true);
        
        txtAnsvarsområde.setEditable(true);
        txtMentor.setEditable(true);
        // aid ändring RISK!!!!
        //txtMentorFör.setEditable(true);

        //txtHandläggaresNamn.setBackground(Color.WHITE);
        //txtHandläggaresEfternamn.setBackground(Color.WHITE);
        txtHandläggaresTelefon.setBackground(Color.WHITE);
        txtHandläggaresAdress.setBackground(Color.WHITE);
        txtHandläggaresEpost.setBackground(Color.WHITE);
        
        txtAnsvarsområde.setBackground(Color.WHITE);
        txtMentor.setBackground(Color.WHITE);
       // txtMentorFör.setBackground(Color.WHITE);
        
    }//GEN-LAST:event_btnÄndraActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        try{
            
        String nyttTelefonnummer = txtHandläggaresTelefon.getText();
        String nyAdress = txtHandläggaresAdress.getText();
        String nyEpost = txtHandläggaresEpost.getText();
        
        String nyAnsvarsområde = txtAnsvarsområde.getText();
        String nyMentor = txtMentor.getText();
        
        String nyMentorFör = txtMentorFör.getText();
        
        String sqlFråga1 = "UPDATE anstalld SET "
                + "telefon = '" + nyttTelefonnummer + "', "
                + "adress = '" + nyAdress + "', "
                + "epost = '" + nyEpost + "' "
                + "WHERE aid = '" + aid + "'";
        idb.update(sqlFråga1);
        
        String sqlFråga2 ="UPDATE handlaggare SET "
                + "ansvarighetsomrade = '" + nyAnsvarsområde + "'"
                + "WHERE aid = '" + aid + "'";
        
        idb.update(sqlFråga2);
        
        String sqlFråga3 ="UPDATE handlaggare SET "
                + "mentor = '" + nyMentor + "'"
                + "WHERE aid = '" + aid + "'";
        
        idb.update(sqlFråga3);
        // tycker inte att en handläggare eller projektchef ska kunna ändra vem de är mentorer för då riskerar vi ändra aid i hela projektet
       // String sqlFråga4 ="UPDATE handlaggare SET "
              //  + "aid = '" + nyMentorFör + "'";
        
        //idb.update(sqlFråga4);
        
        txtHandläggaresTelefon.setEditable(false);
        txtHandläggaresAdress.setEditable(false);
        txtHandläggaresEpost.setEditable(false);
        
        txtAnsvarsområde.setEditable(false);
        txtMentor.setEditable(false);
        txtMentorFör.setEditable(false);
        
        txtHandläggaresTelefon.setBackground(Color.LIGHT_GRAY);
        txtHandläggaresAdress.setBackground(Color.LIGHT_GRAY);
        txtHandläggaresEpost.setBackground(Color.LIGHT_GRAY);
        
        txtAnsvarsområde.setBackground(Color.LIGHT_GRAY);
        txtMentor.setBackground(Color.LIGHT_GRAY);
        txtMentorFör.setBackground(Color.LIGHT_GRAY);
        }
        catch(Exception ex){
            
        }
    }//GEN-LAST:event_btnSparaActionPerformed

    private void lblTillbakaTillMenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblTillbakaTillMenyActionPerformed
        new MenyHandlaggareProjektchef(anvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblTillbakaTillMenyActionPerformed

    private void txtHandläggaresNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHandläggaresNamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHandläggaresNamnActionPerformed

    private void txtHandläggaresEfternamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHandläggaresEfternamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHandläggaresEfternamnActionPerformed

    private void txtHandläggaresAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHandläggaresAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHandläggaresAdressActionPerformed

    private void txtHandläggaresEpostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHandläggaresEpostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHandläggaresEpostActionPerformed

    private void txtHandläggaresTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHandläggaresTelefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHandläggaresTelefonActionPerformed

    private void txtAnsvarsområdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnsvarsområdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnsvarsområdeActionPerformed

    private void txtMentorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMentorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMentorActionPerformed

    private void txtMentorFörActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMentorFörActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMentorFörActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new UppgifterHandlaggare().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnÄndra;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAid;
    private javax.swing.JLabel lblAnställdSedan;
    private javax.swing.JLabel lblAvdelningsNamnOchID;
    private javax.swing.JButton lblTillbakaTillMeny;
    private javax.swing.JTextField txtAnsvarsområde;
    private javax.swing.JTextField txtHandläggaresAdress;
    private javax.swing.JTextField txtHandläggaresEfternamn;
    private javax.swing.JTextField txtHandläggaresEpost;
    private javax.swing.JTextField txtHandläggaresNamn;
    private javax.swing.JTextField txtHandläggaresTelefon;
    private javax.swing.JTextField txtMentor;
    private javax.swing.JTextField txtMentorFör;
    // End of variables declaration//GEN-END:variables
}
