/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

/**
 *
 * @author alexander.willen
 */
public class Hallbarhetsmal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Hallbarhetsmal.class.getName());

    /**
     * Creates new form Hallbarhetsmal
     */
    public Hallbarhetsmal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Tillbaka till Meny");

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 0, 4, 0));
        jPanel10.setMaximumSize(new java.awt.Dimension(580, 32));
        jPanel10.setPreferredSize(new java.awt.Dimension(600, 32));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.X_AXIS));

        jLabel12.setText("Namn");
        jLabel12.setMaximumSize(new java.awt.Dimension(150, 16));
        jLabel12.setMinimumSize(new java.awt.Dimension(150, 16));
        jLabel12.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel10.add(jLabel12);

        jLabel13.setText("målnummer");
        jLabel13.setMaximumSize(new java.awt.Dimension(80, 16));
        jLabel13.setMinimumSize(new java.awt.Dimension(80, 16));
        jLabel13.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel10.add(jLabel13);

        jLabel14.setText("Beskrivning");
        jLabel14.setMaximumSize(new java.awt.Dimension(270, 16));
        jLabel14.setMinimumSize(new java.awt.Dimension(270, 16));
        jLabel14.setPreferredSize(new java.awt.Dimension(270, 16));
        jPanel10.add(jLabel14);

        jLabel15.setText("Prioritet");
        jLabel15.setMaximumSize(new java.awt.Dimension(180, 16));
        jLabel15.setPreferredSize(new java.awt.Dimension(180, 16));
        jPanel10.add(jLabel15);

        jPanel6.add(jPanel10);
        jPanel6.add(jSeparator1);

        jPanel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 0, 4, 0));
        jPanel11.setMaximumSize(new java.awt.Dimension(580, 32));
        jPanel11.setPreferredSize(new java.awt.Dimension(600, 32));
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.X_AXIS));

        jLabel16.setText("[namn]");
        jLabel16.setMaximumSize(new java.awt.Dimension(150, 16));
        jLabel16.setMinimumSize(new java.awt.Dimension(150, 16));
        jLabel16.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel11.add(jLabel16);

        jLabel17.setText("[målnummer]");
        jLabel17.setMaximumSize(new java.awt.Dimension(80, 16));
        jLabel17.setMinimumSize(new java.awt.Dimension(80, 16));
        jLabel17.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel11.add(jLabel17);

        jLabel18.setText("[beskrivning]");
        jLabel18.setMaximumSize(new java.awt.Dimension(270, 16));
        jLabel18.setMinimumSize(new java.awt.Dimension(270, 16));
        jLabel18.setPreferredSize(new java.awt.Dimension(270, 16));
        jPanel11.add(jLabel18);

        jLabel19.setText("[prioritet]");
        jLabel19.setMaximumSize(new java.awt.Dimension(180, 16));
        jLabel19.setPreferredSize(new java.awt.Dimension(180, 16));
        jPanel11.add(jLabel19);

        jPanel6.add(jPanel11);

        jPanel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 0, 4, 0));
        jPanel12.setMaximumSize(new java.awt.Dimension(580, 32));
        jPanel12.setPreferredSize(new java.awt.Dimension(600, 32));
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.X_AXIS));

        jLabel20.setText("[namn]");
        jLabel20.setMaximumSize(new java.awt.Dimension(150, 16));
        jLabel20.setMinimumSize(new java.awt.Dimension(150, 16));
        jLabel20.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel12.add(jLabel20);

        jLabel21.setText("[målnummer]");
        jLabel21.setMaximumSize(new java.awt.Dimension(80, 16));
        jLabel21.setMinimumSize(new java.awt.Dimension(80, 16));
        jLabel21.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel12.add(jLabel21);

        jLabel22.setText("[beskrivning]");
        jLabel22.setMaximumSize(new java.awt.Dimension(270, 16));
        jLabel22.setMinimumSize(new java.awt.Dimension(270, 16));
        jLabel22.setPreferredSize(new java.awt.Dimension(270, 16));
        jPanel12.add(jLabel22);

        jLabel23.setText("[prioritet]");
        jLabel23.setMaximumSize(new java.awt.Dimension(180, 16));
        jLabel23.setPreferredSize(new java.awt.Dimension(180, 16));
        jPanel12.add(jLabel23);

        jPanel6.add(jPanel12);

        jScrollPane1.setViewportView(jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(502, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(385, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(120, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Hallbarhetsmal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
